ArtyK's Console Engine: ace::math::lookup Namespace Reference
ace::math::lookup Namespace Reference
This namespace contains the engine's math lookup functions.
Namespaces
namespace _tables
This namespace contains the engine's lookup tables (raw numbers)
Functions
constexpr std::size_t _getTrigTableIndex (const llint a) noexcept
Returns the index to the trig table from the given (int) degree number.
constexpr float sinDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of sine in the table.
constexpr float cosDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cosine in the table.
constexpr float tanDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of tangent in the table.
constexpr float cotDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cotangent in the table.
constexpr float cscDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cosecant in the table.
constexpr float secDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of secant in the table.
constexpr float sinDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated sine value from the sine lookup table.
constexpr float cosDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated cosine value from the cosine lookup table.
constexpr float tanDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated tangent value from the tangent lookup table.
constexpr float cotDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated cotangent value from the cotangent lookup table.
constexpr float cscDeg_tableInterp (const float degrees) noexcept
Approximates the interpolated cosecant value from the cosecant lookup table.
constexpr float secDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated secant value from the secant lookup table.
Detailed Description
This namespace contains the engine's math lookup functions.
These will be insanely fast, since it's almost just an array lookup (ignoring the rounding and casting passed floats to int)
But since this is a lookup table:
It won't be as precise – error within 1 degree (or even less, with the interpolated functions)
It can increase compile time of the project
Also it can put a strain on cache and increase misses
It can increase memory usage (will be true whenever the lookup table size ever becomes custom-controlled)
Function Documentation
_getTrigTableIndex()
constexpr std::size_t ace::math::lookup::_getTrigTableIndex (const llint a) constexpr noexcept
Returns the index to the trig table from the given (int) degree number.
Remarks
If the number is negative, it wraps it from the end (-1 is the last item of the table)
Note
Not recommended to use directly. It's a helper function for the trig lookup table functions
Parameters
a The integer degree number
Returns
The legal index to the lookup tables
Definition at line 129 of file AEMathTrigLookup.hpp.
References AETRIG_TABLE_SIZE.
sinDeg_table()
constexpr float ace::math::lookup::sinDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of sine in the table.
Parameters
degrees The value of degrees to find a sine from
Returns
Float sine lookup table value that matches the (rounded) degrees amount
Definition at line 143 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::sinTable.
cosDeg_table()
constexpr float ace::math::lookup::cosDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cosine in the table.
Parameters
degrees The value of degrees to find a cosine from
Returns
Float cosine lookup table value that matches the (rounded) degrees amount
Definition at line 156 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::cosTable.
tanDeg_table()
constexpr float ace::math::lookup::tanDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of tangent in the table.
Parameters
degrees The value of degrees to find a tangent from
Returns
Float tangent lookup table value that matches the (rounded) degrees amount
Definition at line 169 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::tanTable.
cotDeg_table()
constexpr float ace::math::lookup::cotDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cotangent in the table.
Parameters
degrees The value of degrees to find a cotangent from
Returns
Float cotangent lookup table value that matches the (rounded) degrees amount
Definition at line 182 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::cotTable.
cscDeg_table()
constexpr float ace::math::lookup::cscDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cosecant in the table.
Parameters
degrees The value of degrees to find a cosecant from
Returns
Float cosecant lookup table value that matches the (rounded) degrees amount
Definition at line 195 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::cscTable.
secDeg_table()
constexpr float ace::math::lookup::secDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of secant in the table.
Parameters
degrees The value of degrees to find a secant from
Returns
Float secant lookup table value that matches the (rounded) degrees amount
Definition at line 208 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::secTable.
sinDeg_tableInterp()
constexpr float ace::math::lookup::sinDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated sine value from the sine lookup table.
Note
Correct to the sine value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a sine from
Returns
Float of interpolated sine value
Definition at line 222 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), and ace::math::lookup::_tables::sinTable.
cosDeg_tableInterp()
constexpr float ace::math::lookup::cosDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated cosine value from the cosine lookup table.
Note
Correct to the cosine value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cosine from
Returns
Float of interpolated cosine value
Definition at line 243 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), ace::math::lookup::_tables::cosTable, and ace::math::truncToInt().
tanDeg_tableInterp()
constexpr float ace::math::lookup::tanDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated tangent value from the tangent lookup table.
Note
Correct to the tangent value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a tangent from
Returns
Float of interpolated tangent value
Definition at line 264 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), ace::math::lookup::_tables::tanTable, and ace::math::truncToInt().
cotDeg_tableInterp()
constexpr float ace::math::lookup::cotDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated cotangent value from the cotangent lookup table.
Note
Correct to the cotangent value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cotangent from
Returns
Float of interpolated cotangent value
Definition at line 285 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), ace::math::lookup::_tables::cotTable, and ace::math::truncToInt().
cscDeg_tableInterp()
constexpr float ace::math::lookup::cscDeg_tableInterp (const float degrees) constexpr noexcept
Approximates the interpolated cosecant value from the cosecant lookup table.
Note
Correct to the cosecant value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cosecant from
Returns
Float of interpolated cosecant value
Definition at line 306 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), ace::math::lookup::_tables::cscTable, and ace::math::truncToInt().
secDeg_tableInterp()
constexpr float ace::math::lookup::secDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated secant value from the secant lookup table.
Note
Correct to the secant value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a secant from
Returns
Float of interpolated secant value
Definition at line 327 of file AEMathTrigLookup.hpp.
References _getTrigTableIndex(), ace::math::lookup::_tables::secTable, and ace::math::truncToInt().