ArtyK's Console Engine: AELogger Class Reference
AELogger Class Reference
The ArtyK's Engine's Logger module – it manages the writing to the log files.
#include <AELogger.hpp>
Public Member Functions
AELogger (const std::string fname, const bool clearLog=false, const ullint queuesize=AELOG_DEFAULT_QUEUE_SIZE)
Class constructor – it opens the file with the given name and starts logging to it.
AELogger (const std::string logpath, const std::string fname, const bool clearLog=false, const ullint queuesize=AELOG_DEFAULT_QUEUE_SIZE)
Class constructor – it opens the file with the given path and name and start logging to it.
AELogger (void)
Default class constructor – doesn't open the file, but setups the instance for one.
~AELogger (void)
Class destructor.
AELogger (const AELogger &)=delete
Deleted (for now) copy-constructor.
AELogger & operator= (const AELogger &)=delete
Deleted (for now) copy-assignment.
cint startWriter (void)
Starts the log-writing thread.
cint stopWriter (void)
Stops the log-writing thread (after flushing the log queue).
cint openLog (const std::string fpath, const std::string fname, const bool clearLog=false)
Open the file to start logging.
cint openLog (const std::string fname, const bool clearLog=false)
Open the file to start logging.
cint openLog (const std::string_view fpath, const std::string_view fname, const bool clearLog=false)
Open the file to start logging.
cint closeLog (void)
Close the file, if it was opened.
cint writeToLog (const std::string_view logmessg, const cint logtype=AELOG_TYPE_INFO, const std::string_view logmodule=AELOG_DEFAULT_MODULE_NAME, const std::time_t logTime=0)
Request a log entry to be written to the opened log file.
cint writeToLog (const AELogEntry &entry, const bool useCurrentTime=true)
Request a log entry to be written to the opened log file, using data from a log entry type.
cint writeToLogDebug (const std::string_view logmessg, const std::string_view logmodule=AELOG_DEFAULT_MODULE_NAME)
Request a debug log entry to be written to the opened log file.
cint writeStatus (void)
Writes the current status of the file logger instance (file name, and entries written).
std::string getLogName (void) const noexcept
Get the name of the log file.
std::string getLogPath (void) const
Get the path of the log file.
std::string getLogAbsolutePath (void) const
Get the full/absolute path of the log file.
ullint getEntryCount (void) const noexcept
Get the amount of log entries done to an opened log file.
bool isOpen (void) const noexcept
Checks if the current log file is open.
bool isClosed (void) const noexcept
Checks if a log file isn't open by this logger.
bool isWriting (void) const noexcept
Checks if the log-writing thread is running.
Static Public Member Functions
static std::string genLogName (const std::string_view logpref, const std::string_view logext=".log")
Creates a full name of the log file to open to be fed to the logger, in a format [prefix]_[current date][.extension] in a given directory.
static ullint getModuleAmount (void) noexcept
Returns the amount of instances of the module currently existing.
static constexpr std::string_view getModuleName (void) noexcept
Returns the name of the registered module.
Static Protected Attributes
static std::atomic< std::size_t > m_ullModulesAlive
Amount of alive module instances.
Private Member Functions
AELogEntry * ptrFromIndex (ullint num) noexcept
Checks for the given index number and returns the pointer in the queue of log entries.
void writeToLogDirectly (const std::string_view logmessg, const cint logtype=AELOG_TYPE_INFO, const std::string_view logmodule=AELOG_DEFAULT_MODULE_NAME) noexcept
Writes to log directly, without thinking of the queue.
void logWriterThread (void)
The function of the log writing thread to...read the entries, format them, write them, and clear them.
REGISTER_MODULE (AELogger)
Private Attributes
AEFileWriter m_fwLogger
The file writer to actually write text to opened log file.
std::mutex m_mtxAllocLock
The mutex to lock when allocating new queue chunks.
std::vector< std::pair< ullint, AELogEntry * > > m_vAllocTable
The vector to all the allocated queue pieces and total amounts allocated.
std::thread m_trdWriter
The thread object for the file writing thread to...write a log file separately.
std::atomic< ullint > m_ullFilledCount
The amount of nodes filled (should we allocate more?)
std::atomic< ullint > m_ullNodeNumber
The current node number the writeToLog is working with.
ullint m_ullQueueSize
The amount of entry spaces/size of the queue.
AELogEntry * m_lepQueue
The pointer to the first item in the queue.
AELogEntry * m_lepLastNode
The pointer to the last item in the queue.
std::atomic< bool > m_bRunTrd
The flag to run the log-writing thread.
std::atomic< bool > m_bQueueFilled
The flag to show that the queue is populated.
Detailed Description
The ArtyK's Engine's Logger module – it manages the writing to the log files.
A wrapper around AEFW functionality for writing, and AELogEntry for mass-formatting of entries to text
The log is written by requesting and filling the entry in the queue. The AELogger instance launches the separate thread that looks at the entries in the queue, retrieves and formats the data in them, and writes it to the file. Afterwards that entry in the queue is cleared.
Hungarian notation is lg. (m_lgMyLogger)
Todo
Implement copy constructors and copy assignment
Add the ability to open the same log file/redirect the instance requests to the one that has it open first.
Bug
The queue can expand if it's too little. But....I don't know how to shrink it. (working on it)
Definition at line 64 of file AELogger.hpp.
Constructor & Destructor Documentation
AELogger() [1/4]
AELogger::AELogger (const std::string fname, const bool clearLog = false, const ullint queuesize = AELOG_DEFAULT_QUEUE_SIZE) inline explicit
Class constructor – it opens the file with the given name and starts logging to it.
Note
Puts the file into the default log path location (AELOG_DEFAULT_LOG_PATH)
Parameters
fname Name of the log file
clearLog Flag to clear the log file if it exists instead of appending it
queuesize The size of the queue to create when creating AELogger instance
Definition at line 76 of file AELogger.hpp.
AELogger() [2/4]
AELogger::AELogger (const std::string logpath, const std::string fname, const bool clearLog = false, const ullint queuesize = AELOG_DEFAULT_QUEUE_SIZE) explicit
Class constructor – it opens the file with the given path and name and start logging to it.
Parameters
logpath The path of the log file to open it in
fname Name of the log file
clearLog Flag to clear the log file if it exists instead of appending it
queuesize The size of the queue to create when creating AELogger instance
Definition at line 13 of file AELogger.cpp.
References AELOG_DEFAULT_ALLOC_VECTOR_RESERVE, AELOG_TYPE_OK, __AEModuleBase< AELogger >::getModuleName(), AEFileWriter::isOpen(), m_fwLogger, m_lepQueue, m_vAllocTable, startWriter(), and writeToLog().
AELogger() [3/4]
AELogger::AELogger (void) inline explicit
Default class constructor – doesn't open the file, but setups the instance for one.
Definition at line 91 of file AELogger.hpp.
References AELOG_DEFAULT_ALLOC_VECTOR_RESERVE, m_lepQueue, m_ullQueueSize, and m_vAllocTable.
~AELogger()
AELogger::~AELogger (void)
Class destructor.
Definition at line 33 of file AELogger.cpp.
References AELOG_TYPE_INFO, closeLog(), __AEModuleBase< AELogger >::getModuleName(), m_vAllocTable, and writeToLog().
AELogger() [4/4]
AELogger::AELogger (const AELogger &) delete
Deleted (for now) copy-constructor.
Member Function Documentation
operator=()
AELogger & AELogger::operator= (const AELogger &) delete
Deleted (for now) copy-assignment.
startWriter()
cint AELogger::startWriter (void)
Starts the log-writing thread.
Returns
AELOG_ERR_NOERROR on success; otherwise AELOG_ERR_THREAD_ALREADY_RUNNING if thread already was running, AELOG_ERR_UNABLE_START_THREAD if error happened (+ std::runtime_error() exception)
Definition at line 44 of file AELogger.cpp.
References AELOG_ERR_NOERROR, AELOG_ERR_THREAD_ALREADY_RUNNING, AELOG_ERR_UNABLE_START_THREAD, AELOG_TYPE_FATAL_ERROR, AELOG_TYPE_INFO, AELOG_TYPE_WARN, closeLog(), __AEModuleBase< AELogger >::getModuleName(), logWriterThread(), m_bRunTrd, m_trdWriter, and writeToLog().
stopWriter()
cint AELogger::stopWriter (void)
Stops the log-writing thread (after flushing the log queue).
Returns
AELOG_ERR_NOERROR on success; otherwise AELOG_ERR_THREAD_ALREADY_STOPPED if thread already was stopped
Definition at line 63 of file AELogger.cpp.
References AELOG_ERR_NOERROR, AELOG_ERR_THREAD_ALREADY_STOPPED, AELOG_TYPE_ERROR, AELOG_TYPE_INFO, AELOG_TYPE_OK, __AEModuleBase< AELogger >::getModuleName(), m_bRunTrd, m_trdWriter, writeToLog(), and writeToLogDirectly().
openLog() [1/3]
cint AELogger::openLog (const std::string fpath, const std::string fname, const bool clearLog = false) inline
Open the file to start logging.
Parameters
fpath Path to put the log file in
fname Name of the log file
clearLog Flag to clear the log file if it exists instead of appending it
Returns
AELOG_ERR_NOERROR on success; otherwise return values of AEFileWriter::openFile() or AELogger::startWriter()
Definition at line 136 of file AELogger.hpp.
References AEFW_ERR_NOERROR, AEFW_FLAG_APPEND, AELOG_TYPE_SUCCESS, __AEModuleBase< AELogger >::getModuleName(), m_fwLogger, AEFileWriter::openFile(), startWriter(), and writeToLog().
openLog() [2/3]
cint AELogger::openLog (const std::string fname, const bool clearLog = false) inline
Open the file to start logging.
Note
Puts the file into the default log path location (AELOG_DEFAULT_LOG_PATH)
Parameters
fname Name of the log file
clearLog Flag to clear the log file if it exists instead of appending it
Returns
AELOG_ERR_NOERROR on success; otherwise return values of AEFileWriter::openFile() or AELogger::startWriter()
Definition at line 152 of file AELogger.hpp.
References AELOG_DEFAULT_LOG_PATH, and openLog().
openLog() [3/3]
cint AELogger::openLog (const std::string_view fpath, const std::string_view fname, const bool clearLog = false) inline
Open the file to start logging.
Parameters
fpath Path of directory to put the log file in (include trailing '/' character)
fname Name of the log file
clearLog Flag to clear the log file if it exists instead of appending it
Returns
AELOG_ERR_NOERROR on success; otherwise return values of AEFileWriter::openFile() or AELogger::startWriter()
Definition at line 163 of file AELogger.hpp.
References openLog().
closeLog()
cint AELogger::closeLog (void) inline
Close the file, if it was opened.
That's it.
Returns
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open,
Definition at line 171 of file AELogger.hpp.
References AEFW_ERR_FILE_NOT_OPEN, AELOG_ERR_NOERROR, AELOG_TYPE_INFO, AELOG_TYPE_SUCCESS, AEFileWriter::closeFile(), AEFileWriter::getFullFileName(), isClosed(), m_fwLogger, stopWriter(), writeToLog(), and writeToLogDirectly().
writeToLog() [1/2]
cint AELogger::writeToLog (const std::string_view logmessg, const cint logtype = AELOG_TYPE_INFO, const std::string_view logmodule = AELOG_DEFAULT_MODULE_NAME, const std::time_t logTime = 0)
Request a log entry to be written to the opened log file.
Note
See AELOG_TYPE_* flags
The module name should contain only alphanumeric characters or underscores (no spaces), otherwise it fails
Parameters
logmessg The message of the requested log entry
logtype The type of the log entry
logmodule The name of the module that invoked this request
logTime The custom time of the log entry to insert, if you really need that!
Returns
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
Todo
Implement decrease in log queue size...somehow
Definition at line 78 of file AELogger.cpp.
References AEFW_ERR_FILE_NOT_OPEN, AELE_MESSAGE_SIZE, AELE_MODULENAME_SIZE, AELE_STATUS_INVALID, AELE_STATUS_READY, AELE_STATUS_SETTING, AELOG_ERR_INVALID_ENTRY_DATA, AELOG_ERR_NOERROR, AELOG_TYPE_DEBUG, AELOG_TYPE_FATAL_ERROR, __AEModuleBase< AELogger >::getModuleName(), ace::utils::isAlNumUs(), isClosed(), ace::utils::isInRange(), AELogEntry::m_cLogType, AELogEntry::m_cStatus, m_lepLastNode, m_lepQueue, m_mtxAllocLock, AELogEntry::m_pNextNode, AELogEntry::m_sLogMessage, AELogEntry::m_sModuleName, AELogEntry::m_tmLogTime, m_ullFilledCount, m_ullNodeNumber, m_ullQueueSize, m_vAllocTable, AELogEntry::makeQueue(), ptrFromIndex(), and writeToLogDebug().
writeToLog() [2/2]
cint AELogger::writeToLog (const AELogEntry & entry, const bool useCurrentTime = true) inline
Request a log entry to be written to the opened log file, using data from a log entry type.
Parameters
entry The log entry to write to the file
useCurrentTime Flag to use current time for the log entry, or use timestamp in the provided entry
Returns
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open
Definition at line 203 of file AELogger.hpp.
References AELogEntry::m_cLogType, AELogEntry::m_sLogMessage, AELogEntry::m_sModuleName, AELogEntry::m_tmLogTime, and writeToLog().
writeToLogDebug()
cint AELogger::writeToLogDebug (const std::string_view logmessg, const std::string_view logmodule = AELOG_DEFAULT_MODULE_NAME) inline
Request a debug log entry to be written to the opened log file.
Note
See AELOG_TYPE_* flags
If ENGINE_DEBUG flag is not set, doesn't do anything
See also
AELogger::writeToLog()
Parameters
logmessg The message of the requested log entry
logmodule The name of the module that invoked this request
Returns
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
Definition at line 216 of file AELogger.hpp.
References AELOG_TYPE_DEBUG, and writeToLog().
writeStatus()
cint AELogger::writeStatus (void) inline
Writes the current status of the file logger instance (file name, and entries written).
Returns
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
Definition at line 227 of file AELogger.hpp.
References AELOG_TYPE_INFO, AEFileWriter::getFullFileName(), m_fwLogger, and writeToLog().
getLogName()
std::string AELogger::getLogName (void) const inline noexcept
Get the name of the log file.
Returns
std::string of the name of opened log file; otherwise values from AEFileWriter::getFullFileName()
Definition at line 237 of file AELogger.hpp.
References AEFileWriter::getFullFileName(), and m_fwLogger.
getLogPath()
std::string AELogger::getLogPath (void) const inline
Get the path of the log file.
Returns
std::string of the path of the opened log file; otherwise values from AEFileWriter::getRelativePath()
Definition at line 245 of file AELogger.hpp.
References AEFileWriter::getRelativePath(), and m_fwLogger.
getLogAbsolutePath()
std::string AELogger::getLogAbsolutePath (void) const inline
Get the full/absolute path of the log file.
Returns
std::string of the absolute path of the opened log file; otherwise values from AEFileWriter::getFullPath()
Definition at line 253 of file AELogger.hpp.
References AEFileWriter::getFullPath(), and m_fwLogger.
getEntryCount()
ullint AELogger::getEntryCount (void) const inline noexcept
Get the amount of log entries done to an opened log file.
Returns
ullint of the amount of times logger written to a file
Definition at line 261 of file AELogger.hpp.
References AEFileWriter::getTotalWrites(), and m_fwLogger.
isOpen()
bool AELogger::isOpen (void) const inline noexcept
Checks if the current log file is open.
Returns
True if the file is open for writing, false otherwise
Definition at line 269 of file AELogger.hpp.
References AEFileWriter::isOpen(), and m_fwLogger.
isClosed()
bool AELogger::isClosed (void) const inline noexcept
Checks if a log file isn't open by this logger.
Returns
True if log file is closed/not open, false if otherwise
Definition at line 277 of file AELogger.hpp.
References AEFileWriter::isClosed(), and m_fwLogger.
isWriting()
bool AELogger::isWriting (void) const inline noexcept
Checks if the log-writing thread is running.
Returns
True if it is working(was launched), false otherwise
Definition at line 285 of file AELogger.hpp.
References m_bRunTrd.
genLogName()
static std::string AELogger::genLogName (const std::string_view logpref, const std::string_view logext = ".log") inline static
Creates a full name of the log file to open to be fed to the logger, in a format [prefix]_[current date][.extension] in a given directory.
Parameters
logpref The prefix of log file
logext The extension of the log file. Include the period before the extension.
Returns
std::string of the file name to feed to the logger for opening
Definition at line 295 of file AELogger.hpp.
References ace::utils::getCurrentDate().
ptrFromIndex()
AELogEntry * AELogger::ptrFromIndex (ullint num) private noexcept
Checks for the given index number and returns the pointer in the queue of log entries.
Note
The index is wrapped around the max queue size.
Parameters
num The index number of the log entry
Returns
Pointer to the node of that index
Definition at line 203 of file AELogger.cpp.
writeToLogDirectly()
void AELogger::writeToLogDirectly (const std::string_view logmessg, const cint logtype = AELOG_TYPE_INFO, const std::string_view logmodule = AELOG_DEFAULT_MODULE_NAME) inline private noexcept
Writes to log directly, without thinking of the queue.
Warning
Use it with caution, when you sure that it won't compromise the log integrity (you know, race conditions with fwrite() in the AELogger::logWriterThread())
Parameters
logmessg Message of the log
logtype the type/severity of the log
logmodule the module name that requested the log
Definition at line 319 of file AELogger.hpp.
References AELE_FORMAT_MAX_SIZE, AELE_MESSAGE_SIZE, AELE_MODULENAME_SIZE, AEFileWriter::flushFile(), AELogEntry::formatEntry(), m_fwLogger, and AEFileWriter::writeData_ptr().
logWriterThread()
void AELogger::logWriterThread (void) private
The function of the log writing thread to...read the entries, format them, write them, and clear them.
Definition at line 143 of file AELogger.cpp.
References AELE_FORMAT_MAX_SIZE, AELE_STATUS_READING, AELE_STATUS_READY, AELOG_TYPE_OK, AELOG_TYPE_SUCCESS, AELogEntry::clearEntry(), AEFileWriter::flushFile(), AELogEntry::formatEntry(), __AEModuleBase< AELogger >::getModuleName(), m_bRunTrd, AELogEntry::m_cStatus, m_fwLogger, m_lepQueue, AELogEntry::m_pNextNode, m_ullFilledCount, ace::utils::sleepUS(), AEFileWriter::writeData_ptr(), writeToLog(), and writeToLogDirectly().
REGISTER_MODULE()
AELogger::REGISTER_MODULE (AELogger) private
getModuleAmount()
static ullint __AEModuleBase< AELogger >::getModuleAmount (void) inline static noexcept inherited
Returns the amount of instances of the module currently existing.
Returns
Unsigned long long of the module amount
Definition at line 91 of file AEModuleBase.hpp.
getModuleName()
static constexpr std::string_view __AEModuleBase< AELogger >::getModuleName (void) static constexpr noexcept inherited
Returns the name of the registered module.
Returns
Member Data Documentation
m_fwLogger
AEFileWriter AELogger::m_fwLogger private
The file writer to actually write text to opened log file.
Definition at line 346 of file AELogger.hpp.
m_mtxAllocLock
std::mutex AELogger::m_mtxAllocLock private
The mutex to lock when allocating new queue chunks.
Definition at line 348 of file AELogger.hpp.
m_vAllocTable
std::vector<std::pair<ullint, AELogEntry*> > AELogger::m_vAllocTable private
The vector to all the allocated queue pieces and total amounts allocated.
Definition at line 350 of file AELogger.hpp.
m_trdWriter
std::thread AELogger::m_trdWriter private
The thread object for the file writing thread to...write a log file separately.
Definition at line 352 of file AELogger.hpp.
m_ullFilledCount
std::atomic<ullint> AELogger::m_ullFilledCount private
The amount of nodes filled (should we allocate more?)
Definition at line 354 of file AELogger.hpp.
m_ullNodeNumber
std::atomic<ullint> AELogger::m_ullNodeNumber private
The current node number the writeToLog is working with.
Definition at line 356 of file AELogger.hpp.
m_ullQueueSize
ullint AELogger::m_ullQueueSize private
The amount of entry spaces/size of the queue.
Definition at line 358 of file AELogger.hpp.
m_lepQueue
AELogEntry* AELogger::m_lepQueue private
The pointer to the first item in the queue.
Definition at line 360 of file AELogger.hpp.
m_lepLastNode
AELogEntry* AELogger::m_lepLastNode private
The pointer to the last item in the queue.
Definition at line 362 of file AELogger.hpp.
m_bRunTrd
std::atomic<bool> AELogger::m_bRunTrd private
The flag to run the log-writing thread.
Definition at line 365 of file AELogger.hpp.
m_bQueueFilled
std::atomic<bool> AELogger::m_bQueueFilled private
The flag to show that the queue is populated.
Definition at line 367 of file AELogger.hpp.
m_ullModulesAlive
std::atomic<std::size_t> __AEModuleBase< AELogger >::m_ullModulesAlive inline static protected inherited
Amount of alive module instances.
Definition at line 109 of file AEModuleBase.hpp.
The documentation for this class was generated from the following files:
AELogger/include/AELogger.hpp
AELogger/src/AELogger.cpp