ArtyK's Console Engine: AEFileReader Class Reference
AEFileReader Class Reference
ArtyK's Engine File Reader; umm, it reads data from the given file.
#include <AEFileReader.hpp>
Public Member Functions
AEFileReader (const std::string_view fname)
Class constructor – constructs the instance and opens the file of given name.
AEFileReader (void) noexcept
Class constructor – constructs the instance with default values, and doesn't open the file.
AEFileReader (AEFileReader &&fr) noexcept
Class move constructor.
AEFileReader (const AEFileReader &)=delete
Deleted copy constructor.
AEFileReader & operator= (const AEFileReader &)=delete
Deleted copy assignment operator.
~AEFileReader (void)
Default Destructor.
cint openFile (const std::string_view fname)
Opens the file for reading.
cint closeFile (void) noexcept
Closes the currently opened file.
template<typename T >
cint readVariable (T &var) noexcept
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed variable.
cint readString (std::string &str, const std::size_t dcount)
Reads the given amount of bytes and interprets them as the string.
cint readString (std::vector< char > &str, const std::size_t dcount)
Reads the given amount of bytes and interprets them as the string.
cint readString (char *str, const std::size_t dcount) noexcept
Reads the given amount of bytes and interprets them as the string.
cint readStringNL (std::string &str, const int dcount)
Reads the characters to a std::string untill a newline (included), or untill the maximum character amount – whichever comes first.
cint readStringNL (std::vector< char > &str, const int dcount)
Reads the characters to a std::vector<char> untill a newline (included), or untill the maximum character amount – whichever comes first.
cint readStringNL (char *str, const int dcount) noexcept
Reads the characters to a c-string untill a newline (included), or untill the maximum character amount – whichever comes first.
cint readStringNULL (std::string &str, const llint dcount)
Reads the characters to a std::string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
cint readStringNULL (std::vector< char > &str, const llint dcount)
Reads the characters to a std::string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
cint readStringNULL (char *str, const llint dcount) noexcept
Reads the characters to a c-string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
template<typename T >
requires (std::is_integral<T>::value == true)
cint readInt (T &num) noexcept
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed integer.
template<typename T >
requires (std::is_integral<T>::value == true)
cint readIntString (T &num) noexcept
Reads the string of numbers from the file and convert it to int.
template<typename T >
cint readFloat (T &num) noexcept(std::is_floating_point< T >::value==true)
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed float.
template<typename T >
requires (std::is_floating_point<T>::value == true)
cint readFloatString (T &num) noexcept
Reads the string of numbers from the file and convert it to float.
cint readBool (bool &num) noexcept
Reads the byte from the file and dumps/reinterprets it as the value in the passed bool (null is false, anything else is true).
cint readBoolString (bool &num) noexcept
Reads the string in the file, looking for "true" or "false" (case insensitive).
cint readChar (signed char &num) noexcept
Reads the character from the file and writes you to a given char.
cint readByte (unsigned char &num) noexcept
Reads the byte from the file and writes you to a given unsigned.
cint readBytes (std::vector< unsigned char > &cdata, const std::size_t dcount)
Reads the bytes from the file and dumps them into the std::vector<unsigned char>.
cint readBytes (void *cdata, const std::size_t dcount) noexcept
Reads the bytes from the file and dumps them into the given pointer.
cint readData_ptr (void *cdata, const std::size_t dcount, const std::size_t dsize=sizeof(char)) noexcept
Reads an array of dcount elements, each one with a size of dsize bytes, to memory block pointed by cdata.
bool isOpen (void) const noexcept
Checks if a file is open by this file-reader.
bool isClosed (void) const noexcept
Checks if a file isn't open by this file-reader.
llint getFileSize (void) const noexcept
Returns size of the file in bytes.
std::string getFullFileName (void) const noexcept
Returns the full name of currently open file, including the relative path, if such was provided.
std::string getRelativePath (void) const
Returns the relative path of the opened file.
std::string getFileName (void) const
Returns the name of the opened file, devoid of the path.
std::string getFullPath (void) const
Returns the full, absolute path of the opened file.
std::FILE * getFilePtr (void) const noexcept
Returns the file pointer of this file-reader.
llint getCursorPos (void) const noexcept
Returns current read cursor position.
int setCursorPos (const llint pos, const int origin=SEEK_CUR) const noexcept
Sets read cursor position to pos from origin.
ullint getTotalReads (void) const noexcept
Returns total reader requests made to file.
std::size_t getLastReadAmount (void) const noexcept
Gets the last read amount of bytes from the opened file.
bool isEOF (void) const noexcept
Checks if the file (cursor) has reached it's (file's) end (feof)
bool isError (void) const noexcept
Checks if error was encountered while reading the file data (ferror)
Static Public Member Functions
static ullint getModuleAmount (void) noexcept
Returns the amount of instances of the module currently existing.
static constexpr std::string_view getModuleName (void) noexcept
Returns the name of the registered module.
Static Protected Attributes
static std::atomic< std::size_t > m_ullModulesAlive
Amount of alive module instances.
Private Attributes
std::string m_sFilename
Full filename and relative path.
std::atomic< ullint > m_ullTotalReads
Counter for total read operations for file.
std::size_t m_szLastReadAmount
The amount of read bytes during last operation.
std::FILE * m_fpFilestr
Object for file reading.
Detailed Description
ArtyK's Engine File Reader; umm, it reads data from the given file.
It is a wrapper around the C's FILE api, for speed and convenience. It can read strings (untill: max string size, newline, NULL character), bools, ints, and floats
Just create it, read stuff, and dump the terabytes of data from the file to your memory and what not. Hungarian notation is fr. (m_frMyFileReader) Flags start with AEFR_
Warning
This is not thread-safe!
Todo
add generic read function
Definition at line 87 of file AEFileReader.hpp.
Constructor & Destructor Documentation
AEFileReader() [1/4]
AEFileReader::AEFileReader (const std::string_view fname) explicit
Class constructor – constructs the instance and opens the file of given name.
See also
AEFileReader::openFile()
Parameters
fname The file name to opens
Definition at line 14 of file AEFileReader.cpp.
References openFile().
AEFileReader() [2/4]
AEFileReader::AEFileReader (void) inline noexcept
Class constructor – constructs the instance with default values, and doesn't open the file.
Definition at line 102 of file AEFileReader.hpp.
AEFileReader() [3/4]
AEFileReader::AEFileReader (AEFileReader && fr) noexcept
Class move constructor.
Definition at line 20 of file AEFileReader.cpp.
AEFileReader() [4/4]
AEFileReader::AEFileReader (const AEFileReader &) delete
Deleted copy constructor.
There is no need to copy AEFR, since access to file is in instance's FILE pointer. If in original instance, the file gets closed, the pointer is invalidated. Which can lead to...bad consequences using it again in the copied instance.
~AEFileReader()
AEFileReader::~AEFileReader (void) inline
Default Destructor.
Just flushes and closes the file.
Definition at line 129 of file AEFileReader.hpp.
References closeFile().
Member Function Documentation
operator=()
AEFileReader & AEFileReader::operator= (const AEFileReader &) delete
Deleted copy assignment operator.
There is no need to copy AEFR, since access to file is in instance's FILE pointer. If in original instance, the file gets closed, the pointer is invalidated. Which can lead to...bad consequences using it again in the copied instance.
openFile()
cint AEFileReader::openFile (const std::string_view fname)
Opens the file for reading.
Parameters
fname The name of the file to open
Returns
AEFR_ERR_NOERROR if file was opened successfully; otherwise AEFR_ERR_OPEN_* flags (like AEFR_ERR_OPEN_FILE_NAME_EMPTY)
Definition at line 32 of file AEFileReader.cpp.
References AEFR_ERR_NOERROR, AEFR_ERR_OPEN_FILE_ALREADY_OPENED, AEFR_ERR_OPEN_FILE_DOESNT_EXIST, AEFR_ERR_OPEN_FILE_NAME_EMPTY, ace::utils::fopenCC(), isClosed(), isOpen(), m_fpFilestr, m_sFilename, and m_szLastReadAmount.
closeFile()
cint AEFileReader::closeFile (void) inline noexcept
Closes the currently opened file.
Returns
AEFR_ERR_NOERROR if file was closed successfully; AEFR_ERR_FILE_NOT_OPEN if file isn't open
Definition at line 146 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_CLOSED_FILE, AEFR_ERR_NOERROR, m_fpFilestr, m_sFilename, and m_szLastReadAmount.
readVariable()
template<typename T > cint AEFileReader::readVariable (T & var) inline noexcept
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed variable.
Note
If EOF/Error was encountered when reading, the rest of bytes that weren't filled are zeroed
Template Parameters
T The type of the variable passed
Parameters
var The variable to fill with bytes
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 166 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AENULL, and readData_ptr().
readString() [1/3]
cint AEFileReader::readString (std::string & str, const std::size_t dcount) inline
Reads the given amount of bytes and interprets them as the string.
Note
Modifies the length of the std::string to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF), resizes it to the amount read.
If the file is closed, it doesn't modify the string
Parameters
str The refernce to the std::string object to read the bytes of string to
dcount The amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 182 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readString().
readString() [2/3]
cint AEFileReader::readString (std::vector< char > & str, const std::size_t dcount) inline
Reads the given amount of bytes and interprets them as the string.
Note
Modifies the length of the std::vector<char> to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF), resizes it to the amount read (+1 for the null termination).
If the file is closed, it doesn't modify the std::vector<char>
Parameters
str The refernce to the std::vector<char> object to read the bytes of string to
dcount The amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 201 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readString().
readString() [3/3]
cint AEFileReader::readString (char * str, const std::size_t dcount) noexcept
Reads the given amount of bytes and interprets them as the string.
Note
The passed string must be at least dcount+1 characters long (+1 is for the trailing null termination)
If the resulting data size is less than dcount (like from EOF), fills the rest of unfilled characters with NULL
If the file is closed, it doesn't modify the data
Parameters
str The pointer to the c-string to read the bytes of string to
dcount The amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 58 of file AEFileReader.cpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_ZERO_SIZE, and AENULL.
readStringNL() [1/3]
cint AEFileReader::readStringNL (std::string & str, const int dcount) inline
Reads the characters to a std::string untill a newline (included), or untill the maximum character amount – whichever comes first.
Note
Modifies the length of the std::string to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF or met newline), resizes it to the amount read.
If the file is closed, it doesn't modify the string
Parameters
str The refernce to the std::string object to read the bytes of string to
dcount The maximum amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 234 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readStringNL().
readStringNL() [2/3]
cint AEFileReader::readStringNL (std::vector< char > & str, const int dcount) inline
Reads the characters to a std::vector<char> untill a newline (included), or untill the maximum character amount – whichever comes first.
Note
Modifies the length of the std::vector<char> to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF or met newline), resizes it to the amount read (+1 for the null termination).
If the file is closed, it doesn't modify the std::vector<char>
Parameters
str The refernce to the std::vector<char> object to read the bytes of string to
dcount The maximum amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 251 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readStringNL().
readStringNL() [3/3]
cint AEFileReader::readStringNL (char * str, const int dcount) noexcept
Reads the characters to a c-string untill a newline (included), or untill the maximum character amount – whichever comes first.
Note
The passed string must be at least dcount+1 characters long (+1 is for the trailing null termination)
If the resulting data size is less than dcount (like from EOF or met newline), fills the rest of unfilled characters with NULL
If the file is closed, it doesn't modify the data
Parameters
str The pointer to the c-string to read the bytes of string to
dcount The maximum amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 70 of file AEFileReader.cpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_EOF, AEFR_ERR_READ_ERROR, AEFR_ERR_READ_SUCCESS, AEFR_ERR_READ_ZERO_SIZE, and AENULL.
readStringNULL() [1/3]
cint AEFileReader::readStringNULL (std::string & str, const llint dcount) inline
Reads the characters to a std::string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
Note
Modifies the length of the std::string to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF or met null), resizes it to the amount read.
If the file is closed, it doesn't modify the string
Parameters
str The refernce to the std::string object to read the bytes of string to
dcount The maximum amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 281 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readStringNULL().
readStringNULL() [2/3]
cint AEFileReader::readStringNULL (std::vector< char > & str, const llint dcount) inline
Reads the characters to a std::string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
Note
Modifies the length of the std::vector<char> to the dcount+1 size (to accomodate for the trailing null-termiantion character).
If the resulting data size is less than dcount (like from EOF or met null), resizes it to the amount read (+1 for the null termination).
If the file is closed, it doesn't modify the std::vector<char>
Parameters
str The refernce to the std::vector<char> object to read the bytes of string to
dcount The maximum amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 298 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, and readStringNULL().
readStringNULL() [3/3]
cint AEFileReader::readStringNULL (char * str, const llint dcount) noexcept
Reads the characters to a c-string untill a NULL character(I guess, you can say "included"?), or untill the maximum character amount – whichever comes first.
Note
The passed string must be at least dcount+1 characters long (+1 is for the trailing null termination)
If the resulting data size is less than dcount (like from EOF or met null), fills the rest of unfilled characters with NULL
If the file is closed, it doesn't modify the data
Parameters
str The pointer to the c-string to read the bytes of string to
dcount The amount of characters to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 94 of file AEFileReader.cpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_ZERO_SIZE, and AENULL.
readInt()
template<typename T > requires (std::is_integral<T>::value == true) cint AEFileReader::readInt (T & num) inline noexcept
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed integer.
Note
If EOF/Error was encountered when reading, the rest of bytes that weren't filled are zeroed
If the file is closed, it doesn't modify the data
AEFileReader::readVariable()
Template Parameters
T The type of the int passed
Parameters
num The int to fill with bytes
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 329 of file AEFileReader.hpp.
References readVariable().
readIntString()
template<typename T > requires (std::is_integral<T>::value == true) cint AEFileReader::readIntString (T & num) inline noexcept
Reads the string of numbers from the file and convert it to int.
Note
If the first character isn't numeric (or minus), the read fails and integer is set to 0
If the file is closed, it doesn't modify the data
Template Parameters
T The type of the int passed
Parameters
num The int to read the value to
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 643 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_EOF, AEFR_ERR_READ_SUCCESS, AENULL, and IS_SAME_NOCV.
readFloat()
template<typename T > cint AEFileReader::readFloat (T & num) inline noexcept
Reads the bytes (size of T) from the file and dumps/reinterprets them as the value in the passed float.
Note
If EOF/Error was encountered when reading, the rest of bytes that weren't filled are zeroed
If the file is closed, it doesn't modify the data
AEFileReader::readVariable()
Template Parameters
T The type of the float passed
Parameters
num The float to fill with bytes
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 357 of file AEFileReader.hpp.
References readVariable().
readFloatString()
template<typename T > requires (std::is_floating_point<T>::value == true) cint AEFileReader::readFloatString (T & num) inline noexcept
Reads the string of numbers from the file and convert it to float.
Note
If the first character isn't numeric (or belonging to float formatting, the read fails and float is (mem)set to 0
If the file is closed, it doesn't modify the data
Template Parameters
T The type of the float passed
Parameters
num The float to read the value to
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 691 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_EOF, AEFR_ERR_READ_SUCCESS, AENULL, and IS_SAME_NOCV.
readBool()
cint AEFileReader::readBool (bool & num) inline noexcept
Reads the byte from the file and dumps/reinterprets it as the value in the passed bool (null is false, anything else is true).
Note
If EOF/Error was encountered when reading, and no bytes were read - the bool is set to false
If the file is closed, it doesn't modify the data
AEFileReader::readVariable()
Parameters
num The bool to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 383 of file AEFileReader.hpp.
References readVariable().
readBoolString()
cint AEFileReader::readBoolString (bool & num) noexcept
Reads the string in the file, looking for "true" or "false" (case insensitive).
Note
If the read characters don't evaluate to "true" or "false", the read fails and bool is set to false
If the file is closed, it doesn't modify the data
Parameters
num The bool to read the value to
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 118 of file AEFileReader.cpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, and AEFR_ERR_READ_ERROR.
readChar()
cint AEFileReader::readChar (signed char & num) inline noexcept
Reads the character from the file and writes you to a given char.
Note
If EOF/Error was encountered when reading, and no bytes were read - the char is set to 0
If the file is closed, it doesn't modify the data
AEFileReader::readVariable()
Same as AEFileReader::readByte()
Parameters
num The char to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 405 of file AEFileReader.hpp.
References readVariable().
readByte()
cint AEFileReader::readByte (unsigned char & num) inline noexcept
Reads the byte from the file and writes you to a given unsigned.
Note
If EOF/Error was encountered when reading, and no bytes were read - the char is set to 0
If the file is closed, it doesn't modify the data
AEFileReader::readVariable()
Parameters
num The char to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 417 of file AEFileReader.hpp.
References readVariable().
readBytes() [1/2]
cint AEFileReader::readBytes (std::vector< unsigned char > & cdata, const std::size_t dcount) inline
Reads the bytes from the file and dumps them into the std::vector<unsigned char>.
Note
Modifies the length of the std::vector<unsigned char> to the dcount size
If the resulting data size is less than dcount (like from EOF), resizes it to the amount read
If the file is closed, it doesn't modify the std::vector<unsigned char>
Parameters
cdata The reference to the std::vector<char> object to fill with bytes
dcount The amount of bytes to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 433 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, m_szLastReadAmount, readData_ptr(), and readVariable().
readBytes() [2/2]
cint AEFileReader::readBytes (void * cdata, const std::size_t dcount) inline noexcept
Reads the bytes from the file and dumps them into the given pointer.
Note
The data pointed by the cdata must be of at least dcount size!
If the resulting data size is less than dcount (like from EOF), fills the rest of unfilled characters with NULL
If the file is closed, it doesn't modify the data of the pointer
Just a shortcut for the AEFileReader::readData_ptr()
Parameters
cdata The pointer to the data to fill with bytes
dcount The amount of bytes to read
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 451 of file AEFileReader.hpp.
References AENULL, readData_ptr(), and readVariable().
readData_ptr()
cint AEFileReader::readData_ptr (void * cdata, const std::size_t dcount, const std::size_t dsize = sizeof(char)) noexcept
Reads an array of dcount elements, each one with a size of dsize bytes, to memory block pointed by cdata.
Also sets the last read amount variable to the read amount of elements. If it doesn't equal to dcount, then EOF or error was encountered during reading.
Note
The memory block pointed by the cdata must be of at least dcount size!
If the file is closed, it doesn't modify the data of the pointer
Parameters
cdata The memory block to read the bytes to
dcount The amount of elements to read from the file
dsize The size of each element
Returns
AEFR_ERR_READ_SUCCESS on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file isn't open, or other AEFR_ERR_READ_* flags (like AEFR_ERR_READ_EOF)
Definition at line 141 of file AEFileReader.cpp.
References _AEFR_EXIT_ON_READ_CLOSED_FILE, AEFR_ERR_READ_EOF, AEFR_ERR_READ_ERROR, AEFR_ERR_READ_SUCCESS, and AEFR_ERR_READ_ZERO_SIZE.
isOpen()
bool AEFileReader::isOpen (void) const inline noexcept
Checks if a file is open by this file-reader.
Returns
True if file is open, false if otherwise
Definition at line 475 of file AEFileReader.hpp.
References m_fpFilestr.
isClosed()
bool AEFileReader::isClosed (void) const inline noexcept
Checks if a file isn't open by this file-reader.
Returns
True if file is closed/not open, false if otherwise
Definition at line 483 of file AEFileReader.hpp.
References isOpen().
getFileSize()
llint AEFileReader::getFileSize (void) const inline noexcept
Returns size of the file in bytes.
Returns
File size in bytes if file is open; otherwise AEFR_ERR_FILE_NOT_OPEN
Definition at line 491 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_CLOSED_FILE, m_fpFilestr, and readVariable().
getFullFileName()
std::string AEFileReader::getFullFileName (void) const inline noexcept
Returns the full name of currently open file, including the relative path, if such was provided.
Note
If no relative path was provided when opening the file, then output of AEFileReader::getFullFileName() is equivalent to AEFileReader::getFileName()
Returns
std::string of the opened file (including relative path if was given); empty string otherwise
Definition at line 506 of file AEFileReader.hpp.
References m_sFilename.
getRelativePath()
std::string AEFileReader::getRelativePath (void) const inline
Returns the relative path of the opened file.
If the file was opened in the same directory as the executable (no relative path provided), returns "./"
Returns
std::string of the relative file path of opened file; empty string otherwise
Definition at line 515 of file AEFileReader.hpp.
References isClosed(), m_sFilename, and readVariable().
getFileName()
std::string AEFileReader::getFileName (void) const inline
Returns the name of the opened file, devoid of the path.
Returns
std::string of the opened file name; emtpy string otherwise
Definition at line 532 of file AEFileReader.hpp.
References m_sFilename, and readVariable().
getFullPath()
std::string AEFileReader::getFullPath (void) const inline
Returns the full, absolute path of the opened file.
Returns
std::string of the absolute path of the opened file; empty string otherwise
Definition at line 546 of file AEFileReader.hpp.
References isClosed(), and m_sFilename.
getFilePtr()
std::FILE * AEFileReader::getFilePtr (void) const inline noexcept
Returns the file pointer of this file-reader.
Returns
Pointer to FILE used in the file reader
Definition at line 557 of file AEFileReader.hpp.
References m_fpFilestr.
getCursorPos()
llint AEFileReader::getCursorPos (void) const inline noexcept
Returns current read cursor position.
Returns
Current read cursor position, starting from 0, if file is open; otherwise AEFR_ERR_FILE_NOT_OPEN
Definition at line 567 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_CLOSED_FILE, m_fpFilestr, and readVariable().
setCursorPos()
int AEFileReader::setCursorPos (const llint pos, const int origin = SEEK_CUR) const inline noexcept
Sets read cursor position to pos from origin.
Note
If cursor is beyond end of file, next read will trigger EOF error and will not read any data (just fill the given data place with NULL)
If origin is not SEEK_SET, SEEK_CUR or SEEK_END returns AEFR_ERR_READ_EOF
Parameters
pos Position to be set to relative to origin (same as "offset" in fseek)
origin Relative origin for the operation. Google SEEK_SET, SEEK_CUR and SEEK_END for more details
Returns
0 on success; otherwise AEFR_ERR_FILE_NOT_OPEN if file's closed, AEFR_ERR_WRONG_CURSOR_ORIGIN on invalid origin, or things that fseek can return
Definition at line 580 of file AEFileReader.hpp.
References _AEFR_EXIT_ON_CLOSED_FILE, AEFR_ERR_READ_EOF, m_fpFilestr, and readVariable().
getTotalReads()
ullint AEFileReader::getTotalReads (void) const inline noexcept
Returns total reader requests made to file.
Returns
Amount of times the read operation has been called on this AEFileReader instance
Definition at line 594 of file AEFileReader.hpp.
References m_ullTotalReads.
getLastReadAmount()
std::size_t AEFileReader::getLastReadAmount (void) const inline noexcept
Gets the last read amount of bytes from the opened file.
Note
If last operation failed and no bytes were read (closed file, full EOF) – returns 0;
Returns
std::size_t of the amount of bytes read in the last reading operation
Definition at line 603 of file AEFileReader.hpp.
References m_szLastReadAmount.
isEOF()
bool AEFileReader::isEOF (void) const inline noexcept
Checks if the file (cursor) has reached it's (file's) end (feof)
Returns
True if end of file was reached, false otherwise
Definition at line 611 of file AEFileReader.hpp.
References m_fpFilestr.
isError()
bool AEFileReader::isError (void) const inline noexcept
Checks if error was encountered while reading the file data (ferror)
Returns
True if end of file was reached, false otherwise
Definition at line 619 of file AEFileReader.hpp.
References m_fpFilestr.
getModuleAmount()
static ullint __AEModuleBase< AEFileReader >::getModuleAmount (void) inline static noexcept inherited
Returns the amount of instances of the module currently existing.
Returns
Unsigned long long of the module amount
Definition at line 91 of file AEModuleBase.hpp.
getModuleName()
static constexpr std::string_view __AEModuleBase< AEFileReader >::getModuleName (void) static constexpr noexcept inherited
Returns the name of the registered module.
Returns
Member Data Documentation
m_sFilename
std::string AEFileReader::m_sFilename private
Full filename and relative path.
Definition at line 627 of file AEFileReader.hpp.
m_ullTotalReads
std::atomic<ullint> AEFileReader::m_ullTotalReads private
Counter for total read operations for file.
Definition at line 629 of file AEFileReader.hpp.
m_szLastReadAmount
std::size_t AEFileReader::m_szLastReadAmount private
The amount of read bytes during last operation.
Definition at line 631 of file AEFileReader.hpp.
m_fpFilestr
std::FILE* AEFileReader::m_fpFilestr private
Object for file reading.
Definition at line 633 of file AEFileReader.hpp.
m_ullModulesAlive
std::atomic<std::size_t> __AEModuleBase< AEFileReader >::m_ullModulesAlive inline static protected inherited
Amount of alive module instances.
Definition at line 109 of file AEModuleBase.hpp.
The documentation for this class was generated from the following files:
AEFileReader/include/AEFileReader.hpp
AEFileReader/src/AEFileReader.cpp