ArtyK's Console Engine: ace::math Namespace Reference
ace::math Namespace Reference
Mathematical functions and other things usefull in math.
Functions
template<typename T = long double>
constexpr T pi (void) noexcept
Engine's pi value.
template<typename T = long double>
constexpr T tau (void) noexcept
Engine's tau (pi*2) value.
template<typename T = long double>
constexpr T piDouble (void) noexcept
Engine's pi*2 (tau) value Just another name for ace::math::tau()
template<typename T = long double>
constexpr T piHalf (void) noexcept
Engine's pi/2 (half) value.
template<typename T = long double>
constexpr T piQuarter (void) noexcept
Engine's pi/4 (quarter) value.
template<typename T = long double>
constexpr T piSquared (void) noexcept
Engine's pi^2 (squared) value.
template<typename T = long double>
constexpr T piInv (void) noexcept
Engine's 1/pi (inverse) value.
template<typename T = long double>
constexpr T log2e (void) noexcept
Engine's log2(e) value.
template<typename T = long double>
constexpr T log10e (void) noexcept
Engine's log10(e) value.
template<typename T = long double>
constexpr T ln2 (void) noexcept
Engine's ln(2) value.
template<typename T = long double>
constexpr T ln10 (void) noexcept
Engine's ln(10) value.
template<typename T = long double>
constexpr T sqrtOf2 (void) noexcept
Engine's sqrt(2) value.
template<typename T = long double>
constexpr T sqrtOf3 (void) noexcept
Engine's sqrt(3) value.
template<typename T = long double>
constexpr T sqrtOf2Inv (void) noexcept
Engine's 1/sqrt(2) value.
template<typename T = long double>
constexpr T sqrtOf3Inv (void) noexcept
Engine's 1/sqrt(3) value.
template<typename T = long double>
constexpr T sqrtOfPi (void) noexcept
Engine's sqrt(pi) value.
template<typename T = long double>
constexpr T sqrtOfPiInv (void) noexcept
Engine's 1/sqrt(pi) value.
template<typename T = long double>
constexpr T e (void) noexcept
Engine's euler's number value.
template<typename T = long double>
constexpr T eGamma (void) noexcept
Engine's euler's gamma function (euler's constant) value.
template<typename T = long double>
constexpr T phi (void) noexcept
Engine's golden ratio (phi) value.
template<typename T >
constexpr T toRad (const T deg) noexcept
Convert given degrees to radians
template<typename T = long double>
constexpr bool isInf (const T num) noexcept
Checks if the float is "infinite" (inf)
template<typename T = long double>
constexpr bool isNan (const T num) noexcept
Checks if the float is "NaN"
template<typename T = long double>
constexpr bool isFinite (const T num) noexcept
Checks if the float is finite (not infinity or NaN)
template<typename T >
constexpr T toDeg (const T rad) noexcept
Convert given radians to degrees
template<typename T = long double>
T sinDeg (const T degrees) noexcept
Calculates the sine of degrees
template<typename T = long double>
T cosDeg (const T degrees) noexcept
Calculates the cosine of degrees
template<typename T = long double>
T tanDeg (const T degrees) noexcept
Calculates the tangent of degrees
template<typename T = long double>
T cotDeg (const T degrees) noexcept
Calculates the cotangent of degrees
template<typename T = long double>
T cscDeg (const T degrees) noexcept
Calculates the cosecant of degrees
template<typename T = long double>
T secDeg (const T degrees) noexcept
Calculates the secant of degrees
template<typename T >
constexpr T absval (const T num) noexcept
Calculates the absolute value of a given number.
template<typename T = long double>
requires (std::is_floating_point<T>::value == true)
constexpr bool fequals (const T num, const T num2, const T _epsilon) noexcept
Compares two floating point values for equality, within a given epsilon
template<typename T = long double>
requires (std::is_floating_point<T>::value == true)
constexpr bool fequals (const T num, const T num2) noexcept
Compares two floating point values for equality, within a default (scaled) epsilon.
template<typename T , typename Y = T>
constexpr bool equals (const T &num, const Y &num2) noexcept
Checks if given 2 numbers are equal, a generic function for all types.
template<typename T = long double>
constexpr T sqrt (const T num) noexcept
Newton's method sqrt implementation, compatible with constexpr evaluation.
template<typename T = long double>
constexpr T intPow (const T num, llint power) noexcept
Calculate the integer exponent of a given number.
template<typename T = long double>
constexpr T root (const T num, const uint rtNum) noexcept
Calculate the n'th root of a number.
template<typename T >
constexpr T max (const T &a, const T &b) noexcept
Returns the largest value between the given two values.
template<typename T >
constexpr T min (const T &a, const T &b) noexcept
Gets the smallest value between given two values.
template<typename T >
requires (std::is_integral<T>::value == true)
constexpr uint lengthOfInt (T num) noexcept
Calculate the length of the given integer number.
template<typename T >
requires (std::is_floating_point<T>::value == true)
constexpr uint lengthOfFloat (const T num) noexcept
Calculate the length of the given float number's non-fractional part.
template<typename T = long double>
constexpr T lerp (const T a, const T b, const T c) noexcept
Computes the linear inter/extrapolation with the given interval boundaries a and b, and the interval percentage c.
template<typename T = long double>
constexpr T hypot (const T a, const T b) noexcept
Calculates the hypotenuse length from given values a and b.
template<typename T = llint, typename Y = long double>
requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true)
constexpr T roundToInt (const Y num) noexcept
Rounds the given float of type Y to integer of type T.
template<typename T = llint, typename Y = long double>
requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true)
constexpr T floorToInt (const Y num) noexcept
Floor's the given float of type Y and converts to integer of type T.
template<typename T = llint, typename Y = long double>
requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true)
constexpr T ceilToInt (const Y num) noexcept
Ceil's the given float of type Y and converts to integer of type T.
template<typename T = llint, typename Y = long double>
requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true)
constexpr T truncToInt (const Y num) noexcept
Truncates the given float of type Y and converts to integer of type T.
constexpr std::size_t _getTrigTableIndex (const llint a) noexcept
Returns the index to the trig table from the given (int) degree number.
constexpr float sinDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of sine in the table.
constexpr float cosDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cosine in the table.
constexpr float tanDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of tangent in the table.
constexpr float cotDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cotangent in the table.
constexpr float cscDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of cosecant in the table.
constexpr float secDeg_table (const float degrees) noexcept
Rounds the degrees value, and looks up the value of secant in the table.
constexpr float sinDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated sine value from the sine lookup table.
constexpr float cosDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated cosine value from the cosine lookup table.
constexpr float tanDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated tangent value from the tangent lookup table.
constexpr float cotDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated cotangent value from the cotangent lookup table.
constexpr float cscDeg_tableInterp (const float degrees) noexcept
Approximates the interpolated cosecant value from the cosecant lookup table.
constexpr float secDeg_tableInterp (const float degrees) noexcept
Calculates the interpolated secant value from the secant lookup table.
Variables
constexpr float sinTable [360]
A lookup table for sine values (degrees)
constexpr float cosTable [360]
A lookup table for cosine values (degrees)
constexpr float tanTable [360]
A lookup table for tangent values (degrees)
constexpr float cotTable [360]
A lookup table for cotangent values (degrees)
constexpr float cscTable [360]
A lookup table for cosecant values (degrees)
constexpr float secTable [360]
A lookup table for secant values (degrees)
Detailed Description
Mathematical functions and other things usefull in math.
Almost all functions have a template parameter for the type of the operation.
That's made so you won't need to make the operation of a wider type, if you need it in the narrower type.
Example: calculate a cosecant using (and for) a float instead of a default long double.
Function Documentation
pi()
template<typename T = long double> constexpr T ace::math::pi (void) constexpr noexcept
Engine's pi value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 43 of file AEMath.hpp.
tau()
template<typename T = long double> constexpr T ace::math::tau (void) constexpr noexcept
Engine's tau (pi*2) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 55 of file AEMath.hpp.
piDouble()
template<typename T = long double> constexpr T ace::math::piDouble (void) constexpr noexcept
Engine's pi*2 (tau) value Just another name for ace::math::tau()
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 68 of file AEMath.hpp.
piHalf()
template<typename T = long double> constexpr T ace::math::piHalf (void) constexpr noexcept
Engine's pi/2 (half) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 80 of file AEMath.hpp.
piQuarter()
template<typename T = long double> constexpr T ace::math::piQuarter (void) constexpr noexcept
Engine's pi/4 (quarter) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 92 of file AEMath.hpp.
piSquared()
template<typename T = long double> constexpr T ace::math::piSquared (void) constexpr noexcept
Engine's pi^2 (squared) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 104 of file AEMath.hpp.
piInv()
template<typename T = long double> constexpr T ace::math::piInv (void) constexpr noexcept
Engine's 1/pi (inverse) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 116 of file AEMath.hpp.
log2e()
template<typename T = long double> constexpr T ace::math::log2e (void) constexpr noexcept
Engine's log2(e) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 128 of file AEMath.hpp.
log10e()
template<typename T = long double> constexpr T ace::math::log10e (void) constexpr noexcept
Engine's log10(e) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 140 of file AEMath.hpp.
ln2()
template<typename T = long double> constexpr T ace::math::ln2 (void) constexpr noexcept
Engine's ln(2) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 152 of file AEMath.hpp.
ln10()
template<typename T = long double> constexpr T ace::math::ln10 (void) constexpr noexcept
Engine's ln(10) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 164 of file AEMath.hpp.
sqrtOf2()
template<typename T = long double> constexpr T ace::math::sqrtOf2 (void) constexpr noexcept
Engine's sqrt(2) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 176 of file AEMath.hpp.
sqrtOf3()
template<typename T = long double> constexpr T ace::math::sqrtOf3 (void) constexpr noexcept
Engine's sqrt(3) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 188 of file AEMath.hpp.
sqrtOf2Inv()
template<typename T = long double> constexpr T ace::math::sqrtOf2Inv (void) constexpr noexcept
Engine's 1/sqrt(2) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 200 of file AEMath.hpp.
sqrtOf3Inv()
template<typename T = long double> constexpr T ace::math::sqrtOf3Inv (void) constexpr noexcept
Engine's 1/sqrt(3) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 212 of file AEMath.hpp.
sqrtOfPi()
template<typename T = long double> constexpr T ace::math::sqrtOfPi (void) constexpr noexcept
Engine's sqrt(pi) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 224 of file AEMath.hpp.
sqrtOfPiInv()
template<typename T = long double> constexpr T ace::math::sqrtOfPiInv (void) constexpr noexcept
Engine's 1/sqrt(pi) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 236 of file AEMath.hpp.
e()
template<typename T = long double> constexpr T ace::math::e (void) constexpr noexcept
Engine's euler's number value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 248 of file AEMath.hpp.
eGamma()
template<typename T = long double> constexpr T ace::math::eGamma (void) constexpr noexcept
Engine's euler's gamma function (euler's constant) value.
Note
Don't confuse with euler's number ace::math::e()
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 261 of file AEMath.hpp.
phi()
template<typename T = long double> constexpr T ace::math::phi (void) constexpr noexcept
Engine's golden ratio (phi) value.
Template Parameters
T Type to convert the constant to
Returns
The constant converted/rounded to a given type
Definition at line 273 of file AEMath.hpp.
toRad()
template<typename T > constexpr T ace::math::toRad (const T deg) constexpr noexcept
Convert given degrees to radians
Template Parameters
T The type of the degrees value and the resulting operation
Parameters
deg Value of degrees to convert
Returns
Radians from given degrees as type T
Definition at line 286 of file AEMath.hpp.
isInf()
template<typename T = long double> constexpr bool ace::math::isInf (const T num) constexpr noexcept
Checks if the float is "infinite" (inf)
Template Parameters
T The type of a floating point number
Parameters
num The number to check
Returns
True if the given float number is infinite
False otherwise
Definition at line 300 of file AEMath.hpp.
isNan()
template<typename T = long double> constexpr bool ace::math::isNan (const T num) constexpr noexcept
Checks if the float is "NaN"
Template Parameters
T The type of a floating point number
Parameters
num The number to check
Returns
True if the float number is NaN
False otherwise
Definition at line 315 of file AEMath.hpp.
isFinite()
template<typename T = long double> constexpr bool ace::math::isFinite (const T num) constexpr noexcept
Checks if the float is finite (not infinity or NaN)
Template Parameters
T The type of a floating point number
Parameters
num The number to check
Returns
True if the float number is finite, not infinite or NaN
False otherwise
Definition at line 330 of file AEMath.hpp.
toDeg()
template<typename T > constexpr T ace::math::toDeg (const T rad) constexpr noexcept
Convert given radians to degrees
Template Parameters
T The type of the radians value and the resulting operation
Parameters
rad Value of radians to convert
Returns
Degrees from given radians as type T
Definition at line 344 of file AEMath.hpp.
sinDeg()
template<typename T = long double> T ace::math::sinDeg (const T degrees) inline noexcept
Calculates the sine of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate sine from
Returns
The values of sine of given degrees, as type T
Definition at line 357 of file AEMath.hpp.
References toRad().
cosDeg()
template<typename T = long double> T ace::math::cosDeg (const T degrees) inline noexcept
Calculates the cosine of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate cosine from
Returns
The values of cosine of given degrees, as type T
Definition at line 370 of file AEMath.hpp.
References toRad().
tanDeg()
template<typename T = long double> T ace::math::tanDeg (const T degrees) inline noexcept
Calculates the tangent of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate tangent from
Returns
The values of tangent of given degrees, as type T
Definition at line 383 of file AEMath.hpp.
References toRad().
cotDeg()
template<typename T = long double> T ace::math::cotDeg (const T degrees) inline noexcept
Calculates the cotangent of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate cotangent from
Returns
The values of cotangent of given degrees, as type T
Definition at line 396 of file AEMath.hpp.
References tanDeg().
cscDeg()
template<typename T = long double> T ace::math::cscDeg (const T degrees) inline noexcept
Calculates the cosecant of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate cosecant from
Returns
The values of cosecant of given degrees, as type T
Definition at line 409 of file AEMath.hpp.
References sinDeg().
secDeg()
template<typename T = long double> T ace::math::secDeg (const T degrees) inline noexcept
Calculates the secant of degrees
Template Parameters
T The type to do the operation with
Parameters
degrees Degree number to calculate secant from
Returns
The values of secant of given degrees, as type T
Definition at line 422 of file AEMath.hpp.
References cosDeg().
absval()
template<typename T > constexpr T ace::math::absval (const T num) inline constexpr noexcept
Calculates the absolute value of a given number.
Template Parameters
T The type of the passed number
Parameters
num The value to calculate absolute value of
Returns
Absolute value of a given number of type T
Definition at line 435 of file AEMath.hpp.
fequals() [1/2]
template<typename T = long double> requires (std::is_floating_point<T>::value == true) constexpr bool ace::math::fequals (const T num, const T num2, const T _epsilon) constexpr noexcept
Compares two floating point values for equality, within a given epsilon
Template Parameters
T The type of the floating point value
Parameters
num The first float to compare
num2 The second float to compare
_epsilon The epsilon to compare against
Returns
If both numbers are equal (within epsilon):
True
Otherwise:
False
Definition at line 455 of file AEMath.hpp.
fequals() [2/2]
template<typename T = long double> requires (std::is_floating_point<T>::value == true) constexpr bool ace::math::fequals (const T num, const T num2) constexpr noexcept
Compares two floating point values for equality, within a default (scaled) epsilon.
The epsilon is std::numeric_limits<T>::epsilon() * the smallest number of the 2
Note
This is a helper/shortcut function of ace::math::fequals(const T num, const T num2, const T _epsilon)
Template Parameters
T The type of the floats
Parameters
num The first float to compare
num2 The second float to compare
Returns
If both numbers are equal (within epsilon):
True
Otherwise:
False
Definition at line 477 of file AEMath.hpp.
equals()
template<typename T , typename Y = T> constexpr bool ace::math::equals (const T & num, const Y & num2) constexpr noexcept
Checks if given 2 numbers are equal, a generic function for all types.
Note
If the T type is a float, returns the result of ace::math::fequals() with the default epsilon values
See also
ace::math::fequals(const T num, const T num2)
Template Parameters
T The type of the first number passed
Y The type of the second number passed (defaults to T)
Parameters
num The first number to compare
num2 The second number to compare
Returns
If both numbers are equal:
True
Otherwise:
False
Definition at line 499 of file AEMath.hpp.
sqrt()
template<typename T = long double> constexpr T ace::math::sqrt (const T num) constexpr noexcept
Newton's method sqrt implementation, compatible with constexpr evaluation.
Note
Exists here for the only reason that std::sqrt isn't constexpr untill c++26 (https://en.cppreference.com/w/cpp/numeric/math/sqrt)
Todo
When C++23 support appears, add if-consteval to use the newton's method in constexpr context, and use classic std::sqrt otherwise
Template Parameters
T The type of the passed value and type to calculate it with
Parameters
num The value to calculate the square root from
Returns
If the num is positive and finite:
The square root of num as type T
If the num is negative or isn't finite:
std::numeric_limits<T>::max() (largest value of type T)
Definition at line 529 of file AEMath.hpp.
References equals().
intPow()
template<typename T = long double> constexpr T ace::math::intPow (const T num, llint power) constexpr noexcept
Calculate the integer exponent of a given number.
Warning
If the type T cannot hold the result, it will overflow!
Template Parameters
T The type of the variable to calculate it with
Parameters
num The value to raise to power
power Integer power to raise the number to
Returns
If the passed num is valid and finite:
Number num raised to the exponent power
Otherwise, if num isn't finite, or it's 0 and power is negative:
std::numeric_limits<T>::max() (largest value of type T)
Definition at line 562 of file AEMath.hpp.
References equals().
root()
template<typename T = long double> constexpr T ace::math::root (const T num, const uint rtNum) constexpr noexcept
Calculate the n'th root of a number.
Thanks, Newton!
Note
If rtNum is 2, calls ace::math::sqrt() instead
Template Parameters
T The type of the variable to calculate it with
Parameters
num The number to take a root of
rtNum The root degree to calculate
Returns
If the num value is finite and valid for the given root degree:
The n'th root of num as type T
Otherwise, if num isn't finite, or the operation results in an imaginary root:
std::numeric_limits<T>::max() (largest value of type T)
Definition at line 621 of file AEMath.hpp.
References equals(), and sqrt().
max()
template<typename T > constexpr T ace::math::max (const T & a, const T & b) constexpr noexcept
Returns the largest value between the given two values.
Template Parameters
T Type of the values
Parameters
a The first value to compare
b The second value to compare
Returns
If a is more than b:
A copy of value a (since returned by value)
Otherwise:
A copy of value b (since returned by value)
Definition at line 659 of file AEMath.hpp.
min()
template<typename T > constexpr T ace::math::min (const T & a, const T & b) constexpr noexcept
Gets the smallest value between given two values.
Template Parameters
T Type of the values
Parameters
a The first value to compare
b The second value to compare
Returns
If a is less than b:
A copy of value a (since returned by value)
Otherwise:
A copy of value b (since returned by value)
Definition at line 677 of file AEMath.hpp.
lengthOfInt()
template<typename T > requires (std::is_integral<T>::value == true) constexpr uint ace::math::lengthOfInt (T num) constexpr noexcept
Calculate the length of the given integer number.
Note
Passing non-integral value will not compile
Template Parameters
T The type of the integer number
Parameters
num The number to calculate the length of
Returns
The length of the integer num as uint
Definition at line 691 of file AEMath.hpp.
lengthOfFloat()
template<typename T > requires (std::is_floating_point<T>::value == true) constexpr uint ace::math::lengthOfFloat (const T num) constexpr noexcept
Calculate the length of the given float number's non-fractional part.
Essentially ace::math::lengthOfInt() for larger numbers.
Template Parameters
T The type of the float number
Parameters
num The number to calculate the length of
Returns
The length of the num's non fractional part as uint
Definition at line 709 of file AEMath.hpp.
lerp()
template<typename T = long double> constexpr T ace::math::lerp (const T a, const T b, const T c) constexpr noexcept
Computes the linear inter/extrapolation with the given interval boundaries a and b, and the interval percentage c.
The value of c is the percentage of the distance between values a and c:
0% is a
100% is b
50% is in between them
150% is b+half of distance a and b. Example: lower boundary a is 0, higher boundary b is 10, interval coefficient c is 0.75; The result is 7.5.
Example: lower boundary a is 0, higher boundary b is 10, interval coefficient c is 1.5; The result is 15.
Note
if c is outside of 0 and 1, computes linear extrapolation.
If c is between 0 (closest to boundary a) and 1 (closest to boundary b), computes linear interpolation.
https://en.wikipedia.org/wiki/Linear_interpolation
Template Parameters
T The type to calculate it with
Parameters
a The value of a (lower known boundary)
b The value of b (higher known boundary)
c The value for inter/extrapolation (interval percentage)
Returns
The inter/extrapolated value of type T
Definition at line 736 of file AEMath.hpp.
hypot()
template<typename T = long double> constexpr T ace::math::hypot (const T a, const T b) constexpr noexcept
Calculates the hypotenuse length from given values a and b.
Template Parameters
T The type of the variable to calculate it with
Parameters
a The length of side a in the right triangle
b The length of side b in the right triangle
Returns
The length of hypotenuse of type T with given lengths of a and b sides
Definition at line 750 of file AEMath.hpp.
roundToInt()
template<typename T = llint, typename Y = long double> requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true) constexpr T ace::math::roundToInt (const Y num) constexpr noexcept
Rounds the given float of type Y to integer of type T.
Warning
If value overflows – return value depends on the overflow behaviour of your platform/compiler
Note
num should be finite (check with ace::math::isFinite())
Template Parameters
T The type of the integer to round to
Y The type of the float to round
Parameters
num The floating point number to round
Returns
If the type Y is an integral type:
Simply num casted to type T;
If the type Y is a floating point type:
The rounded integer of type T, from the given num value
Definition at line 770 of file AEMath.hpp.
floorToInt()
template<typename T = llint, typename Y = long double> requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true) constexpr T ace::math::floorToInt (const Y num) constexpr noexcept
Floor's the given float of type Y and converts to integer of type T.
Warning
If value overflows – return value depends on the overflow behaviour of your platform/compiler
Note
num should be finite (check with ace::math::isFinite())
If num is positive, it truncates the decimal digits (towards zero); if negative, it ceil's the decimals (away from zero)
Template Parameters
T The type of the integer to floor to
Y The type of the float to floor
Parameters
num The floating point number to floor
Returns
If the type Y is an integral type:
Simply num casted to type T;
If the type Y is a floating point type:
The floored integer of type T, from the given num value
Definition at line 795 of file AEMath.hpp.
ceilToInt()
template<typename T = llint, typename Y = long double> requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true) constexpr T ace::math::ceilToInt (const Y num) constexpr noexcept
Ceil's the given float of type Y and converts to integer of type T.
Warning
If value overflows – return value depends on the overflow behaviour of your platform/compiler
Note
num should be finite (check with ace::math::isFinite())
Template Parameters
T The type of the integer to ceil to
Y The type of the float to ceil
Parameters
num The floating point number to ceil
Returns
If the type Y is an integral type:
Simply num casted to type T;
If the type Y is a floating point type:
The ceiled integer of type T, from the given num value
Definition at line 818 of file AEMath.hpp.
truncToInt()
template<typename T = llint, typename Y = long double> requires (std::is_arithmetic<Y>::value == true && std::is_integral<T>::value == true) constexpr T ace::math::truncToInt (const Y num) constexpr noexcept
Truncates the given float of type Y and converts to integer of type T.
Warning
If value overflows – return value depends on the overflow behaviour of your platform/compiler
Note
num should be finite (check with ace::math::isFinite())
Template Parameters
T The type of the integer to truncate to
Y The type of the float to truncate
Parameters
num The floating point number to truncate
Returns
If the type Y is an integral type:
Simply num casted to type T;
If the type Y is a floating point type:
The truncated integer of type T, from the given num value
Definition at line 841 of file AEMath.hpp.
_getTrigTableIndex()
constexpr std::size_t ace::math::_getTrigTableIndex (const llint a) constexpr noexcept
Returns the index to the trig table from the given (int) degree number.
Note
If the number is negative, it wraps it from the end (-1 is the last item of the table)
Not recommended to use. It's a helper function for the trig lookup table functions
Parameters
a The integer degree number
Returns
The legal index to the lookup tables
Definition at line 109 of file AETrigLookup.hpp.
References AETRIG_TABLE_SIZE.
sinDeg_table()
constexpr float ace::math::sinDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of sine in the table.
Parameters
degrees The value of degrees to find a sine from
Returns
Float sine lookup table value that matches the (rounded) degrees amount
Definition at line 123 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and sinTable.
cosDeg_table()
constexpr float ace::math::cosDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cosine in the table.
Parameters
degrees The value of degrees to find a cosine from
Returns
Float cosine lookup table value that matches the (rounded) degrees amount
Definition at line 134 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and cosTable.
tanDeg_table()
constexpr float ace::math::tanDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of tangent in the table.
Parameters
degrees The value of degrees to find a tangent from
Returns
Float tangent lookup table value that matches the (rounded) degrees amount
Definition at line 145 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and tanTable.
cotDeg_table()
constexpr float ace::math::cotDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cotangent in the table.
Parameters
degrees The value of degrees to find a cotangent from
Returns
Float cotangent lookup table value that matches the (rounded) degrees amount
Definition at line 156 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and cotTable.
cscDeg_table()
constexpr float ace::math::cscDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of cosecant in the table.
Parameters
degrees The value of degrees to find a cosecant from
Returns
Float cosecant lookup table value that matches the (rounded) degrees amount
Definition at line 167 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and cscTable.
secDeg_table()
constexpr float ace::math::secDeg_table (const float degrees) constexpr noexcept
Rounds the degrees value, and looks up the value of secant in the table.
Parameters
degrees The value of degrees to find a secant from
Returns
Float secant lookup table value that matches the (rounded) degrees amount
Definition at line 178 of file AETrigLookup.hpp.
References _getTrigTableIndex(), and secTable.
sinDeg_tableInterp()
constexpr float ace::math::sinDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated sine value from the sine lookup table.
Note
Correct to the sine value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a sine from
Returns
Float of interpolated sine value
Definition at line 190 of file AETrigLookup.hpp.
References _getTrigTableIndex(), sinTable, and truncToInt().
cosDeg_tableInterp()
constexpr float ace::math::cosDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated cosine value from the cosine lookup table.
Note
Correct to the cosine value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cosine from
Returns
Float of interpolated cosine value
Definition at line 203 of file AETrigLookup.hpp.
References _getTrigTableIndex(), cosTable, and truncToInt().
tanDeg_tableInterp()
constexpr float ace::math::tanDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated tangent value from the tangent lookup table.
Note
Correct to the tangent value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a tangent from
Returns
Float of interpolated tangent value
Definition at line 216 of file AETrigLookup.hpp.
References _getTrigTableIndex(), tanTable, and truncToInt().
cotDeg_tableInterp()
constexpr float ace::math::cotDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated cotangent value from the cotangent lookup table.
Note
Correct to the cotangent value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cotangent from
Returns
Float of interpolated cotangent value
Definition at line 229 of file AETrigLookup.hpp.
References _getTrigTableIndex(), cotTable, and truncToInt().
cscDeg_tableInterp()
constexpr float ace::math::cscDeg_tableInterp (const float degrees) constexpr noexcept
Approximates the interpolated cosecant value from the cosecant lookup table.
Note
Correct to the cosecant value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a cosecant from
Returns
Float of interpolated cosecant value
Definition at line 242 of file AETrigLookup.hpp.
References _getTrigTableIndex(), cscTable, and truncToInt().
secDeg_tableInterp()
constexpr float ace::math::secDeg_tableInterp (const float degrees) constexpr noexcept
Calculates the interpolated secant value from the secant lookup table.
Note
Correct to the secant value up to a few decimal point digits: truncating digits -> up to 3, rounding digits -> up to 4
Parameters
degrees The value of degrees to find a secant from
Returns
Float of interpolated secant value
Definition at line 255 of file AETrigLookup.hpp.
References _getTrigTableIndex(), secTable, and truncToInt().
Variable Documentation
sinTable
constexpr float ace::math::sinTable[360] constexpr
Initial value:
{
        0.00000000f, 0.01745241f, 0.03489950f, 0.05233596f, 0.06975647f, 0.08715574f, 0.10452846f, 0.12186934f, 0.13917310f, 0.15643447f, 0.17364818f, 0.19080900f, 0.20791169f, 0.22495105f, 0.24192190f, 0.25881905f, 0.27563736f, 0.29237170f, 0.30901699f, 0.32556815f, 0.34202014f, 0.35836795f, 0.37460659f, 0.39073113f, 0.40673664f, 0.42261826f, 0.43837115f, 0.45399050f, 0.46947156f, 0.48480962f, 0.50000000f, 0.51503807f, 0.52991926f, 0.54463904f, 0.55919290f, 0.57357644f, 0.58778525f, 0.60181502f, 0.61566148f, 0.62932039f, 0.64278761f, 0.65605903f, 0.66913061f, 0.68199836f, 0.69465837f, 0.70710678f, 0.71933980f, 0.73135370f, 0.74314483f, 0.75470958f, 0.76604444f, 0.77714596f, 0.78801075f, 0.79863551f, 0.80901699f, 0.81915204f, 0.82903757f, 0.83867057f, 0.84804810f, 0.85716730f,
        0.86602540f, 0.87461971f, 0.88294759f, 0.89100652f, 0.89879405f, 0.90630779f, 0.91354546f, 0.92050485f, 0.92718385f, 0.93358043f, 0.93969262f, 0.94551858f, 0.95105652f, 0.95630476f, 0.96126170f, 0.96592583f, 0.97029573f, 0.97437006f, 0.97814760f, 0.98162718f, 0.98480775f, 0.98768834f, 0.99026807f, 0.99254615f, 0.99452190f, 0.99619470f, 0.99756405f, 0.99862953f, 0.99939083f, 0.99984770f, 1.00000000f, 0.99984770f, 0.99939083f, 0.99862953f, 0.99756405f, 0.99619470f, 0.99452190f, 0.99254615f, 0.99026807f, 0.98768834f, 0.98480775f, 0.98162718f, 0.97814760f, 0.97437006f, 0.97029573f, 0.96592583f, 0.96126170f, 0.95630476f, 0.95105652f, 0.94551858f, 0.93969262f, 0.93358043f, 0.92718385f, 0.92050485f, 0.91354546f, 0.90630779f, 0.89879405f, 0.89100652f, 0.88294759f, 0.87461971f,
        0.86602540f, 0.85716730f, 0.84804810f, 0.83867057f, 0.82903757f, 0.81915204f, 0.80901699f, 0.79863551f, 0.78801075f, 0.77714596f, 0.76604444f, 0.75470958f, 0.74314483f, 0.73135370f, 0.71933980f, 0.70710678f, 0.69465837f, 0.68199836f, 0.66913061f, 0.65605903f, 0.64278761f, 0.62932039f, 0.61566148f, 0.60181502f, 0.58778525f, 0.57357644f, 0.55919290f, 0.54463904f, 0.52991926f, 0.51503807f, 0.50000000f, 0.48480962f, 0.46947156f, 0.45399050f, 0.43837115f, 0.42261826f, 0.40673664f, 0.39073113f, 0.37460659f, 0.35836795f, 0.34202014f, 0.32556815f, 0.30901699f, 0.29237170f, 0.27563736f, 0.25881905f, 0.24192190f, 0.22495105f, 0.20791169f, 0.19080900f, 0.17364818f, 0.15643447f, 0.13917310f, 0.12186934f, 0.10452846f, 0.08715574f, 0.06975647f, 0.05233596f, 0.03489950f, 0.01745241f,
        0.00000000f, -0.01745241f, -0.03489950f, -0.05233596f, -0.06975647f, -0.08715574f, -0.10452846f, -0.12186934f, -0.13917310f, -0.15643447f, -0.17364818f, -0.19080900f, -0.20791169f, -0.22495105f, -0.24192190f, -0.25881905f, -0.27563736f, -0.29237170f, -0.30901699f, -0.32556815f, -0.34202014f, -0.35836795f, -0.37460659f, -0.39073113f, -0.40673664f, -0.42261826f, -0.43837115f, -0.45399050f, -0.46947156f, -0.48480962f, -0.50000000f, -0.51503807f, -0.52991926f, -0.54463904f, -0.55919290f, -0.57357644f, -0.58778525f, -0.60181502f, -0.61566148f, -0.62932039f, -0.64278761f, -0.65605903f, -0.66913061f, -0.68199836f, -0.69465837f, -0.70710678f, -0.71933980f, -0.73135370f, -0.74314483f, -0.75470958f, -0.76604444f, -0.77714596f, -0.78801075f, -0.79863551f, -0.80901699f, -0.81915204f, -0.82903757f, -0.83867057f, -0.84804810f, -0.85716730f,
        -0.86602540f, -0.87461971f, -0.88294759f, -0.89100652f, -0.89879405f, -0.90630779f, -0.91354546f, -0.92050485f, -0.92718385f, -0.93358043f, -0.93969262f, -0.94551858f, -0.95105652f, -0.95630476f, -0.96126170f, -0.96592583f, -0.97029573f, -0.97437006f, -0.97814760f, -0.98162718f, -0.98480775f, -0.98768834f, -0.99026807f, -0.99254615f, -0.99452190f, -0.99619470f, -0.99756405f, -0.99862953f, -0.99939083f, -0.99984770f, -1.00000000f, -0.99984770f, -0.99939083f, -0.99862953f, -0.99756405f, -0.99619470f, -0.99452190f, -0.99254615f, -0.99026807f, -0.98768834f, -0.98480775f, -0.98162718f, -0.97814760f, -0.97437006f, -0.97029573f, -0.96592583f, -0.96126170f, -0.95630476f, -0.95105652f, -0.94551858f, -0.93969262f, -0.93358043f, -0.92718385f, -0.92050485f, -0.91354546f, -0.90630779f, -0.89879405f, -0.89100652f, -0.88294759f, -0.87461971f,
        -0.86602540f, -0.85716730f, -0.84804810f, -0.83867057f, -0.82903757f, -0.81915204f, -0.80901699f, -0.79863551f, -0.78801075f, -0.77714596f, -0.76604444f, -0.75470958f, -0.74314483f, -0.73135370f, -0.71933980f, -0.70710678f, -0.69465837f, -0.68199836f, -0.66913061f, -0.65605903f, -0.64278761f, -0.62932039f, -0.61566148f, -0.60181502f, -0.58778525f, -0.57357644f, -0.55919290f, -0.54463904f, -0.52991926f, -0.51503807f, -0.50000000f, -0.48480962f, -0.46947156f, -0.45399050f, -0.43837115f, -0.42261826f, -0.40673664f, -0.39073113f, -0.37460659f, -0.35836795f, -0.34202014f, -0.32556815f, -0.30901699f, -0.29237170f, -0.27563736f, -0.25881905f, -0.24192190f, -0.22495105f, -0.20791169f, -0.19080900f, -0.17364818f, -0.15643447f, -0.13917310f, -0.12186934f, -0.10452846f, -0.08715574f, -0.06975647f, -0.05233596f, -0.03489950f, -0.01745241f,
    }
A lookup table for sine values (degrees)
Definition at line 41 of file AETrigLookup.hpp.
cosTable
constexpr float ace::math::cosTable[360] constexpr
Initial value:
{
        1.00000000f, 0.99984770f, 0.99939083f, 0.99862953f, 0.99756405f, 0.99619470f, 0.99452190f, 0.99254615f, 0.99026807f, 0.98768834f, 0.98480775f, 0.98162718f, 0.97814760f, 0.97437006f, 0.97029573f, 0.96592583f, 0.96126170f, 0.95630476f, 0.95105652f, 0.94551858f, 0.93969262f, 0.93358043f, 0.92718385f, 0.92050485f, 0.91354546f, 0.90630779f, 0.89879405f, 0.89100652f, 0.88294759f, 0.87461971f, 0.86602540f, 0.85716730f, 0.84804810f, 0.83867057f, 0.82903757f, 0.81915204f, 0.80901699f, 0.79863551f, 0.78801075f, 0.77714596f, 0.76604444f, 0.75470958f, 0.74314483f, 0.73135370f, 0.71933980f, 0.70710678f, 0.69465837f, 0.68199836f, 0.66913061f, 0.65605903f, 0.64278761f, 0.62932039f, 0.61566148f, 0.60181502f, 0.58778525f, 0.57357644f, 0.55919290f, 0.54463904f, 0.52991926f, 0.51503807f,
        0.50000000f, 0.48480962f, 0.46947156f, 0.45399050f, 0.43837115f, 0.42261826f, 0.40673664f, 0.39073113f, 0.37460659f, 0.35836795f, 0.34202014f, 0.32556815f, 0.30901699f, 0.29237170f, 0.27563736f, 0.25881905f, 0.24192190f, 0.22495105f, 0.20791169f, 0.19080900f, 0.17364818f, 0.15643447f, 0.13917310f, 0.12186934f, 0.10452846f, 0.08715574f, 0.06975647f, 0.05233596f, 0.03489950f, 0.01745241f, 0.00000000f, -0.01745241f, -0.03489950f, -0.05233596f, -0.06975647f, -0.08715574f, -0.10452846f, -0.12186934f, -0.13917310f, -0.15643447f, -0.17364818f, -0.19080900f, -0.20791169f, -0.22495105f, -0.24192190f, -0.25881905f, -0.27563736f, -0.29237170f, -0.30901699f, -0.32556815f, -0.34202014f, -0.35836795f, -0.37460659f, -0.39073113f, -0.40673664f, -0.42261826f, -0.43837115f, -0.45399050f, -0.46947156f, -0.48480962f,
        -0.50000000f, -0.51503807f, -0.52991926f, -0.54463904f, -0.55919290f, -0.57357644f, -0.58778525f, -0.60181502f, -0.61566148f, -0.62932039f, -0.64278761f, -0.65605903f, -0.66913061f, -0.68199836f, -0.69465837f, -0.70710678f, -0.71933980f, -0.73135370f, -0.74314483f, -0.75470958f, -0.76604444f, -0.77714596f, -0.78801075f, -0.79863551f, -0.80901699f, -0.81915204f, -0.82903757f, -0.83867057f, -0.84804810f, -0.85716730f, -0.86602540f, -0.87461971f, -0.88294759f, -0.89100652f, -0.89879405f, -0.90630779f, -0.91354546f, -0.92050485f, -0.92718385f, -0.93358043f, -0.93969262f, -0.94551858f, -0.95105652f, -0.95630476f, -0.96126170f, -0.96592583f, -0.97029573f, -0.97437006f, -0.97814760f, -0.98162718f, -0.98480775f, -0.98768834f, -0.99026807f, -0.99254615f, -0.99452190f, -0.99619470f, -0.99756405f, -0.99862953f, -0.99939083f, -0.99984770f,
        -1.00000000f, -0.99984770f, -0.99939083f, -0.99862953f, -0.99756405f, -0.99619470f, -0.99452190f, -0.99254615f, -0.99026807f, -0.98768834f, -0.98480775f, -0.98162718f, -0.97814760f, -0.97437006f, -0.97029573f, -0.96592583f, -0.96126170f, -0.95630476f, -0.95105652f, -0.94551858f, -0.93969262f, -0.93358043f, -0.92718385f, -0.92050485f, -0.91354546f, -0.90630779f, -0.89879405f, -0.89100652f, -0.88294759f, -0.87461971f, -0.86602540f, -0.85716730f, -0.84804810f, -0.83867057f, -0.82903757f, -0.81915204f, -0.80901699f, -0.79863551f, -0.78801075f, -0.77714596f, -0.76604444f, -0.75470958f, -0.74314483f, -0.73135370f, -0.71933980f, -0.70710678f, -0.69465837f, -0.68199836f, -0.66913061f, -0.65605903f, -0.64278761f, -0.62932039f, -0.61566148f, -0.60181502f, -0.58778525f, -0.57357644f, -0.55919290f, -0.54463904f, -0.52991926f, -0.51503807f,
        -0.50000000f, -0.48480962f, -0.46947156f, -0.45399050f, -0.43837115f, -0.42261826f, -0.40673664f, -0.39073113f, -0.37460659f, -0.35836795f, -0.34202014f, -0.32556815f, -0.30901699f, -0.29237170f, -0.27563736f, -0.25881905f, -0.24192190f, -0.22495105f, -0.20791169f, -0.19080900f, -0.17364818f, -0.15643447f, -0.13917310f, -0.12186934f, -0.10452846f, -0.08715574f, -0.06975647f, -0.05233596f, -0.03489950f, -0.01745241f, -0.00000000f, 0.01745241f, 0.03489950f, 0.05233596f, 0.06975647f, 0.08715574f, 0.10452846f, 0.12186934f, 0.13917310f, 0.15643447f, 0.17364818f, 0.19080900f, 0.20791169f, 0.22495105f, 0.24192190f, 0.25881905f, 0.27563736f, 0.29237170f, 0.30901699f, 0.32556815f, 0.34202014f, 0.35836795f, 0.37460659f, 0.39073113f, 0.40673664f, 0.42261826f, 0.43837115f, 0.45399050f, 0.46947156f, 0.48480962f,
        0.50000000f, 0.51503807f, 0.52991926f, 0.54463904f, 0.55919290f, 0.57357644f, 0.58778525f, 0.60181502f, 0.61566148f, 0.62932039f, 0.64278761f, 0.65605903f, 0.66913061f, 0.68199836f, 0.69465837f, 0.70710678f, 0.71933980f, 0.73135370f, 0.74314483f, 0.75470958f, 0.76604444f, 0.77714596f, 0.78801075f, 0.79863551f, 0.80901699f, 0.81915204f, 0.82903757f, 0.83867057f, 0.84804810f, 0.85716730f, 0.86602540f, 0.87461971f, 0.88294759f, 0.89100652f, 0.89879405f, 0.90630779f, 0.91354546f, 0.92050485f, 0.92718385f, 0.93358043f, 0.93969262f, 0.94551858f, 0.95105652f, 0.95630476f, 0.96126170f, 0.96592583f, 0.97029573f, 0.97437006f, 0.97814760f, 0.98162718f, 0.98480775f, 0.98768834f, 0.99026807f, 0.99254615f, 0.99452190f, 0.99619470f, 0.99756405f, 0.99862953f, 0.99939083f, 0.99984770f,
    }
A lookup table for cosine values (degrees)
Definition at line 51 of file AETrigLookup.hpp.
tanTable
constexpr float ace::math::tanTable[360] constexpr
Initial value:
{
        0.00000000f, 0.01745506f, 0.03492077f, 0.05240778f, 0.06992681f, 0.08748866f, 0.10510424f, 0.12278456f, 0.14054083f, 0.15838444f, 0.17632698f, 0.19438031f, 0.21255656f, 0.23086819f, 0.24932800f, 0.26794919f, 0.28674539f, 0.30573068f, 0.32491970f, 0.34432761f, 0.36397023f, 0.38386404f, 0.40402623f, 0.42447482f, 0.44522869f, 0.46630766f, 0.48773259f, 0.50952545f, 0.53170943f, 0.55430905f, 0.57735027f, 0.60086062f, 0.62486935f, 0.64940759f, 0.67450852f, 0.70020754f, 0.72654253f, 0.75355405f, 0.78128563f, 0.80978403f, 0.83909963f, 0.86928674f, 0.90040404f, 0.93251509f, 0.96568877f, 1.00000000f, 1.03553031f, 1.07236871f, 1.11061251f, 1.15036841f, 1.19175359f, 1.23489716f, 1.27994163f, 1.32704482f, 1.37638192f, 1.42814801f, 1.48256097f, 1.53986496f, 1.60033453f, 1.66427948f,
        1.73205081f, 1.80404776f, 1.88072647f, 1.96261051f, 2.05030384f, 2.14450692f, 2.24603677f, 2.35585237f, 2.47508685f, 2.60508906f, 2.74747742f, 2.90421088f, 3.07768354f, 3.27085262f, 3.48741444f, 3.73205081f, 4.01078093f, 4.33147587f, 4.70463011f, 5.14455402f, 5.67128182f, 6.31375151f, 7.11536972f, 8.14434643f, 9.51436445f, 11.43005230f, 14.30066626f, 19.08113669f, 28.63625328f, 57.28996163f, FLT_MAX, -57.28996163f, -28.63625328f, -19.08113669f, -14.30066626f, -11.43005230f, -9.51436445f, -8.14434643f, -7.11536972f, -6.31375151f, -5.67128182f, -5.14455402f, -4.70463011f, -4.33147587f, -4.01078093f, -3.73205081f, -3.48741444f, -3.27085262f, -3.07768354f, -2.90421088f, -2.74747742f, -2.60508906f, -2.47508685f, -2.35585237f, -2.24603677f, -2.14450692f, -2.05030384f, -1.96261051f, -1.88072647f, -1.80404776f,
        -1.73205081f, -1.66427948f, -1.60033453f, -1.53986496f, -1.48256097f, -1.42814801f, -1.37638192f, -1.32704482f, -1.27994163f, -1.23489716f, -1.19175359f, -1.15036841f, -1.11061251f, -1.07236871f, -1.03553031f, -1.00000000f, -0.96568877f, -0.93251509f, -0.90040404f, -0.86928674f, -0.83909963f, -0.80978403f, -0.78128563f, -0.75355405f, -0.72654253f, -0.70020754f, -0.67450852f, -0.64940759f, -0.62486935f, -0.60086062f, -0.57735027f, -0.55430905f, -0.53170943f, -0.50952545f, -0.48773259f, -0.46630766f, -0.44522869f, -0.42447482f, -0.40402623f, -0.38386404f, -0.36397023f, -0.34432761f, -0.32491970f, -0.30573068f, -0.28674539f, -0.26794919f, -0.24932800f, -0.23086819f, -0.21255656f, -0.19438031f, -0.17632698f, -0.15838444f, -0.14054083f, -0.12278456f, -0.10510424f, -0.08748866f, -0.06992681f, -0.05240778f, -0.03492077f, -0.01745506f,
        -0.00000000f, 0.01745506f, 0.03492077f, 0.05240778f, 0.06992681f, 0.08748866f, 0.10510424f, 0.12278456f, 0.14054083f, 0.15838444f, 0.17632698f, 0.19438031f, 0.21255656f, 0.23086819f, 0.24932800f, 0.26794919f, 0.28674539f, 0.30573068f, 0.32491970f, 0.34432761f, 0.36397023f, 0.38386404f, 0.40402623f, 0.42447482f, 0.44522869f, 0.46630766f, 0.48773259f, 0.50952545f, 0.53170943f, 0.55430905f, 0.57735027f, 0.60086062f, 0.62486935f, 0.64940759f, 0.67450852f, 0.70020754f, 0.72654253f, 0.75355405f, 0.78128563f, 0.80978403f, 0.83909963f, 0.86928674f, 0.90040404f, 0.93251509f, 0.96568877f, 1.00000000f, 1.03553031f, 1.07236871f, 1.11061251f, 1.15036841f, 1.19175359f, 1.23489716f, 1.27994163f, 1.32704482f, 1.37638192f, 1.42814801f, 1.48256097f, 1.53986496f, 1.60033453f, 1.66427948f,
        1.73205081f, 1.80404776f, 1.88072647f, 1.96261051f, 2.05030384f, 2.14450692f, 2.24603677f, 2.35585237f, 2.47508685f, 2.60508906f, 2.74747742f, 2.90421088f, 3.07768354f, 3.27085262f, 3.48741444f, 3.73205081f, 4.01078093f, 4.33147587f, 4.70463011f, 5.14455402f, 5.67128182f, 6.31375151f, 7.11536972f, 8.14434643f, 9.51436445f, 11.43005230f, 14.30066626f, 19.08113669f, 28.63625328f, 57.28996163f, FLT_MAX, -57.28996163f, -28.63625328f, -19.08113669f, -14.30066626f, -11.43005230f, -9.51436445f, -8.14434643f, -7.11536972f, -6.31375151f, -5.67128182f, -5.14455402f, -4.70463011f, -4.33147587f, -4.01078093f, -3.73205081f, -3.48741444f, -3.27085262f, -3.07768354f, -2.90421088f, -2.74747742f, -2.60508906f, -2.47508685f, -2.35585237f, -2.24603677f, -2.14450692f, -2.05030384f, -1.96261051f, -1.88072647f, -1.80404776f,
        -1.73205081f, -1.66427948f, -1.60033453f, -1.53986496f, -1.48256097f, -1.42814801f, -1.37638192f, -1.32704482f, -1.27994163f, -1.23489716f, -1.19175359f, -1.15036841f, -1.11061251f, -1.07236871f, -1.03553031f, -1.00000000f, -0.96568877f, -0.93251509f, -0.90040404f, -0.86928674f, -0.83909963f, -0.80978403f, -0.78128563f, -0.75355405f, -0.72654253f, -0.70020754f, -0.67450852f, -0.64940759f, -0.62486935f, -0.60086062f, -0.57735027f, -0.55430905f, -0.53170943f, -0.50952545f, -0.48773259f, -0.46630766f, -0.44522869f, -0.42447482f, -0.40402623f, -0.38386404f, -0.36397023f, -0.34432761f, -0.32491970f, -0.30573068f, -0.28674539f, -0.26794919f, -0.24932800f, -0.23086819f, -0.21255656f, -0.19438031f, -0.17632698f, -0.15838444f, -0.14054083f, -0.12278456f, -0.10510424f, -0.08748866f, -0.06992681f, -0.05240778f, -0.03492077f, -0.01745506f,
    }
A lookup table for tangent values (degrees)
Definition at line 61 of file AETrigLookup.hpp.
cotTable
constexpr float ace::math::cotTable[360] constexpr
Initial value:
{
        FLT_MAX, 57.28996163f, 28.63625328f, 19.08113669f, 14.30066626f, 11.43005230f, 9.51436445f, 8.14434643f, 7.11536972f, 6.31375151f, 5.67128182f, 5.14455402f, 4.70463011f, 4.33147587f, 4.01078093f, 3.73205081f, 3.48741444f, 3.27085262f, 3.07768354f, 2.90421088f, 2.74747742f, 2.60508906f, 2.47508685f, 2.35585237f, 2.24603677f, 2.14450692f, 2.05030384f, 1.96261051f, 1.88072647f, 1.80404776f, 1.73205081f, 1.66427948f, 1.60033453f, 1.53986496f, 1.48256097f, 1.42814801f, 1.37638192f, 1.32704482f, 1.27994163f, 1.23489716f, 1.19175359f, 1.15036841f, 1.11061251f, 1.07236871f, 1.03553031f, 1.00000000f, 0.96568877f, 0.93251509f, 0.90040404f, 0.86928674f, 0.83909963f, 0.80978403f, 0.78128563f, 0.75355405f, 0.72654253f, 0.70020754f, 0.67450852f, 0.64940759f, 0.62486935f, 0.60086062f,
        0.57735027f, 0.55430905f, 0.53170943f, 0.50952545f, 0.48773259f, 0.46630766f, 0.44522869f, 0.42447482f, 0.40402623f, 0.38386404f, 0.36397023f, 0.34432761f, 0.32491970f, 0.30573068f, 0.28674539f, 0.26794919f, 0.24932800f, 0.23086819f, 0.21255656f, 0.19438031f, 0.17632698f, 0.15838444f, 0.14054083f, 0.12278456f, 0.10510424f, 0.08748866f, 0.06992681f, 0.05240778f, 0.03492077f, 0.01745506f, 0.00000000f, -0.01745506f, -0.03492077f, -0.05240778f, -0.06992681f, -0.08748866f, -0.10510424f, -0.12278456f, -0.14054083f, -0.15838444f, -0.17632698f, -0.19438031f, -0.21255656f, -0.23086819f, -0.24932800f, -0.26794919f, -0.28674539f, -0.30573068f, -0.32491970f, -0.34432761f, -0.36397023f, -0.38386404f, -0.40402623f, -0.42447482f, -0.44522869f, -0.46630766f, -0.48773259f, -0.50952545f, -0.53170943f, -0.55430905f,
        -0.57735027f, -0.60086062f, -0.62486935f, -0.64940759f, -0.67450852f, -0.70020754f, -0.72654253f, -0.75355405f, -0.78128563f, -0.80978403f, -0.83909963f, -0.86928674f, -0.90040404f, -0.93251509f, -0.96568877f, -1.00000000f, -1.03553031f, -1.07236871f, -1.11061251f, -1.15036841f, -1.19175359f, -1.23489716f, -1.27994163f, -1.32704482f, -1.37638192f, -1.42814801f, -1.48256097f, -1.53986496f, -1.60033453f, -1.66427948f, -1.73205081f, -1.80404776f, -1.88072647f, -1.96261051f, -2.05030384f, -2.14450692f, -2.24603677f, -2.35585237f, -2.47508685f, -2.60508906f, -2.74747742f, -2.90421088f, -3.07768354f, -3.27085262f, -3.48741444f, -3.73205081f, -4.01078093f, -4.33147587f, -4.70463011f, -5.14455402f, -5.67128182f, -6.31375151f, -7.11536972f, -8.14434643f, -9.51436445f, -11.43005230f, -14.30066626f, -19.08113669f, -28.63625328f, -57.28996163f,
        -FLT_MAX, 57.28996163f, 28.63625328f, 19.08113669f, 14.30066626f, 11.43005230f, 9.51436445f, 8.14434643f, 7.11536972f, 6.31375151f, 5.67128182f, 5.14455402f, 4.70463011f, 4.33147587f, 4.01078093f, 3.73205081f, 3.48741444f, 3.27085262f, 3.07768354f, 2.90421088f, 2.74747742f, 2.60508906f, 2.47508685f, 2.35585237f, 2.24603677f, 2.14450692f, 2.05030384f, 1.96261051f, 1.88072647f, 1.80404776f, 1.73205081f, 1.66427948f, 1.60033453f, 1.53986496f, 1.48256097f, 1.42814801f, 1.37638192f, 1.32704482f, 1.27994163f, 1.23489716f, 1.19175359f, 1.15036841f, 1.11061251f, 1.07236871f, 1.03553031f, 1.00000000f, 0.96568877f, 0.93251509f, 0.90040404f, 0.86928674f, 0.83909963f, 0.80978403f, 0.78128563f, 0.75355405f, 0.72654253f, 0.70020754f, 0.67450852f, 0.64940759f, 0.62486935f, 0.60086062f,
        0.57735027f, 0.55430905f, 0.53170943f, 0.50952545f, 0.48773259f, 0.46630766f, 0.44522869f, 0.42447482f, 0.40402623f, 0.38386404f, 0.36397023f, 0.34432761f, 0.32491970f, 0.30573068f, 0.28674539f, 0.26794919f, 0.24932800f, 0.23086819f, 0.21255656f, 0.19438031f, 0.17632698f, 0.15838444f, 0.14054083f, 0.12278456f, 0.10510424f, 0.08748866f, 0.06992681f, 0.05240778f, 0.03492077f, 0.01745506f, 0.00000000f, -0.01745506f, -0.03492077f, -0.05240778f, -0.06992681f, -0.08748866f, -0.10510424f, -0.12278456f, -0.14054083f, -0.15838444f, -0.17632698f, -0.19438031f, -0.21255656f, -0.23086819f, -0.24932800f, -0.26794919f, -0.28674539f, -0.30573068f, -0.32491970f, -0.34432761f, -0.36397023f, -0.38386404f, -0.40402623f, -0.42447482f, -0.44522869f, -0.46630766f, -0.48773259f, -0.50952545f, -0.53170943f, -0.55430905f,
        -0.57735027f, -0.60086062f, -0.62486935f, -0.64940759f, -0.67450852f, -0.70020754f, -0.72654253f, -0.75355405f, -0.78128563f, -0.80978403f, -0.83909963f, -0.86928674f, -0.90040404f, -0.93251509f, -0.96568877f, -1.00000000f, -1.03553031f, -1.07236871f, -1.11061251f, -1.15036841f, -1.19175359f, -1.23489716f, -1.27994163f, -1.32704482f, -1.37638192f, -1.42814801f, -1.48256097f, -1.53986496f, -1.60033453f, -1.66427948f, -1.73205081f, -1.80404776f, -1.88072647f, -1.96261051f, -2.05030384f, -2.14450692f, -2.24603677f, -2.35585237f, -2.47508685f, -2.60508906f, -2.74747742f, -2.90421088f, -3.07768354f, -3.27085262f, -3.48741444f, -3.73205081f, -4.01078093f, -4.33147587f, -4.70463011f, -5.14455402f, -5.67128182f, -6.31375151f, -7.11536972f, -8.14434643f, -9.51436445f, -11.43005230f, -14.30066626f, -19.08113669f, -28.63625328f, -57.28996163f,
    }
A lookup table for cotangent values (degrees)
Definition at line 71 of file AETrigLookup.hpp.
cscTable
constexpr float ace::math::cscTable[360] constexpr
Initial value:
{
        FLT_MAX, 57.29868850f, 28.65370835f, 19.10732261f, 14.33558703f, 11.47371325f, 9.56677223f, 8.20550905f, 7.18529653f, 6.39245322f, 5.75877048f, 5.24084306f, 4.80973434f, 4.44541148f, 4.13356549f, 3.86370331f, 3.62795528f, 3.42030362f, 3.23606798f, 3.07155349f, 2.92380440f, 2.79042811f, 2.66946716f, 2.55930467f, 2.45859334f, 2.36620158f, 2.28117203f, 2.20268926f, 2.13005447f, 2.06266534f, 2.00000000f, 1.94160403f, 1.88707991f, 1.83607846f, 1.78829165f, 1.74344680f, 1.70130162f, 1.66164014f, 1.62426925f, 1.58901573f, 1.55572383f, 1.52425309f, 1.49447655f, 1.46627919f, 1.43955654f, 1.41421356f, 1.39016359f, 1.36732746f, 1.34563273f, 1.32501299f, 1.30540729f, 1.28675957f, 1.26901822f, 1.25213566f, 1.23606798f, 1.22077459f, 1.20621795f, 1.19236329f, 1.17917840f, 1.16663340f,
        1.15470054f, 1.14335407f, 1.13257005f, 1.12232624f, 1.11260194f, 1.10337792f, 1.09463628f, 1.08636038f, 1.07853474f, 1.07114499f, 1.06417777f, 1.05762068f, 1.05146222f, 1.04569176f, 1.04029944f, 1.03527618f, 1.03061363f, 1.02630411f, 1.02234059f, 1.01871669f, 1.01542661f, 1.01246513f, 1.00982757f, 1.00750983f, 1.00550828f, 1.00381984f, 1.00244190f, 1.00137235f, 1.00060954f, 1.00015233f, 1.00000000f, 1.00015233f, 1.00060954f, 1.00137235f, 1.00244190f, 1.00381984f, 1.00550828f, 1.00750983f, 1.00982757f, 1.01246513f, 1.01542661f, 1.01871669f, 1.02234059f, 1.02630411f, 1.03061363f, 1.03527618f, 1.04029944f, 1.04569176f, 1.05146222f, 1.05762068f, 1.06417777f, 1.07114499f, 1.07853474f, 1.08636038f, 1.09463628f, 1.10337792f, 1.11260194f, 1.12232624f, 1.13257005f, 1.14335407f,
        1.15470054f, 1.16663340f, 1.17917840f, 1.19236329f, 1.20621795f, 1.22077459f, 1.23606798f, 1.25213566f, 1.26901822f, 1.28675957f, 1.30540729f, 1.32501299f, 1.34563273f, 1.36732746f, 1.39016359f, 1.41421356f, 1.43955654f, 1.46627919f, 1.49447655f, 1.52425309f, 1.55572383f, 1.58901573f, 1.62426925f, 1.66164014f, 1.70130162f, 1.74344680f, 1.78829165f, 1.83607846f, 1.88707991f, 1.94160403f, 2.00000000f, 2.06266534f, 2.13005447f, 2.20268926f, 2.28117203f, 2.36620158f, 2.45859334f, 2.55930467f, 2.66946716f, 2.79042811f, 2.92380440f, 3.07155349f, 3.23606798f, 3.42030362f, 3.62795528f, 3.86370331f, 4.13356549f, 4.44541148f, 4.80973434f, 5.24084306f, 5.75877048f, 6.39245322f, 7.18529653f, 8.20550905f, 9.56677223f, 11.47371325f, 14.33558703f, 19.10732261f, 28.65370835f, 57.29868850f,
        -FLT_MAX, -57.29868850f, -28.65370835f, -19.10732261f, -14.33558703f, -11.47371325f, -9.56677223f, -8.20550905f, -7.18529653f, -6.39245322f, -5.75877048f, -5.24084306f, -4.80973434f, -4.44541148f, -4.13356549f, -3.86370331f, -3.62795528f, -3.42030362f, -3.23606798f, -3.07155349f, -2.92380440f, -2.79042811f, -2.66946716f, -2.55930467f, -2.45859334f, -2.36620158f, -2.28117203f, -2.20268926f, -2.13005447f, -2.06266534f, -2.00000000f, -1.94160403f, -1.88707991f, -1.83607846f, -1.78829165f, -1.74344680f, -1.70130162f, -1.66164014f, -1.62426925f, -1.58901573f, -1.55572383f, -1.52425309f, -1.49447655f, -1.46627919f, -1.43955654f, -1.41421356f, -1.39016359f, -1.36732746f, -1.34563273f, -1.32501299f, -1.30540729f, -1.28675957f, -1.26901822f, -1.25213566f, -1.23606798f, -1.22077459f, -1.20621795f, -1.19236329f, -1.17917840f, -1.16663340f,
        -1.15470054f, -1.14335407f, -1.13257005f, -1.12232624f, -1.11260194f, -1.10337792f, -1.09463628f, -1.08636038f, -1.07853474f, -1.07114499f, -1.06417777f, -1.05762068f, -1.05146222f, -1.04569176f, -1.04029944f, -1.03527618f, -1.03061363f, -1.02630411f, -1.02234059f, -1.01871669f, -1.01542661f, -1.01246513f, -1.00982757f, -1.00750983f, -1.00550828f, -1.00381984f, -1.00244190f, -1.00137235f, -1.00060954f, -1.00015233f, -1.00000000f, -1.00015233f, -1.00060954f, -1.00137235f, -1.00244190f, -1.00381984f, -1.00550828f, -1.00750983f, -1.00982757f, -1.01246513f, -1.01542661f, -1.01871669f, -1.02234059f, -1.02630411f, -1.03061363f, -1.03527618f, -1.04029944f, -1.04569176f, -1.05146222f, -1.05762068f, -1.06417777f, -1.07114499f, -1.07853474f, -1.08636038f, -1.09463628f, -1.10337792f, -1.11260194f, -1.12232624f, -1.13257005f, -1.14335407f,
        -1.15470054f, -1.16663340f, -1.17917840f, -1.19236329f, -1.20621795f, -1.22077459f, -1.23606798f, -1.25213566f, -1.26901822f, -1.28675957f, -1.30540729f, -1.32501299f, -1.34563273f, -1.36732746f, -1.39016359f, -1.41421356f, -1.43955654f, -1.46627919f, -1.49447655f, -1.52425309f, -1.55572383f, -1.58901573f, -1.62426925f, -1.66164014f, -1.70130162f, -1.74344680f, -1.78829165f, -1.83607846f, -1.88707991f, -1.94160403f, -2.00000000f, -2.06266534f, -2.13005447f, -2.20268926f, -2.28117203f, -2.36620158f, -2.45859334f, -2.55930467f, -2.66946716f, -2.79042811f, -2.92380440f, -3.07155349f, -3.23606798f, -3.42030362f, -3.62795528f, -3.86370331f, -4.13356549f, -4.44541148f, -4.80973434f, -5.24084306f, -5.75877048f, -6.39245322f, -7.18529653f, -8.20550905f, -9.56677223f, -11.47371325f, -14.33558703f, -19.10732261f, -28.65370835f, -57.29868850f,
    }
A lookup table for cosecant values (degrees)
Definition at line 81 of file AETrigLookup.hpp.
secTable
constexpr float ace::math::secTable[360] constexpr
Initial value:
{
        1.00000000f, 1.00015233f, 1.00060954f, 1.00137235f, 1.00244190f, 1.00381984f, 1.00550828f, 1.00750983f, 1.00982757f, 1.01246513f, 1.01542661f, 1.01871669f, 1.02234059f, 1.02630411f, 1.03061363f, 1.03527618f, 1.04029944f, 1.04569176f, 1.05146222f, 1.05762068f, 1.06417777f, 1.07114499f, 1.07853474f, 1.08636038f, 1.09463628f, 1.10337792f, 1.11260194f, 1.12232624f, 1.13257005f, 1.14335407f, 1.15470054f, 1.16663340f, 1.17917840f, 1.19236329f, 1.20621795f, 1.22077459f, 1.23606798f, 1.25213566f, 1.26901822f, 1.28675957f, 1.30540729f, 1.32501299f, 1.34563273f, 1.36732746f, 1.39016359f, 1.41421356f, 1.43955654f, 1.46627919f, 1.49447655f, 1.52425309f, 1.55572383f, 1.58901573f, 1.62426925f, 1.66164014f, 1.70130162f, 1.74344680f, 1.78829165f, 1.83607846f, 1.88707991f, 1.94160403f,
        2.00000000f, 2.06266534f, 2.13005447f, 2.20268926f, 2.28117203f, 2.36620158f, 2.45859334f, 2.55930467f, 2.66946716f, 2.79042811f, 2.92380440f, 3.07155349f, 3.23606798f, 3.42030362f, 3.62795528f, 3.86370331f, 4.13356549f, 4.44541148f, 4.80973434f, 5.24084306f, 5.75877048f, 6.39245322f, 7.18529653f, 8.20550905f, 9.56677223f, 11.47371325f, 14.33558703f, 19.10732261f, 28.65370835f, 57.29868850f, FLT_MAX, -57.29868850f, -28.65370835f, -19.10732261f, -14.33558703f, -11.47371325f, -9.56677223f, -8.20550905f, -7.18529653f, -6.39245322f, -5.75877048f, -5.24084306f, -4.80973434f, -4.44541148f, -4.13356549f, -3.86370331f, -3.62795528f, -3.42030362f, -3.23606798f, -3.07155349f, -2.92380440f, -2.79042811f, -2.66946716f, -2.55930467f, -2.45859334f, -2.36620158f, -2.28117203f, -2.20268926f, -2.13005447f, -2.06266534f,
        -2.00000000f, -1.94160403f, -1.88707991f, -1.83607846f, -1.78829165f, -1.74344680f, -1.70130162f, -1.66164014f, -1.62426925f, -1.58901573f, -1.55572383f, -1.52425309f, -1.49447655f, -1.46627919f, -1.43955654f, -1.41421356f, -1.39016359f, -1.36732746f, -1.34563273f, -1.32501299f, -1.30540729f, -1.28675957f, -1.26901822f, -1.25213566f, -1.23606798f, -1.22077459f, -1.20621795f, -1.19236329f, -1.17917840f, -1.16663340f, -1.15470054f, -1.14335407f, -1.13257005f, -1.12232624f, -1.11260194f, -1.10337792f, -1.09463628f, -1.08636038f, -1.07853474f, -1.07114499f, -1.06417777f, -1.05762068f, -1.05146222f, -1.04569176f, -1.04029944f, -1.03527618f, -1.03061363f, -1.02630411f, -1.02234059f, -1.01871669f, -1.01542661f, -1.01246513f, -1.00982757f, -1.00750983f, -1.00550828f, -1.00381984f, -1.00244190f, -1.00137235f, -1.00060954f, -1.00015233f,
        -1.00000000f, -1.00015233f, -1.00060954f, -1.00137235f, -1.00244190f, -1.00381984f, -1.00550828f, -1.00750983f, -1.00982757f, -1.01246513f, -1.01542661f, -1.01871669f, -1.02234059f, -1.02630411f, -1.03061363f, -1.03527618f, -1.04029944f, -1.04569176f, -1.05146222f, -1.05762068f, -1.06417777f, -1.07114499f, -1.07853474f, -1.08636038f, -1.09463628f, -1.10337792f, -1.11260194f, -1.12232624f, -1.13257005f, -1.14335407f, -1.15470054f, -1.16663340f, -1.17917840f, -1.19236329f, -1.20621795f, -1.22077459f, -1.23606798f, -1.25213566f, -1.26901822f, -1.28675957f, -1.30540729f, -1.32501299f, -1.34563273f, -1.36732746f, -1.39016359f, -1.41421356f, -1.43955654f, -1.46627919f, -1.49447655f, -1.52425309f, -1.55572383f, -1.58901573f, -1.62426925f, -1.66164014f, -1.70130162f, -1.74344680f, -1.78829165f, -1.83607846f, -1.88707991f, -1.94160403f,
        -2.00000000f, -2.06266534f, -2.13005447f, -2.20268926f, -2.28117203f, -2.36620158f, -2.45859334f, -2.55930467f, -2.66946716f, -2.79042811f, -2.92380440f, -3.07155349f, -3.23606798f, -3.42030362f, -3.62795528f, -3.86370331f, -4.13356549f, -4.44541148f, -4.80973434f, -5.24084306f, -5.75877048f, -6.39245322f, -7.18529653f, -8.20550905f, -9.56677223f, -11.47371325f, -14.33558703f, -19.10732261f, -28.65370835f, -57.29868850f, -FLT_MAX, 57.29868850f, 28.65370835f, 19.10732261f, 14.33558703f, 11.47371325f, 9.56677223f, 8.20550905f, 7.18529653f, 6.39245322f, 5.75877048f, 5.24084306f, 4.80973434f, 4.44541148f, 4.13356549f, 3.86370331f, 3.62795528f, 3.42030362f, 3.23606798f, 3.07155349f, 2.92380440f, 2.79042811f, 2.66946716f, 2.55930467f, 2.45859334f, 2.36620158f, 2.28117203f, 2.20268926f, 2.13005447f, 2.06266534f,
        2.00000000f, 1.94160403f, 1.88707991f, 1.83607846f, 1.78829165f, 1.74344680f, 1.70130162f, 1.66164014f, 1.62426925f, 1.58901573f, 1.55572383f, 1.52425309f, 1.49447655f, 1.46627919f, 1.43955654f, 1.41421356f, 1.39016359f, 1.36732746f, 1.34563273f, 1.32501299f, 1.30540729f, 1.28675957f, 1.26901822f, 1.25213566f, 1.23606798f, 1.22077459f, 1.20621795f, 1.19236329f, 1.17917840f, 1.16663340f, 1.15470054f, 1.14335407f, 1.13257005f, 1.12232624f, 1.11260194f, 1.10337792f, 1.09463628f, 1.08636038f, 1.07853474f, 1.07114499f, 1.06417777f, 1.05762068f, 1.05146222f, 1.04569176f, 1.04029944f, 1.03527618f, 1.03061363f, 1.02630411f, 1.02234059f, 1.01871669f, 1.01542661f, 1.01246513f, 1.00982757f, 1.00750983f, 1.00550828f, 1.00381984f, 1.00244190f, 1.00137235f, 1.00060954f, 1.00015233f,
    }
A lookup table for secant values (degrees)
Definition at line 91 of file AETrigLookup.hpp.