.TH "ace" 3 "Thu Feb 15 2024 11:57:32" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ace \- This namespace contains all of things that any of the part of program can use, and is useful\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmath\fP"
.br
.RI "Mathematical functions and other things usefull in math\&. "
.ti -1c
.RI "namespace \fButils\fP"
.br
.RI "Global usefull utilities\&. "
.in -1c
.SH "Detailed Description"
.PP 
This namespace contains all of things that any of the part of program can use, and is useful\&. 

Such things as flags, utilities, handles to windows, status(we're starting or closing), etc\&. Basically everything for everyone and public access 
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
