.TH "ace" 3 "Sat Mar 16 2024 12:23:02" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ace \- This namespace contains \fBeverything that belongs to the engine\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmath\fP"
.br
.RI "This namespace contains the engine's \fBmath and math-related functions\fP\&. "
.ti -1c
.RI "namespace \fButils\fP"
.br
.RI "This namespace contains the engine's \fButility functions and code\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
This namespace contains \fBeverything that belongs to the engine\fP\&. 

Everything but the typedefs and macros\&. 
.br
 That includes modules, custom types (structs), version and current status values, handles to windows, etc\&.
.PP
Think of it as ACEngine's version of std namespace 
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
