.TH "AEFrame/include/AEFrame.hpp" 3 "Thu Mar 14 2024 20:55:55" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEFrame/include/AEFrame.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'include/AEFlags\&.hpp'\fP
.br
\fR#include 'include/AEModuleBase\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAEFrame\fP"
.br
.RI "This is the ArtyK's Engine's frame delay module -- it allows to create precise delays for game loops\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENGINE_FPS\fP   0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the frame delay module code\&. Useful if you need to limit the execution time of the program\&. It makes sure that the loop executes with same delay, if contents of loop are processed faster than you need\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAEFrame\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENGINE_FPS   0"

.PP
Definition at line \fB22\fP of file \fBAEFrame\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
