.TH "AEFrame/include/AEFrame.hpp" 3 "Thu Nov 9 2023 20:42:38" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEFrame/include/AEFrame.hpp \- This file contains the frame delay module code\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/AETypedefs\&.hpp'\fP
.br
\fC#include 'include/AEModuleBase\&.hpp'\fP
.br
\fC#include 'include/AEFlags\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAEFrame\fP"
.br
.RI "This is the ArtyK's Engine's frame delay module -- it allows to create precise delays for game loops\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the frame delay module code\&. 

Useful if you need to limit the execution time of the program\&. It makes sure that the loop executes with same delay, if contents of loop are processed faster than you need\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAEFrame\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
