.TH "AELogParser/include/AELogParser.hpp" 3 "Thu Nov 9 2023 20:42:38" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogParser/include/AELogParser.hpp \- This file contains the [stuff]\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/AEModuleBase\&.hpp'\fP
.br
\fC#include 'include/AETypedefs\&.hpp'\fP
.br
\fC#include 'include/AEUtils\&.hpp'\fP
.br
\fC#include 'include/AEFileReader\&.hpp'\fP
.br
\fC#include 'include/AELogTypes\&.hpp'\fP
.br
\fC#include 'include/AEFlags\&.hpp'\fP
.br
\fC#include 'include/AELogEntry\&.hpp'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include <string_view>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAELogParser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_NOERROR\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_INVALID_LENGTH\fP   3"
.br
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_INVALID_TIME\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_INVALID_TYPE\fP   5"
.br
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_INVALID_MNAME\fP   6"
.br
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_INVALID_FORMAT\fP   7"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_AELP_INVALID_ENTRY_INDEX\fP   8"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the [stuff]\&. 

This file contains the definitions of the engine's [stuff]\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogParser\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP _AELP_INVALID_ENTRY_INDEX   8"

.PP
Definition at line \fB35\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_INVALID_FORMAT   7"

.PP
Definition at line \fB32\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_INVALID_LENGTH   3"

.PP
Definition at line \fB28\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_INVALID_MNAME   6"

.PP
Definition at line \fB31\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_INVALID_TIME   4"

.PP
Definition at line \fB29\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_INVALID_TYPE   5"

.PP
Definition at line \fB30\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_NOERROR   0"

.PP
Definition at line \fB27\fP of file \fBAELogParser\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
