.TH "AELogger" 3 "Fri Jan 12 2024 01:05:07" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogger \- The ArtyK's Engine's Logger module -- it manages the writing to the log files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AELogger\&.hpp>\fP
.PP
Inherits \fB__AEModuleBase< AELogger >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAELogger\fP (\fBconst\fP std::string_view \fBfname\fP, \fBconst\fP bool \fBclearLog\fP=\fBfalse\fP, \fBconst\fP \fBullint\fP \fBqueuesize\fP=\fBAELOG_DEFAULT_QUEUE_SIZE\fP)"
.br
.RI "Class constructor -- it opens the file with the given name and starts logging to it\&. "
.ti -1c
.RI "\fBAELogger\fP (\fBconst\fP std::string_view \fBlogpath\fP, \fBconst\fP std::string_view \fBfname\fP, \fBconst\fP bool \fBclearLog\fP=\fBfalse\fP, \fBconst\fP \fBullint\fP \fBqueuesize\fP=\fBAELOG_DEFAULT_QUEUE_SIZE\fP)"
.br
.RI "Class constructor -- it opens the file with the given path and name and start logging to it\&. "
.ti -1c
.RI "\fBAELogger\fP (\fBvoid\fP)"
.br
.RI "Default class constructor -- doesn't open the file, but setups the instance for one\&. "
.ti -1c
.RI "\fB~AELogger\fP (\fBvoid\fP)"
.br
.RI "Class destructor\&. "
.ti -1c
.RI "\fBAELogger\fP (\fBconst\fP \fBAELogger\fP &)=\fBdelete\fP"
.br
.RI "Deleted (for now) copy-constructor\&. "
.ti -1c
.RI "\fBAELogger\fP & \fBoperator=\fP (\fBconst\fP \fBAELogger\fP &)=\fBdelete\fP"
.br
.RI "Deleted (for now) copy-assignment\&. "
.ti -1c
.RI "\fBcint\fP \fBstartWriter\fP (\fBvoid\fP)"
.br
.RI "Starts the log-writing thread\&. "
.ti -1c
.RI "\fBcint\fP \fBstopWriter\fP (\fBvoid\fP)"
.br
.RI "Stops the log-writing thread (after flushing the log queue)\&. "
.ti -1c
.RI "\fBcint\fP \fBopenLog\fP (\fBconst\fP std::string_view \fBfname\fP, \fBconst\fP bool \fBclearLog\fP=\fBfalse\fP)"
.br
.RI "Open the file to start logging\&. "
.ti -1c
.RI "\fBcint\fP \fBopenLog\fP (\fBconst\fP std::string_view \fBfpath\fP, \fBconst\fP std::string_view \fBfname\fP, \fBconst\fP bool \fBclearLog\fP=\fBfalse\fP)"
.br
.RI "Open the file to start logging\&. "
.ti -1c
.RI "\fBcint\fP \fBcloseLog\fP (\fBvoid\fP)"
.br
.RI "Close the file, if it was opened\&. "
.ti -1c
.RI "\fBcint\fP \fBwriteToLog\fP (\fBconst\fP std::string_view \fBlogmessg\fP, \fBconst\fP \fBcint\fP \fBlogtype\fP=\fBAELOG_TYPE_INFO\fP, \fBconst\fP std::string_view \fBlogmodule\fP=\fBAELOG_DEFAULT_MODULE_NAME\fP)"
.br
.RI "Request a log entry to be written to the opened log file\&. "
.ti -1c
.RI "\fBcint\fP \fBwriteToLog\fP (\fBconst\fP \fBAELogEntry\fP &\fBentry\fP, \fBconst\fP bool \fBuseCurrentTime\fP=\fBtrue\fP)"
.br
.RI "Request a log entry to be written to the opened log file, using data from a log entry type\&. "
.ti -1c
.RI "\fBcint\fP \fBwriteToLogDebug\fP (\fBconst\fP std::string_view \fBlogmessg\fP, \fBconst\fP std::string_view \fBlogmodule\fP=\fBAELOG_DEFAULT_MODULE_NAME\fP)"
.br
.RI "Request a debug log entry to be written to the opened log file\&. "
.ti -1c
.RI "\fBcint\fP \fBwriteStatus\fP (\fBvoid\fP)"
.br
.RI "Writes the current status of the file logger instance (file name, and entries written)\&. "
.ti -1c
.RI "std::string \fBgetLogName\fP (\fBvoid\fP) \fBconst\fP \fBnoexcept\fP"
.br
.RI "Get the name of the log file\&. "
.ti -1c
.RI "std::string \fBgetLogPath\fP (\fBvoid\fP) \fBconst\fP"
.br
.RI "Get the path of the log file\&. "
.ti -1c
.RI "std::string \fBgetLogAbsolutePath\fP (\fBvoid\fP) \fBconst\fP"
.br
.RI "Get the full/absolute path of the log file\&. "
.ti -1c
.RI "\fBullint\fP \fBgetEntryCount\fP (\fBvoid\fP) \fBconst\fP \fBnoexcept\fP"
.br
.RI "Get the amount of log entries done to an opened log file\&. "
.ti -1c
.RI "bool \fBisOpen\fP (\fBvoid\fP) \fBconst\fP \fBnoexcept\fP"
.br
.RI "Checks if the current log file is open\&. "
.ti -1c
.RI "bool \fBisClosed\fP (\fBvoid\fP) \fBconst\fP \fBnoexcept\fP"
.br
.RI "Checks if a log file isn't open by this logger\&. "
.ti -1c
.RI "bool \fBisWriting\fP (\fBvoid\fP) \fBconst\fP \fBnoexcept\fP"
.br
.RI "Checks if the log-writing thread is running\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP std::string \fBgenLogName\fP (\fBconst\fP std::string_view \fBlogpath\fP, \fBconst\fP std::string_view \fBlogpref\fP, \fBconst\fP std::string_view \fBlogext\fP='\&.log')"
.br
.RI "Creates a full name of the log file to open to be fed to the logger, in a format [prefix]_[current date][\&.extension] in a given directory\&. "
.ti -1c
.RI "\fBstatic\fP \fBullint\fP \fBgetModuleAmount\fP (\fBvoid\fP) \fBnoexcept\fP"
.br
.RI "Returns the amount of instances of the module currently existing\&. "
.ti -1c
.RI "\fBstatic\fP std::string_view \fBgetModuleName\fP (\fBvoid\fP) \fBnoexcept\fP"
.br
.RI "Returns the name of the registered module\&. "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP std::string_view \fBm_sModulename\fP"
.br
.RI "Name of the module (class), same as in code\&. "
.ti -1c
.RI "\fBstatic\fP std::atomic< \fBullint\fP > \fBm_ullModulesAlive\fP"
.br
.RI "Amount of alive module instances\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBAELogEntry\fP * \fBptrFromIndex\fP (\fBullint\fP \fBnum\fP) \fBnoexcept\fP"
.br
.RI "Checks for the given index number and returns the pointer in the queue of log entries\&. "
.ti -1c
.RI "\fBvoid\fP \fBlogWriterThread\fP (\fBvoid\fP)"
.br
.RI "The function of the log writing thread to\&.\&.\&.read the entries, format them, write them, and clear them\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAEFileWriter\fP \fBm_fwLogger\fP"
.br
.RI "The file writer to actually write text to opened log file\&. "
.ti -1c
.RI "std::mutex \fBm_mtxAllocLock\fP"
.br
.RI "The mutex to lock when allocating new queue chunks\&. "
.ti -1c
.RI "std::vector< std::pair< \fBullint\fP, \fBAELogEntry\fP * > > \fBm_vAllocTable\fP"
.br
.RI "The vector to all the allocated queue pieces and total amounts allocated\&. "
.ti -1c
.RI "std::thread \fBm_trdWriter\fP"
.br
.RI "The thread object for the file writing thread to\&.\&.\&.write a log file separately\&. "
.ti -1c
.RI "std::atomic< \fBullint\fP > \fBm_ullFilledCount\fP"
.br
.RI "The amount of nodes filled (should we allocate more?) "
.ti -1c
.RI "std::atomic< \fBullint\fP > \fBm_ullNodeNumber\fP"
.br
.RI "The current node number the writeToLog is working with\&. "
.ti -1c
.RI "\fBullint\fP \fBm_ullQueueSize\fP"
.br
.RI "The amount of entry spaces/size of the queue\&. "
.ti -1c
.RI "\fBAELogEntry\fP * \fBm_lepQueue\fP"
.br
.RI "The pointer to the first item in the queue\&. "
.ti -1c
.RI "\fBAELogEntry\fP * \fBm_lepLastNode\fP"
.br
.RI "The pointer to the last item in the queue\&. "
.ti -1c
.RI "std::atomic< bool > \fBm_bRunTrd\fP"
.br
.RI "The flag to run the log-writing thread\&. "
.ti -1c
.RI "std::atomic< bool > \fBm_bQueueFilled\fP"
.br
.RI "The flag to show that the queue is populated\&. "
.in -1c
.SH "Detailed Description"
.PP 
The ArtyK's Engine's Logger module -- it manages the writing to the log files\&. 

A wrapper around AEFW functionality for writing, and \fBAELogEntry\fP for mass-formatting of entries to text
.PP
The log is written by requesting and filling the entry in the queue\&. The \fBAELogger\fP instance launches the separate thread that looks at the entries in the queue, retrieves and formats the data in them, and writes it to the file\&. Afterwards that entry in the queue is cleared\&.
.PP
Hungarian notation is lg\&. (m_lgMyLogger)
.PP
\fBTodo\fP
.RS 4
Implement copy constructors and copy assignment 
.PP
Add the ability to open the same log file/redirect the instance requests to the one that has it open first\&. 
.RE
.PP
\fBBug\fP
.RS 4
The queue can expand if it's too little\&. But\&.\&.\&.\&.I don't know how to shrink it\&. (working on it) 
.RE
.PP

.PP
Definition at line \fB68\fP of file \fBAELogger\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AELogger::AELogger (\fBconst\fP std::string_view fname, \fBconst\fP bool clearLog = \fC\fBfalse\fP\fP, \fBconst\fP \fBullint\fP queuesize = \fC\fBAELOG_DEFAULT_QUEUE_SIZE\fP\fP)\fC [explicit]\fP"

.PP
Class constructor -- it opens the file with the given name and starts logging to it\&. 
.PP
\fBParameters\fP
.RS 4
\fIfname\fP Name of the log file
.br
\fIclearLog\fP Flag to clear the log file if it exists instead of appending it
.br
\fIqueuesize\fP The size of the queue to create when creating \fBAELogger\fP instance
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBAELogger\&.cpp\fP\&.
.SS "AELogger::AELogger (\fBconst\fP std::string_view logpath, \fBconst\fP std::string_view fname, \fBconst\fP bool clearLog = \fC\fBfalse\fP\fP, \fBconst\fP \fBullint\fP queuesize = \fC\fBAELOG_DEFAULT_QUEUE_SIZE\fP\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Class constructor -- it opens the file with the given path and name and start logging to it\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogpath\fP The path of the log file to open it in
.br
\fIfname\fP Name of the log file
.br
\fIclearLog\fP Flag to clear the log file if it exists instead of appending it
.br
\fIqueuesize\fP The size of the queue to create when creating \fBAELogger\fP instance
.RE
.PP

.PP
Definition at line \fB88\fP of file \fBAELogger\&.hpp\fP\&.
.SS "AELogger::AELogger (\fBvoid\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Default class constructor -- doesn't open the file, but setups the instance for one\&. 
.PP
Definition at line \fB94\fP of file \fBAELogger\&.hpp\fP\&.
.SS "AELogger::~AELogger (\fBvoid\fP)"

.PP
Class destructor\&. 
.PP
Definition at line \fB41\fP of file \fBAELogger\&.cpp\fP\&.
.SS "AELogger::AELogger (\fBconst\fP \fBAELogger\fP &)\fC [delete]\fP"

.PP
Deleted (for now) copy-constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBcint\fP AELogger::closeLog (\fBvoid\fP)\fC [inline]\fP"

.PP
Close the file, if it was opened\&. That's it\&.
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, 
.RE
.PP

.PP
Definition at line \fB162\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBstatic\fP std::string AELogger::genLogName (\fBconst\fP std::string_view logpath, \fBconst\fP std::string_view logpref, \fBconst\fP std::string_view logext = \fC'\&.log'\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Creates a full name of the log file to open to be fed to the logger, in a format [prefix]_[current date][\&.extension] in a given directory\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogpath\fP The path of the log file
.br
\fIlogpref\fP The prefix of log file
.br
\fIlogext\fP The extension of the log file\&. Include the period before the extension\&.
.RE
.PP
\fBReturns\fP
.RS 4
std::string of the file name to feed to the logger for opening
.RE
.PP

.PP
Definition at line \fB281\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBullint\fP AELogger::getEntryCount (\fBvoid\fP) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Get the amount of log entries done to an opened log file\&. 
.PP
\fBReturns\fP
.RS 4
ullint of the amount of times logger written to a file
.RE
.PP

.PP
Definition at line \fB246\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::string AELogger::getLogAbsolutePath (\fBvoid\fP) const\fC [inline]\fP"

.PP
Get the full/absolute path of the log file\&. 
.PP
\fBReturns\fP
.RS 4
std::string of the absolute path of the opened log file; otherwise values from \fBAEFileWriter::getFullPath()\fP
.RE
.PP

.PP
Definition at line \fB238\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::string AELogger::getLogName (\fBvoid\fP) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Get the name of the log file\&. 
.PP
\fBReturns\fP
.RS 4
std::string of the name of opened log file; otherwise values from \fBAEFileWriter::getFullFileName()\fP
.RE
.PP

.PP
Definition at line \fB222\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::string AELogger::getLogPath (\fBvoid\fP) const\fC [inline]\fP"

.PP
Get the path of the log file\&. 
.PP
\fBReturns\fP
.RS 4
std::string of the path of the opened log file; otherwise values from \fBAEFileWriter::getRelativePath()\fP
.RE
.PP

.PP
Definition at line \fB230\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBstatic\fP \fBullint\fP \fB__AEModuleBase\fP< \fBAELogger\fP  >::getModuleAmount (\fBvoid\fP)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP, \fC [inherited]\fP"

.PP
Returns the amount of instances of the module currently existing\&. 
.PP
\fBReturns\fP
.RS 4
Unsigned long long of the module amount
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "\fBstatic\fP std::string_view \fB__AEModuleBase\fP< \fBAELogger\fP  >::getModuleName (\fBvoid\fP)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP, \fC [inherited]\fP"

.PP
Returns the name of the registered module\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB85\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "bool AELogger::isClosed (\fBvoid\fP) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Checks if a log file isn't open by this logger\&. 
.PP
\fBReturns\fP
.RS 4
True if log file is closed/not open, false if otherwise
.RE
.PP

.PP
Definition at line \fB262\fP of file \fBAELogger\&.hpp\fP\&.
.SS "bool AELogger::isOpen (\fBvoid\fP) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Checks if the current log file is open\&. 
.PP
\fBReturns\fP
.RS 4
True if the file is open for writing, false otherwise
.RE
.PP

.PP
Definition at line \fB254\fP of file \fBAELogger\&.hpp\fP\&.
.SS "bool AELogger::isWriting (\fBvoid\fP) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Checks if the log-writing thread is running\&. 
.PP
\fBReturns\fP
.RS 4
True if it is \fBworking(was launched)\fP, false otherwise
.RE
.PP

.PP
Definition at line \fB270\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBvoid\fP AELogger::logWriterThread (\fBvoid\fP)\fC [private]\fP"

.PP
The function of the log writing thread to\&.\&.\&.read the entries, format them, write them, and clear them\&. 
.PP
Definition at line \fB184\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::openLog (\fBconst\fP std::string_view fname, \fBconst\fP bool clearLog = \fC\fBfalse\fP\fP)\fC [inline]\fP"

.PP
Open the file to start logging\&. 
.PP
\fBParameters\fP
.RS 4
\fIfname\fP Name of the log file
.br
\fIclearLog\fP Flag to clear the log file if it exists instead of appending it
.RE
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise return values of \fBAEFileWriter::openFile()\fP or \fBAELogger::startWriter()\fP
.RE
.PP

.PP
Definition at line \fB138\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBcint\fP AELogger::openLog (\fBconst\fP std::string_view fpath, \fBconst\fP std::string_view fname, \fBconst\fP bool clearLog = \fC\fBfalse\fP\fP)\fC [inline]\fP"

.PP
Open the file to start logging\&. 
.PP
\fBParameters\fP
.RS 4
\fIfpath\fP Path of directory to put the log file in (include trailing '/' character)
.br
\fIfname\fP Name of the log file
.br
\fIclearLog\fP Flag to clear the log file if it exists instead of appending it
.RE
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise return values of \fBAEFileWriter::openFile()\fP or \fBAELogger::startWriter()\fP
.RE
.PP

.PP
Definition at line \fB154\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBAELogger\fP & AELogger::operator= (\fBconst\fP \fBAELogger\fP &)\fC [delete]\fP"

.PP
Deleted (for now) copy-assignment\&. 
.SS "\fBAELogEntry\fP * AELogger::ptrFromIndex (\fBullint\fP num)\fC [private]\fP, \fC [noexcept]\fP"

.PP
Checks for the given index number and returns the pointer in the queue of log entries\&. 
.PP
\fBNote\fP
.RS 4
The index is wrapped around the max queue size\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fInum\fP The index number of the log entry
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the node of that index
.RE
.PP

.PP
Definition at line \fB254\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::startWriter (\fBvoid\fP)"

.PP
Starts the log-writing thread\&. 
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AELOG_ERR_THREAD_ALREADY_RUNNING if thread already was running, AELOG_ERR_UNABLE_START_THREAD if error happened (+ std::runtime_error() exception)
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::stopWriter (\fBvoid\fP)"

.PP
Stops the log-writing thread (after flushing the log queue)\&. 
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AELOG_ERR_THREAD_ALREADY_STOPPED if thread already was stopped
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::writeStatus (\fBvoid\fP)\fC [inline]\fP"

.PP
Writes the current status of the file logger instance (file name, and entries written)\&. 
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
.RE
.PP

.PP
Definition at line \fB212\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBcint\fP AELogger::writeToLog (\fBconst\fP \fBAELogEntry\fP & entry, \fBconst\fP bool useCurrentTime = \fC\fBtrue\fP\fP)"

.PP
Request a log entry to be written to the opened log file, using data from a log entry type\&. 
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The log entry to write to the file
.br
\fIuseCurrentTime\fP Flag to use current time for the log entry, or use timestamp in the provided entry
.RE
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::writeToLog (\fBconst\fP std::string_view logmessg, \fBconst\fP \fBcint\fP logtype = \fC\fBAELOG_TYPE_INFO\fP\fP, \fBconst\fP std::string_view logmodule = \fC\fBAELOG_DEFAULT_MODULE_NAME\fP\fP)"

.PP
Request a log entry to be written to the opened log file\&. 
.PP
\fBNote\fP
.RS 4
See AELOG_TYPE_* flags 
.PP
The module name should contain only alphanumeric characters or underscores (no spaces), otherwise it fails
.RE
.PP
\fBParameters\fP
.RS 4
\fIlogmessg\fP The message of the requested log entry
.br
\fIlogtype\fP The type of the log entry
.br
\fIlogmodule\fP The name of the module that invoked this request
.RE
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
.RE
.PP

.PP
\fBTodo\fP
.RS 4
Implement decrease in log queue size\&.\&.\&.somehow 
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBAELogger\&.cpp\fP\&.
.SS "\fBcint\fP AELogger::writeToLogDebug (\fBconst\fP std::string_view logmessg, \fBconst\fP std::string_view logmodule = \fC\fBAELOG_DEFAULT_MODULE_NAME\fP\fP)\fC [inline]\fP"

.PP
Request a debug log entry to be written to the opened log file\&. 
.PP
\fBNote\fP
.RS 4
See AELOG_TYPE_* flags 
.PP
If ENGINE_DEBUG flag is not set, doesn't do anything 
.RE
.PP
\fBSee also\fP
.RS 4
\fBAELogger::writeToLog()\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIlogmessg\fP The message of the requested log entry
.br
\fIlogmodule\fP The name of the module that invoked this request
.RE
.PP
\fBReturns\fP
.RS 4
AELOG_ERR_NOERROR on success; otherwise AEFW_ERR_FILE_NOT_OPEN if log file isn't open, AELOG_ERR_INVALID_ENTRY_DATA if passed data isn't of proper format
.RE
.PP

.PP
Definition at line \fB202\fP of file \fBAELogger\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::atomic<bool> AELogger::m_bQueueFilled\fC [private]\fP"

.PP
The flag to show that the queue is populated\&. 
.PP
Definition at line \fB327\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::atomic<bool> AELogger::m_bRunTrd\fC [private]\fP"

.PP
The flag to run the log-writing thread\&. 
.PP
Definition at line \fB325\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBAEFileWriter\fP AELogger::m_fwLogger\fC [private]\fP"

.PP
The file writer to actually write text to opened log file\&. 
.PP
Definition at line \fB306\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBAELogEntry\fP* AELogger::m_lepLastNode\fC [private]\fP"

.PP
The pointer to the last item in the queue\&. 
.PP
Definition at line \fB322\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBAELogEntry\fP* AELogger::m_lepQueue\fC [private]\fP"

.PP
The pointer to the first item in the queue\&. 
.PP
Definition at line \fB320\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::mutex AELogger::m_mtxAllocLock\fC [private]\fP"

.PP
The mutex to lock when allocating new queue chunks\&. 
.PP
Definition at line \fB308\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBconst\fP std::string_view \fB__AEModuleBase\fP< \fBAELogger\fP  >::m_sModulename\fC [static]\fP, \fC [protected]\fP, \fC [inherited]\fP"

.PP
Name of the module (class), same as in code\&. Sets up the static variable values for the base class (and inherited classes)
.PP
\fBTodo\fP
.RS 4
Find a way to make it constexpr and compile-time evaluated 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "std::thread AELogger::m_trdWriter\fC [private]\fP"

.PP
The thread object for the file writing thread to\&.\&.\&.write a log file separately\&. 
.PP
Definition at line \fB312\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::atomic<\fBullint\fP> AELogger::m_ullFilledCount\fC [private]\fP"

.PP
The amount of nodes filled (should we allocate more?) 
.PP
Definition at line \fB314\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::atomic<\fBullint\fP> \fB__AEModuleBase\fP< \fBAELogger\fP  >::m_ullModulesAlive\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP, \fC [inherited]\fP"

.PP
Amount of alive module instances\&. 
.PP
Definition at line \fB99\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "std::atomic<\fBullint\fP> AELogger::m_ullNodeNumber\fC [private]\fP"

.PP
The current node number the writeToLog is working with\&. 
.PP
Definition at line \fB316\fP of file \fBAELogger\&.hpp\fP\&.
.SS "\fBullint\fP AELogger::m_ullQueueSize\fC [private]\fP"

.PP
The amount of entry spaces/size of the queue\&. 
.PP
Definition at line \fB318\fP of file \fBAELogger\&.hpp\fP\&.
.SS "std::vector<std::pair<\fBullint\fP, \fBAELogEntry\fP*> > AELogger::m_vAllocTable\fC [private]\fP"

.PP
The vector to all the allocated queue pieces and total amounts allocated\&. 
.PP
Definition at line \fB310\fP of file \fBAELogger\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
