.TH "AELogger/src/AELogger.cpp" 3 "Fri Feb 2 2024 00:44:14" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogger/src/AELogger.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/AELogger\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
This file contains the definitions of the engine's logger's functions\&. 
.PP
\fBSee also\fP
.RS 4
\fBAELogger\fP 
.PP
\fBAELogger\&.hpp\fP
.RE
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogger\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
