.TH "AELogEntry" 3 "Fri Jan 12 2024 01:05:42" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogEntry \- The structure for the data of the log entry to be manipulated with the log files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AELogEntry\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAELogEntry\fP & \fBoperator=\fP (\fBconst\fP \fBAELogEntry\fP &\fBentry\fP)"
.br
.RI "Copy assignment operator -- copies data from the passed node\&. "
.ti -1c
.RI "\fBvoid\fP \fBcopyEntryFull\fP (\fBconst\fP \fBAELogEntry\fP &\fBentry\fP) \fBnoexcept\fP"
.br
.RI "Makes a full copy of the log entry, including the pointer to the next node\&. "
.ti -1c
.RI "\fBvoid\fP \fBcopyEntry\fP (\fBconst\fP \fBAELogEntry\fP &\fBentry\fP) \fBnoexcept\fP"
.br
.RI "Makes a normal copy of the log entry, copying everything but the pointer to the next node\&. "
.ti -1c
.RI "\fBvoid\fP \fBcopyEntryReduced\fP (\fBconst\fP \fBAELogEntry\fP &\fBentry\fP) \fBnoexcept\fP"
.br
.RI "Makes a reduced copy of the log entry, including only the message, module name, and type\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBclearEntry\fP (\fBAELogEntry\fP &\fBentry\fP) \fBnoexcept\fP"
.br
.RI "Clears the current entry and sets its values to zero/invalid\&. "
.ti -1c
.RI "\fBstatic\fP \fBAELogEntry\fP * \fBmakeQueue\fP (\fBconst\fP std::size_t \fBamt\fP, \fBAELogEntry\fP *\fBoldqueue\fP=\fBnullptr\fP, \fBconst\fP bool \fBloopQueue\fP=\fBtrue\fP)"
.br
.RI "Allocates the queue of the given size on the heap and returns the pointer to it's first node\&. "
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBformatEntry\fP (char *\fBconst\fP \fBstr\fP, \fBconst\fP \fBAELogEntry\fP &\fBentry\fP) \fBnoexcept\fP"
.br
.RI "Formats the passed entry to the given c-string\&. "
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBconst\fP char * \fBtypeToString\fP (\fBconst\fP \fBcint\fP \fBlogtype\fP) \fBnoexcept\fP"
.br
.RI "Deduces the entry's log type and returns a c-string of it\&. "
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBcint\fP \fBstringToType\fP (\fBconst\fP std::string_view \fBstr\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBcint\fP \fBparseStringEntry\fP (\fBAELogEntry\fP &\fBentry\fP, \fBconst\fP std::string_view \fBentryString\fP, \fBconst\fP \fBcint\fP \fBflags\fP=0b0001111)"
.br
.RI "Parses a given string as a log entry, and write it into passed entry object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBm_sLogMessage\fP [\fBAELE_MESSAGE_SIZE\fP+1] {}"
.br
.RI "The message of the log entry\&. "
.ti -1c
.RI "char \fBm_sModuleName\fP [\fBAELE_MODULENAME_SIZE\fP+1] {}"
.br
.RI "The name of the module that issued the log entry\&. "
.ti -1c
.RI "std::time_t \fBm_tmLogTime\fP = \fBNULL\fP"
.br
.RI "The time when this log entry was created\&. "
.ti -1c
.RI "\fBAELogEntry\fP * \fBm_pNextNode\fP = \fBnullptr\fP"
.br
.RI "The pointer to the next log entry in the queue\&. "
.ti -1c
.RI "\fBcint\fP \fBm_cLogType\fP = \-1"
.br
.RI "The type of the log entry\&. "
.ti -1c
.RI "std::atomic< \fBcint\fP > \fBm_cStatus\fP = 0"
.br
.RI "The status flag in the entry to show if the entry is ready, being read/set, or is invalid\&. "
.in -1c
.SH "Detailed Description"
.PP 
The structure for the data of the log entry to be manipulated with the log files\&. 

The flags start with AELE_ 
.PP
Definition at line \fB82\fP of file \fBAELogEntry\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP AELogEntry::clearEntry (\fBAELogEntry\fP & entry)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Clears the current entry and sets its values to zero/invalid\&. 
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The entry to clear
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBvoid\fP AELogEntry::copyEntry (\fBconst\fP \fBAELogEntry\fP & entry)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Makes a normal copy of the log entry, copying everything but the pointer to the next node\&. 
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The entry to copy data from
.RE
.PP

.PP
Definition at line \fB124\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBvoid\fP AELogEntry::copyEntryFull (\fBconst\fP \fBAELogEntry\fP & entry)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Makes a full copy of the log entry, including the pointer to the next node\&. 
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The entry to copy data from
.RE
.PP

.PP
Definition at line \fB115\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBvoid\fP AELogEntry::copyEntryReduced (\fBconst\fP \fBAELogEntry\fP & entry)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Makes a reduced copy of the log entry, including only the message, module name, and type\&. 
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The entry to copy data from
.RE
.PP

.PP
Definition at line \fB134\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBstatic\fP \fBvoid\fP AELogEntry::formatEntry (char *\fBconst\fP str, \fBconst\fP \fBAELogEntry\fP & entry)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Formats the passed entry to the given c-string\&. 
.PP
\fBNote\fP
.RS 4
The size of the c-string must be of AELE_FORMAT_MAX_SIZE !
.RE
.PP
\fBParameters\fP
.RS 4
\fIstr\fP The c-string to format the data to
.br
\fIentry\fP The entry object to format its data to string
.RE
.PP

.PP
Definition at line \fB192\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBstatic\fP \fBAELogEntry\fP * AELogEntry::makeQueue (\fBconst\fP std::size_t amt, \fBAELogEntry\fP * oldqueue = \fC\fBnullptr\fP\fP, \fBconst\fP bool loopQueue = \fC\fBtrue\fP\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Allocates the queue of the given size on the heap and returns the pointer to it's first node\&. Optionally may loop the newly-allocated queue to the old queue\&. 
.PP
\fBNote\fP
.RS 4
You should delete[] the pointer after you're done using it (unless you like mem-leaks) 
.PP
If the amt is 0, throws the std::runtime exception
.RE
.PP
\fBParameters\fP
.RS 4
\fIamt\fP The amount of entries in the queue(size)
.br
\fIoldqueue\fP The pointer to the old queue to loop the new queue to\&.
.br
\fIloopQueue\fP The flag to indicate whether to loop the generated queue at all
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the first node of the allocated queue
.RE
.PP

.PP
Definition at line \fB159\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBAELogEntry\fP & AELogEntry::operator= (\fBconst\fP \fBAELogEntry\fP & entry)\fC [inline]\fP"

.PP
Copy assignment operator -- copies data from the passed node\&. 
.PP
\fBNote\fP
.RS 4
The pointer to the next node is omitted from the operation; 
.PP
Uses the \fBAELogEntry::copyEntry()\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIentry\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB106\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBstatic\fP \fBcint\fP AELogEntry::parseStringEntry (\fBAELogEntry\fP & entry, \fBconst\fP std::string_view entryString, \fBconst\fP \fBcint\fP flags = \fC0b0001111\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Parses a given string as a log entry, and write it into passed entry object\&. 
.PP
\fBNote\fP
.RS 4
If the string is less than AELE_FORMAT_MIN_SIZE or more than AELE_FORMAT_MAX_SIZE, fails the check with AELE_ERR_INVALID_LENGTH
.RE
.PP
\fBParameters\fP
.RS 4
\fIentry\fP The log entry object to write data to
.br
\fIentryString\fP The string to parse
.br
\fIflags\fP The flags for parsing\&. Refer to AELE_PARSE_STRING_* (like AELE_PARSE_STRING_JUST_VALIDATE)
.RE
.PP
\fBReturns\fP
.RS 4
AELE_ERR_NOERROR (0) on success, other AELE error flags otherwise
.RE
.PP

.PP
Definition at line \fB260\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBstatic\fP \fBconstexpr\fP \fBcint\fP AELogEntry::stringToType (\fBconst\fP std::string_view str)\fC [inline]\fP, \fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB220\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBstatic\fP \fBconstexpr\fP \fBconst\fP char * AELogEntry::typeToString (\fBconst\fP \fBcint\fP logtype)\fC [inline]\fP, \fC [static]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Deduces the entry's log type and returns a c-string of it\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogtype\fP The value of the log type
.RE
.PP
\fBReturns\fP
.RS 4
c-string of the type
.RE
.PP

.PP
Definition at line \fB210\fP of file \fBAELogEntry\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcint\fP AELogEntry::m_cLogType = \-1"

.PP
The type of the log entry\&. 
.PP
\fBSee also\fP
.RS 4
\fBAELogTypes\&.hpp\fP 
.RE
.PP

.PP
Definition at line \fB94\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "std::atomic<\fBcint\fP> AELogEntry::m_cStatus = 0"

.PP
The status flag in the entry to show if the entry is ready, being read/set, or is invalid\&. 
.PP
Definition at line \fB96\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "\fBAELogEntry\fP* AELogEntry::m_pNextNode = \fBnullptr\fP"

.PP
The pointer to the next log entry in the queue\&. 
.PP
Definition at line \fB91\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "char AELogEntry::m_sLogMessage[\fBAELE_MESSAGE_SIZE\fP+1] {}"

.PP
The message of the log entry\&. 
.PP
Definition at line \fB85\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "char AELogEntry::m_sModuleName[\fBAELE_MODULENAME_SIZE\fP+1] {}"

.PP
The name of the module that issued the log entry\&. 
.PP
Definition at line \fB87\fP of file \fBAELogEntry\&.hpp\fP\&.
.SS "std::time_t AELogEntry::m_tmLogTime = \fBNULL\fP"

.PP
The time when this log entry was created\&. 
.PP
Definition at line \fB89\fP of file \fBAELogEntry\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
