.TH "AELogger/include/AELogger.hpp" 3 "Sat Mar 16 2024 11:28:29" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogger/include/AELogger.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'include/AEFileWriter\&.hpp'\fP
.br
\fR#include 'include/AELogEntry\&.hpp'\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAELogger\fP"
.br
.RI "The ArtyK's Engine's Logger module -- it manages the writing to the log files\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAELOG_ERR_NOERROR\fP   \fBENGINE_MODULE_ERR_NOERROR\fP"
.br
.RI "Macro for the indicator that everything is good/no error was encountered in the process\&. "
.ti -1c
.RI "#define \fBAELOG_ERR_UNABLE_START_THREAD\fP   \-11"
.br
.RI "Macro for the error that's raised when the log-writing-thread cannot be started\&. "
.ti -1c
.RI "#define \fBAELOG_ERR_THREAD_ALREADY_RUNNING\fP   \-12"
.br
.RI "Macro for the error that's raised when the log-writing-thread is attempted to be started again, while it's already running\&. "
.ti -1c
.RI "#define \fBAELOG_ERR_THREAD_ALREADY_STOPPED\fP   \-13"
.br
.RI "Macro for the error that's raised when the log-writing-thread is attempted to be stopped again, while it was already stopped\&. "
.ti -1c
.RI "#define \fBAELOG_ERR_INVALID_ENTRY_DATA\fP   \-14"
.br
.RI "Macro for the error that's raised when invalid data is passed to \fBAELogger::writeToLog()\fP (like empty message, empty/non-alphanumeric module name, type outside of range) "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAELogger\fP \fBglobalLogger\fP (\fBAELogger::genLogName\fP('LOG', '\&.log'))"
.br
.RI "The global logger of the engine to log engine-wide events\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the code for the engine's logger module, err\&.\&.\&.for logging data to file\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogger\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AELOG_ERR_NOERROR   \fBENGINE_MODULE_ERR_NOERROR\fP"

.PP
Macro for the indicator that everything is good/no error was encountered in the process\&. 
.PP
Definition at line \fB35\fP of file \fBAELogger\&.hpp\fP\&.
.SS "#define AELOG_ERR_UNABLE_START_THREAD   \-11"

.PP
Macro for the error that's raised when the log-writing-thread cannot be started\&. 
.PP
Definition at line \fB38\fP of file \fBAELogger\&.hpp\fP\&.
.SS "#define AELOG_ERR_THREAD_ALREADY_RUNNING   \-12"

.PP
Macro for the error that's raised when the log-writing-thread is attempted to be started again, while it's already running\&. 
.PP
Definition at line \fB41\fP of file \fBAELogger\&.hpp\fP\&.
.SS "#define AELOG_ERR_THREAD_ALREADY_STOPPED   \-13"

.PP
Macro for the error that's raised when the log-writing-thread is attempted to be stopped again, while it was already stopped\&. 
.PP
Definition at line \fB44\fP of file \fBAELogger\&.hpp\fP\&.
.SS "#define AELOG_ERR_INVALID_ENTRY_DATA   \-14"

.PP
Macro for the error that's raised when invalid data is passed to \fBAELogger::writeToLog()\fP (like empty message, empty/non-alphanumeric module name, type outside of range) 
.PP
Definition at line \fB47\fP of file \fBAELogger\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBAELogger\fP globalLogger(\fBAELogger::genLogName\fP('LOG', '\&.log')) (\fBAELogger::genLogName\fP('LOG', '\&.log'))\fR [inline]\fP"

.PP
The global logger of the engine to log engine-wide events\&. It starts the writing thread and logging as soon as the program starts\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
