.TH "AECustomTypes/include/AELogEntryInfo.hpp" 3 "Sat Mar 16 2024 12:23:02" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AECustomTypes/include/AELogEntryInfo.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'include/AETypedefs\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAELogEntryInfo\fP"
.br
.RI "The struct that holds the information about the log entry, used by \fBAELogParser\fP\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAELEI_INVALID_CURSOR\fP   \-1"
.br
.RI "Macro for the \fBAELogEntryInfo\fP's value for the invalid cursor index\&. "
.ti -1c
.RI "#define \fBAELEI_INVLAID_MNAME\fP   \-1"
.br
.RI "Macro for the \fBAELogEntryInfo\fP's value for the invalid module name index\&. "
.ti -1c
.RI "#define \fBAELEI_INVALID_TYPE\fP   \-1"
.br
.RI "Macro for the \fBAELogEntryInfo\fP's value for the invalid log type\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the macros for the \fBAELogEntryInfo\fP (and consequently \fBAELogEntry\fP's) log types\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogEntryInfo\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AELEI_INVALID_CURSOR   \-1"

.PP
Macro for the \fBAELogEntryInfo\fP's value for the invalid cursor index\&. 
.PP
Definition at line \fB17\fP of file \fBAELogEntryInfo\&.hpp\fP\&.
.SS "#define AELEI_INVLAID_MNAME   \-1"

.PP
Macro for the \fBAELogEntryInfo\fP's value for the invalid module name index\&. 
.PP
Definition at line \fB19\fP of file \fBAELogEntryInfo\&.hpp\fP\&.
.SS "#define AELEI_INVALID_TYPE   \-1"

.PP
Macro for the \fBAELogEntryInfo\fP's value for the invalid log type\&. 
.PP
Definition at line \fB21\fP of file \fBAELogEntryInfo\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
