.TH "AELogParser/include/AELogParser.hpp" 3 "Thu Jan 11 2024 21:33:35" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogParser/include/AELogParser.hpp \- This file contains the [stuff]\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/AEModuleBase\&.hpp'\fP
.br
\fC#include 'include/AETypedefs\&.hpp'\fP
.br
\fC#include 'include/AEUtils\&.hpp'\fP
.br
\fC#include 'include/AEFileReader\&.hpp'\fP
.br
\fC#include 'include/AELogTypes\&.hpp'\fP
.br
\fC#include 'include/AEFlags\&.hpp'\fP
.br
\fC#include 'include/AELogEntry\&.hpp'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include <string_view>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAELogParser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBAELP_ERR_NOERROR\fP   \fBENGINE_MODULE_ERR_NOERROR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_AELP_INVALID_ENTRY_INDEX\fP   8"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the [stuff]\&. 

This file contains the definitions of the engine's [stuff]\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogParser\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP _AELP_INVALID_ENTRY_INDEX   8"

.PP
Definition at line \fB28\fP of file \fBAELogParser\&.hpp\fP\&.
.SS "#\fBdefine\fP AELP_ERR_NOERROR   \fBENGINE_MODULE_ERR_NOERROR\fP"

.PP
Definition at line \fB25\fP of file \fBAELogParser\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
