.TH "AECustomTypes/include/AELogTypes.hpp" 3 "Fri Jan 12 2024 01:05:06" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AECustomTypes/include/AELogTypes.hpp \- This file contains the macros for the \fBAELogEntry\fP (and consequently \fBAELogger\fP's) log types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_INVALID\fP   \-1"
.br
.RI "Macro for the \fBAELogger\fP's entry of invalid type\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_DEBUG\fP   0"
.br
.RI "Macro for the \fBAELogger\fP's debug entry\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_INFO\fP   1"
.br
.RI "Macro for the \fBAELogger\fP's informational entry\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_WARN\fP   2"
.br
.RI "Macro for the \fBAELogger\fP's warning entry (something isn't right)\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_SEVERE_WARN\fP   3"
.br
.RI "Macro for the \fBAELogger\fP's severe warning entry (something is wrong but it's not an error)\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_OK\fP   4"
.br
.RI "Macro for the \fBAELogger\fP's OK entry (something is good, like a check)\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_SUCCESS\fP   5"
.br
.RI "Macro for the \fBAELogger\fP's successful entry (something done is successfull\&.\&.like a module start)\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_ERROR\fP   6"
.br
.RI "Macro for the \fBAELogger\fP's errorneus entry (something is bad\&.\&.it's an error)\&. "
.ti -1c
.RI "#\fBdefine\fP \fBAELOG_TYPE_FATAL_ERROR\fP   7"
.br
.RI "Macro for the \fBAELogger\fP's fatally-errorenous entry (something critical is fatally-bad)\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the macros for the \fBAELogEntry\fP (and consequently \fBAELogger\fP's) log types\&. 

Please do not touch! (Unless really-really sure) Thank you\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAELogTypes\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP AELOG_TYPE_DEBUG   0"

.PP
Macro for the \fBAELogger\fP's debug entry\&. 
.PP
Definition at line \fB19\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_ERROR   6"

.PP
Macro for the \fBAELogger\fP's errorneus entry (something is bad\&.\&.it's an error)\&. 
.PP
Definition at line \fB37\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_FATAL_ERROR   7"

.PP
Macro for the \fBAELogger\fP's fatally-errorenous entry (something critical is fatally-bad)\&. 
.PP
Definition at line \fB40\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_INFO   1"

.PP
Macro for the \fBAELogger\fP's informational entry\&. 
.PP
Definition at line \fB22\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_INVALID   \-1"

.PP
Macro for the \fBAELogger\fP's entry of invalid type\&. 
.PP
Definition at line \fB16\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_OK   4"

.PP
Macro for the \fBAELogger\fP's OK entry (something is good, like a check)\&. 
.PP
Definition at line \fB31\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_SEVERE_WARN   3"

.PP
Macro for the \fBAELogger\fP's severe warning entry (something is wrong but it's not an error)\&. 
.PP
Definition at line \fB28\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_SUCCESS   5"

.PP
Macro for the \fBAELogger\fP's successful entry (something done is successfull\&.\&.like a module start)\&. 
.PP
Definition at line \fB34\fP of file \fBAELogTypes\&.hpp\fP\&.
.SS "#\fBdefine\fP AELOG_TYPE_WARN   2"

.PP
Macro for the \fBAELogger\fP's warning entry (something isn't right)\&. 
.PP
Definition at line \fB25\fP of file \fBAELogTypes\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
