.TH "AEModuleBase/include/AEModuleBase.hpp" 3 "Thu Mar 14 2024 20:55:55" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEModuleBase/include/AEModuleBase.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'include/AETypedefs\&.hpp'\fP
.br
\fR#include 'include/AEFlags\&.hpp'\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__AEModuleBase< T >\fP"
.br
.RI "This is a base class for all basic modules, meaning that the module is not using other modules to work\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREGISTER_MODULE\fP(T)"
.br
.RI "A process to register the module (that inherited from \fB__AEModuleBase\fP) (under the hood: finish specialising \fB__AEModuleBase::getModuleName()\fP specially for the inheriting class) Usage: Always put it as the \fBlast\fP entry to the class, before the closing brace }\&. "
.ti -1c
.RI "#define \fBCOPYCONSTRUCT_MODULE\fP(T,  val)   \fB__AEModuleBase\fP<T>(val)"
.br
.RI "A process to correctly copy-construct the module (that inherited from \fB__AEModuleBase\fP) (under the hood: calls the copy-constructor of the \fB__AEModuleBase\fP) Usage: put it as the first item of the initializer list Example: TestClass(const TestClass& val) : \fBCOPYCONSTRUCT_MODULE(T, val)\fP, [other member initialisation] {\&.\&.\&.}\&. "
.ti -1c
.RI "#define \fBENGINE_MODULE_ERR_NOERROR\fP   0"
.br
.RI "Global 'no error' return flag for all engine modules\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the code for the module that all (utility) modules base on in the ArtyK's Console Engine class\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAEModuleBase\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define REGISTER_MODULE(T)"
\fBValue:\fP.PP
.nf
    public: [[nodiscard]] static constexpr std::string_view getModuleName(void) noexcept { \\
    static_assert(sizeof(#T) <= AELE_MODULENAME_SIZE, "The module name is TOO BIG! (check AELE_MODULENAME_SIZE in AEMisc/include/AEFlags\&.hpp"); \\
    return #T; }
.fi

.PP
A process to register the module (that inherited from \fB__AEModuleBase\fP) (under the hood: finish specialising \fB__AEModuleBase::getModuleName()\fP specially for the inheriting class) Usage: Always put it as the \fBlast\fP entry to the class, before the closing brace }\&. 
.PP
\fBWarning\fP
.RS 4
If you won't do it, the project won't compile with the 'unresolved external' error 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Inheriting module's class name
.RE
.PP
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "#define COPYCONSTRUCT_MODULE(T, val)   \fB__AEModuleBase\fP<T>(val)"

.PP
A process to correctly copy-construct the module (that inherited from \fB__AEModuleBase\fP) (under the hood: calls the copy-constructor of the \fB__AEModuleBase\fP) Usage: put it as the first item of the initializer list Example: TestClass(const TestClass& val) : \fBCOPYCONSTRUCT_MODULE(T, val)\fP, [other member initialisation] {\&.\&.\&.}\&. 
.PP
\fBWarning\fP
.RS 4
If you won't do it, the module count (done by \fB__AEModuleBase\fP) won't be incremented 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Inheriting module's class name
.br
\fIval\fP The name of the argument to be copy-constructed from
.RE
.PP
.RE
.PP

.PP
Definition at line \fB35\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "#define ENGINE_MODULE_ERR_NOERROR   0"

.PP
Global 'no error' return flag for all engine modules\&. 
.PP
Definition at line \fB38\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
