.TH "AETimer" 3 "Mon Mar 18 2024 18:44:24" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AETimer \- ArtyK's Engine Timer -- the engine's internal timer for, um, timing events or anything, with variable tick speed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AETimer\&.hpp>\fP
.PP
Inherits \fB__AEModuleBase< AETimer >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAETimer\fP (const double tps=\fBENGINE_FPS\fP)"
.br
.RI "Class constructor -- starts the timer automatically\&. "
.ti -1c
.RI "\fBAETimer\fP (void) noexcept"
.br
.RI "Class constructor -- just assigns default delay (ENGINE_FPS) and doesn't start the thread\&. "
.ti -1c
.RI "\fBAETimer\fP (const \fBAETimer\fP &tm)"
.br
.RI "Copy constructor -- Just copies the data and then starts the timer if original timer was started\&. "
.ti -1c
.RI "\fBAETimer\fP & \fBoperator=\fP (const \fBAETimer\fP &tm)"
.br
.RI "The copy assignment operator\&. "
.ti -1c
.RI "\fB~AETimer\fP (void)"
.br
.RI "Class destructor\&. "
.ti -1c
.RI "void \fBstartThread\fP (void)"
.br
.RI "Starts the timer thread and starts tick counting\&. "
.ti -1c
.RI "void \fBstopThread\fP (void)"
.br
.RI "Stops the timer thread and stops tick counting\&. "
.ti -1c
.RI "void \fBresetTick\fP (void) noexcept"
.br
.RI "Resets the timer's tick to 0\&. "
.ti -1c
.RI "void \fBsetTick\fP (const \fBullint\fP tick) noexcept"
.br
.RI "Sets the new tick value instead of the current\&. "
.ti -1c
.RI "void \fBsetDelay\fP (const double tps)"
.br
.RI "Sets the new delay instead of the current\&. "
.ti -1c
.RI "\fBullint\fP \fBgetTick\fP (void) const noexcept"
.br
.RI "Returns the current tick of the timer\&. "
.ti -1c
.RI "long double \fBgetWorldTime\fP (void) const noexcept"
.br
.RI "Calculates the approximate world time of the timer in seconds (from the ticks) "
.ti -1c
.RI "double \fBgetFrameRate\fP (void) const noexcept"
.br
.RI "Returns the fps goal of \fBAEFrame\fP instance in the \fBAETimer\fP\&. "
.ti -1c
.RI "double \fBgetDelay\fP (void) const noexcept"
.br
.RI "Returns the maximum \fBAEFrame\fP's instance in the \fBAETimer\fP delay from the set fps, in seconds\&. "
.ti -1c
.RI "constexpr const \fBullint\fP \fBgetModuleID\fP (void) noexcept"
.br
.RI "Get the \fBid number of the instance\fP of the module\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBwaitForTick\fP (const \fBAETimer\fP &timer, const \fBullint\fP tick) noexcept"
.br
.RI "Stops and sleeps the thread untill the given timer hits the certain tick number\&. "
.ti -1c
.RI "static void \fBwaitTicks\fP (const \fBAETimer\fP &timer, const \fBullint\fP tick) noexcept"
.br
.RI "Stops and sleeps the thread untill the given timer goes through certain tick amount\&. "
.ti -1c
.RI "static \fBullint\fP \fBgetModuleAmount\fP (void) noexcept"
.br
.RI "Get the \fBamount of the currently-alive instances of module T\fP\&. "
.ti -1c
.RI "static constexpr const std::string_view \fBgetModuleName\fP (void) noexcept"
.br
.RI "Get the \fBname of the module\fP\&. "
.ti -1c
.RI "static constexpr const \fBullint\fP \fBgetInstanceCounter\fP (void) noexcept"
.br
.RI "Get the current value of the \fBinstance counter\fP of the module\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBullint\fP \fBm_ullModuleId\fP"
.br
.RI "The ID number of the current module\&. "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static std::atomic< std::size_t > \fBm_ullModulesAlive\fP"
.br
.RI "Amount of the currently-alive (not destroyed) instances of the module\&. "
.ti -1c
.RI "static std::atomic< \fBullint\fP > \fBm_ullInstanceCounter\fP"
.br
.RI "Amount of the instances of the module ever created during the program's runtime\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBtickTimer\fP (void) noexcept"
.br
.RI "The function that does the tick counting for the timer\&. "
.ti -1c
.RI "\fBREGISTER_MODULE\fP (\fBAETimer\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAEFrame\fP \fBm_rDelay\fP"
.br
.RI "The frame-rater of the timer for proper delay in the tick-counting function loop\&. "
.ti -1c
.RI "std::thread \fBm_trdCounting\fP"
.br
.RI "The thread that does the tick counting\&. "
.ti -1c
.RI "std::atomic< \fBullint\fP > \fBm_ullTicks\fP"
.br
.RI "The tick count variable\&. "
.ti -1c
.RI "std::atomic< bool > \fBm_bRunTrd\fP"
.br
.RI "The flag to continue running the tick counting loop\&. "
.in -1c
.SH "Detailed Description"
.PP 
ArtyK's Engine Timer -- the engine's internal timer for, um, timing events or anything, with variable tick speed\&. 

It makes a separate thread that increments the tick number every set time period\&. For the delay, it uses \fBAEFrame\fP\&.
.PP
Just create it and look at the ticks of the timer from anywhere in the program\&.\&.\&.that you can access it\&. Hungarian notation is tm\&. (m_tmMyTimer) 
.PP
Definition at line \fB26\fP of file \fBAETimer\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AETimer::AETimer (const double tps = \fR\fBENGINE_FPS\fP\fP)\fR [inline]\fP, \fR [explicit]\fP"

.PP
Class constructor -- starts the timer automatically\&. 
.PP
\fBParameters\fP
.RS 4
\fItps\fP The amount of ticks per second, as the float
.RE
.PP

.PP
Definition at line \fB35\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBstartThread()\fP\&.
.SS "AETimer::AETimer (void)\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Class constructor -- just assigns default delay (ENGINE_FPS) and doesn't start the thread\&. 
.PP
Definition at line \fB43\fP of file \fBAETimer\&.hpp\fP\&.
.SS "AETimer::AETimer (const \fBAETimer\fP & tm)\fR [inline]\fP"

.PP
Copy constructor -- Just copies the data and then starts the timer if original timer was started\&. 
.PP
\fBParameters\fP
.RS 4
\fItm\fP The original \fBAETimer\fP instance to make a copy of
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_bRunTrd\fP, and \fBstartThread()\fP\&.
.SS "AETimer::~AETimer (void)\fR [inline]\fP"

.PP
Class destructor\&. 
.PP
Definition at line \fB78\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBstopThread()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAETimer\fP & AETimer::operator= (const \fBAETimer\fP & tm)\fR [inline]\fP"

.PP
The copy assignment operator\&. Just copies the data and then starts the timer if original timer was started\&.
.PP
\fBParameters\fP
.RS 4
\fItm\fP The original \fBAETimer\fP instance to make a copy of
.RE
.PP
\fBReturns\fP
.RS 4
Reference to the resulting \fBAETimer\fP copy
.RE
.PP

.PP
Definition at line \fB65\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_bRunTrd\fP, \fBm_rDelay\fP, \fBm_ullTicks\fP, and \fBstartThread()\fP\&.
.SS "void AETimer::startThread (void)\fR [inline]\fP"

.PP
Starts the timer thread and starts tick counting\&. 
.PP
\fBNote\fP
.RS 4
Does nothing if thread is already started 
.RE
.PP

.PP
Definition at line \fB86\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_bRunTrd\fP, \fBm_trdCounting\fP, and \fBtickTimer()\fP\&.
.SS "void AETimer::stopThread (void)\fR [inline]\fP"

.PP
Stops the timer thread and stops tick counting\&. 
.PP
Definition at line \fB101\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_bRunTrd\fP, and \fBm_trdCounting\fP\&.
.SS "void AETimer::resetTick (void)\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Resets the timer's tick to 0\&. 
.PP
Definition at line \fB113\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_ullTicks\fP\&.
.SS "void AETimer::setTick (const \fBullint\fP tick)\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Sets the new tick value instead of the current\&. 
.PP
\fBParameters\fP
.RS 4
\fItick\fP The tick value to set instance's tick value to
.RE
.PP

.PP
Definition at line \fB121\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_ullTicks\fP\&.
.SS "void AETimer::setDelay (const double tps)\fR [inline]\fP"

.PP
Sets the new delay instead of the current\&. 
.PP
\fBNote\fP
.RS 4
It stops the thread and starts it again -- don't expect the counting to start immediately
.RE
.PP
\fBParameters\fP
.RS 4
\fItps\fP The amount of ticks per second to set the delay to
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_rDelay\fP, \fBAEFrame::setFps()\fP, \fBstartThread()\fP, and \fBstopThread()\fP\&.
.SS "\fBullint\fP AETimer::getTick (void) const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Returns the current tick of the timer\&. 
.PP
\fBNote\fP
.RS 4
If thread is not started/working, the return value will be the same
.RE
.PP
\fBReturns\fP
.RS 4
ullint of the current timer tick
.RE
.PP

.PP
Definition at line \fB141\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_ullTicks\fP\&.
.SS "long double AETimer::getWorldTime (void) const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Calculates the approximate world time of the timer in seconds (from the ticks) 
.PP
\fBNote\fP
.RS 4
If thread is not started/working, the return value will be the same
.RE
.PP
\fBReturns\fP
.RS 4
double of the approximate world time the timer has counted (using it's ticks)
.RE
.PP

.PP
Definition at line \fB150\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBAEFrame::getDelay()\fP, \fBm_rDelay\fP, and \fBm_ullTicks\fP\&.
.SS "double AETimer::getFrameRate (void) const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Returns the fps goal of \fBAEFrame\fP instance in the \fBAETimer\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBAEFrame::getFrameRate()\fP
.RE
.PP
\fBReturns\fP
.RS 4
Rounded int of the approximated fps goal
.RE
.PP

.PP
Definition at line \fB159\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBAEFrame::getFrameRate()\fP, and \fBm_rDelay\fP\&.
.SS "double AETimer::getDelay (void) const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Returns the maximum \fBAEFrame\fP's instance in the \fBAETimer\fP delay from the set fps, in seconds\&. 
.PP
\fBSee also\fP
.RS 4
\fBAEFrame::getDelay()\fP
.RE
.PP
\fBReturns\fP
.RS 4
double of the maximum \fBAEFrame\fP's instance in the \fBAETimer\fP delay in real-world seconds
.RE
.PP

.PP
Definition at line \fB168\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBAEFrame::getDelay()\fP, and \fBm_rDelay\fP\&.
.SS "static void AETimer::waitForTick (const \fBAETimer\fP & timer, const \fBullint\fP tick)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.PP
Stops and sleeps the thread untill the given timer hits the certain tick number\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP The instance of the \fBAETimer\fP to wait for
.br
\fItick\fP The \fBAETimer\fP instance tick value to wait for
.RE
.PP

.PP
Definition at line \fB177\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBAEFrame::sleep()\fP\&.
.SS "static void AETimer::waitTicks (const \fBAETimer\fP & timer, const \fBullint\fP tick)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP"

.PP
Stops and sleeps the thread untill the given timer goes through certain tick amount\&. 
.PP
\fBParameters\fP
.RS 4
\fItimer\fP The instance of the \fBAETimer\fP to wait for
.br
\fItick\fP The amount of ticks to wait for in the \fBAETimer\fP instance
.RE
.PP

.PP
Definition at line \fB189\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBwaitForTick()\fP\&.
.SS "void AETimer::tickTimer (void)\fR [inline]\fP, \fR [private]\fP, \fR [noexcept]\fP"

.PP
The function that does the tick counting for the timer\&. 
.PP
Definition at line \fB199\fP of file \fBAETimer\&.hpp\fP\&.
.PP
References \fBm_bRunTrd\fP, \fBm_rDelay\fP, \fBm_ullTicks\fP, and \fBAEFrame::sleep()\fP\&.
.SS "AETimer::REGISTER_MODULE (\fBAETimer\fP)\fR [private]\fP"

.SS "static \fBullint\fP \fB__AEModuleBase\fP< \fBAETimer\fP  >::getModuleAmount (void)\fR [inline]\fP, \fR [static]\fP, \fR [noexcept]\fP, \fR [inherited]\fP"

.PP
Get the \fBamount of the currently-alive instances of module T\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fB__AEModuleBase<T>::m_ullModulesAlive\fP
.RE
.PP
\fBReturns\fP
.RS 4
Unsigned long long of the alive module amount 
.RE
.PP

.PP
Definition at line \fB121\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "static constexpr const std::string_view \fB__AEModuleBase\fP< \fBAETimer\fP  >::getModuleName (void)\fR [static]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP, \fR [inherited]\fP"

.PP
Get the \fBname of the module\fP\&. 
.PP
\fBAttention\fP
.RS 4
You \fIneed\fP to add \fBREGISTER_MODULE()\fP to the end of the class declarations if you want to use this thing 
.RE
.PP
\fBSee also\fP
.RS 4
\fBREGISTER_MODULE()\fP
.RE
.PP
\fBReturns\fP
.RS 4
The name of the module as a const std::strinv_view type 
.RE
.PP

.SS "constexpr const \fBullint\fP \fB__AEModuleBase\fP< \fBAETimer\fP  >::getModuleID (void)\fR [inline]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP, \fR [inherited]\fP"

.PP
Get the \fBid number of the instance\fP of the module\&. 
.PP
\fBRemarks\fP
.RS 4
Every module has its own instance counter
.RE
.PP
\fBReturns\fP
.RS 4
The id number of the instance of the module as \fBullint\fP type 
.RE
.PP

.PP
Definition at line \fB144\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "static constexpr const \fBullint\fP \fB__AEModuleBase\fP< \fBAETimer\fP  >::getInstanceCounter (void)\fR [inline]\fP, \fR [static]\fP, \fR [constexpr]\fP, \fR [noexcept]\fP, \fR [inherited]\fP"

.PP
Get the current value of the \fBinstance counter\fP of the module\&. 
.PP
\fBSee also\fP
.RS 4
\fB__AEModuleBase::m_ullInstanceCounter\fP
.RE
.PP
\fBReturns\fP
.RS 4
The amount of the module's instances overall created throughout the program's runtime 
.RE
.PP

.PP
Definition at line \fB156\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAEFrame\fP AETimer::m_rDelay\fR [private]\fP"

.PP
The frame-rater of the timer for proper delay in the tick-counting function loop\&. 
.PP
Definition at line \fB211\fP of file \fBAETimer\&.hpp\fP\&.
.SS "std::thread AETimer::m_trdCounting\fR [private]\fP"

.PP
The thread that does the tick counting\&. 
.PP
Definition at line \fB213\fP of file \fBAETimer\&.hpp\fP\&.
.SS "std::atomic<\fBullint\fP> AETimer::m_ullTicks\fR [private]\fP"

.PP
The tick count variable\&. 
.PP
Definition at line \fB215\fP of file \fBAETimer\&.hpp\fP\&.
.SS "std::atomic<bool> AETimer::m_bRunTrd\fR [private]\fP"

.PP
The flag to continue running the tick counting loop\&. 
.PP
Definition at line \fB217\fP of file \fBAETimer\&.hpp\fP\&.
.SS "std::atomic<std::size_t> \fB__AEModuleBase\fP< \fBAETimer\fP  >::m_ullModulesAlive\fR [inline]\fP, \fR [static]\fP, \fR [protected]\fP, \fR [inherited]\fP"

.PP
Amount of the currently-alive (not destroyed) instances of the module\&. 
.PP
Definition at line \fB165\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "std::atomic<\fBullint\fP> \fB__AEModuleBase\fP< \fBAETimer\fP  >::m_ullInstanceCounter\fR [inline]\fP, \fR [static]\fP, \fR [protected]\fP, \fR [inherited]\fP"

.PP
Amount of the instances of the module ever created during the program's runtime\&. 
.PP
Definition at line \fB170\fP of file \fBAEModuleBase\&.hpp\fP\&.
.SS "const \fBullint\fP \fB__AEModuleBase\fP< \fBAETimer\fP  >::m_ullModuleId\fR [protected]\fP, \fR [inherited]\fP"

.PP
The ID number of the current module\&. 
.PP
Definition at line \fB175\fP of file \fBAEModuleBase\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
