.TH "AETimer/include/AETimer.hpp" 3 "Thu Nov 9 2023 20:42:38" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AETimer/include/AETimer.hpp \- This file contains the code for engine's timer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/AEFrame\&.hpp'\fP
.br
\fC#include 'include/AETypedefs\&.hpp'\fP
.br
\fC#include 'include/AEModuleBase\&.hpp'\fP
.br
\fC#include 'include/AEFlags\&.hpp'\fP
.br
\fC#include <thread>\fP
.br
\fC#include <atomic>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAETimer\fP"
.br
.RI "ArtyK's Engine Timer -- the engine's internal timer for, um, timing events or anything, with variable tick speed\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBREGISTER_CLASS\fP (\fBAETimer\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the code for engine's timer\&. 

You can use it to time events\&. Or like\&.\&.\&.wait for the tick of the timer for a certain delay or even to happen\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAETimer\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "REGISTER_CLASS (\fBAETimer\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
