.TH "AETimer/include/AETimer.hpp" 3 "Fri Feb 2 2024 00:44:14" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AETimer/include/AETimer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/AEFrame\&.hpp'\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAETimer\fP"
.br
.RI "ArtyK's Engine Timer -- the engine's internal timer for, um, timing events or anything, with variable tick speed\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the code for engine's timer\&. You can use it to time events\&. Or like\&.\&.\&.wait for the tick of the timer for a certain delay or even to happen\&.
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAETimer\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
