.TH "AEVector/include/AEVector.hpp" 3 "Thu Feb 29 2024 21:13:54" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEVector/include/AEVector.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'include/AEFlags\&.hpp'\fP
.br
\fR#include 'include/AEMath\&.hpp'\fP
.br
\fR#include <string>\fP
.br
\fR#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAEVector< T, dimAmount, >\fP"
.br
.RI "The ArtyK's Engine's mathematical vector -- for mathematically-correct vector operations\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAEVector\fP< int, 2 > \fBAEVec2Int\fP"
.br
.RI "The shortcut typedef for the 2-dimensional integer vector\&. "
.ti -1c
.RI "typedef \fBAEVector\fP< int, 3 > \fBAEVec3Int\fP"
.br
.RI "The shortcut typedef for the 3-dimensional integer vector\&. "
.ti -1c
.RI "typedef \fBAEVector\fP< float, 2 > \fBAEVec2Float\fP"
.br
.RI "The shortcut typedef for the 2-dimensional floating point vector\&. "
.ti -1c
.RI "typedef \fBAEVector\fP< float, 3 > \fBAEVec3Float\fP"
.br
.RI "The shortcut typedef for the 3-dimensional floating point vector\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the engine's math vector code\&. So you can make more math calculations with it\&.\&.\&.and things in graphics and games that need (math) vectors to accomplish
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBAEVector\&.hpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAEVector\fP<float, 2> \fBAEVec2Float\fP"

.PP
The shortcut typedef for the 2-dimensional floating point vector\&. 
.PP
Definition at line \fB546\fP of file \fBAEVector\&.hpp\fP\&.
.SS "typedef \fBAEVector\fP<int, 2> \fBAEVec2Int\fP"

.PP
The shortcut typedef for the 2-dimensional integer vector\&. 
.PP
Definition at line \fB542\fP of file \fBAEVector\&.hpp\fP\&.
.SS "typedef \fBAEVector\fP<float, 3> \fBAEVec3Float\fP"

.PP
The shortcut typedef for the 3-dimensional floating point vector\&. 
.PP
Definition at line \fB548\fP of file \fBAEVector\&.hpp\fP\&.
.SS "typedef \fBAEVector\fP<int, 3> \fBAEVec3Int\fP"

.PP
The shortcut typedef for the 3-dimensional integer vector\&. 
.PP
Definition at line \fB544\fP of file \fBAEVector\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
