.TH "AEMisc/include Directory Reference" 3 "Fri Jan 12 2024 00:59:44" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEMisc/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAEFlags\&.hpp\fP"
.br
.RI "This file contains engine flags that are used to alter it's code and behaviour\&. "
.ti -1c
.RI "file \fBAEMath\&.hpp\fP"
.br
.RI "This file contains the engine math functions, (probably)optimised for engine stuff\&. "
.ti -1c
.RI "file \fBAETrigLookup\&.hpp\fP"
.br
.RI "This file contains the results for the trigonometric function lookup tables\&. "
.ti -1c
.RI "file \fBAETypedefs\&.hpp\fP"
.br
.RI "This file contains typedefs/aliases of the variable types that are long and are used often/inconvenient to use in their long original naming\&. "
.ti -1c
.RI "file \fBAEUtils\&.hpp\fP"
.br
.RI "This file contains engine function (hopefully useful) utilities\&. "
.in -1c
