.TH "AECustomTypes/include Directory Reference" 3 "Fri Jan 12 2024 00:59:44" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AECustomTypes/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAELogTypes\&.hpp\fP"
.br
.RI "This file contains the macros for the \fBAELogEntry\fP (and consequently \fBAELogger\fP's) log types\&. "
.in -1c
