.TH "AELogger/include Directory Reference" 3 "Thu Nov 9 2023 20:42:39" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogger/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAELogger\&.hpp\fP"
.br
.RI "This file contains the code for the engine's logger module, err\&.\&.\&.for logging data to file\&. "
.ti -1c
.RI "file \fBAELogTypes\&.hpp\fP"
.br
.RI "This file contains the macros for the \fBAELogger\fP's log types\&. "
.in -1c
