.TH "AELogger/src Directory Reference" 3 "Thu Jan 11 2024 21:33:35" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogger/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAELogger\&.cpp\fP"
.br
.RI "This file contains the definitions of the engine's logger's functions\&. "
.in -1c
