.TH "AEFileReader/include Directory Reference" 3 "Fri Jan 12 2024 00:59:44" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEFileReader/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAEFileReader\&.hpp\fP"
.br
.RI "This file contains the code for the engine's file reader\&. "
.in -1c
