.TH "AEMisc/include Directory Reference" 3 "Mon Mar 18 2024 18:44:25" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEMisc/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAEFlags\&.hpp\fP"
.br
.RI "This file contains the \fBflags to manipulate engine's funcitonality\fP\&. "
.ti -1c
.RI "file \fBAEMath\&.hpp\fP"
.br
.RI "This file contains the engine's \fBmath and math-related functions\fP\&. "
.ti -1c
.RI "file \fBAEMathConst\&.hpp\fP"
.br
.RI "This file contains the engine's \fBmath constants\fP\&. "
.ti -1c
.RI "file \fBAEMathTrigLookup\&.hpp\fP"
.br
.RI "This file contains the engine's \fBtrigonometric function lookup tables\fP\&. "
.ti -1c
.RI "file \fBAETypedefs\&.hpp\fP"
.br
.RI "This file contains the engine's \fBtypedefs and variable type aliases\fP\&. "
.ti -1c
.RI "file \fBAEUtils\&.hpp\fP"
.br
.RI "This file contains the engine's \fBusefull utilities for trivial tasks\fP\&. "
.ti -1c
.RI "file \fBAEUtilsMacros\&.hpp\fP"
.br
.RI "This file contains the engine's \fBmacros for trivial tasks\fP\&. "
.in -1c
