.TH "AETimer/include Directory Reference" 3 "Thu Jan 11 2024 21:33:35" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AETimer/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAETimer\&.hpp\fP"
.br
.RI "This file contains the code for engine's timer\&. "
.in -1c
