.TH "AEFileReader/src Directory Reference" 3 "Fri Nov 10 2023 00:47:23" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEFileReader/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAEFileReader\&.cpp\fP"
.br
.RI "This file contains the definitions of the engine's file reader's functions\&. "
.in -1c
