.TH "AECustomTypes/include Directory Reference" 3 "Fri Nov 10 2023 00:47:23" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AECustomTypes/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAELogEntry\&.hpp\fP"
.br
.RI "This file contains the code for the log entry -- struct containing data from the entry of the log file\&. "
.in -1c
