.TH "AEModuleBase/include Directory Reference" 3 "Thu Nov 9 2023 20:42:39" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEModuleBase/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAEModuleBase\&.hpp\fP"
.br
.RI "This file contains the code for the module that all (utility) modules base on in the ArtyK's Console Engine class\&. "
.in -1c
