.TH "build/CMakeFiles/3.28.1/CompilerIdCXX/CMakeCXXCompilerId.cpp" 3 "Thu Feb 15 2024 11:57:32" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/CMakeFiles/3.28.1/CompilerIdCXX/CMakeCXXCompilerId.cpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fB__has_include\fP(\fBx\fP)   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBCOMPILER_ID\fP   ''"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSTRINGIFY_HELPER\fP(\fBX\fP)   #\fBX\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSTRINGIFY\fP(\fBX\fP)   \fBSTRINGIFY_HELPER\fP(\fBX\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPLATFORM_ID\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBARCHITECTURE_ID\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEC\fP(\fBn\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBHEX\fP(\fBn\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBCXX_STD\fP   \fB__cplusplus\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, char *\fBargv\fP[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBconst\fP  * \fBinfo_compiler\fP = 'INFO' ':' 'compiler[' '' ']'"
.br
.ti -1c
.RI "char \fBconst\fP  * \fBinfo_platform\fP = 'INFO' ':' 'platform[' ']'"
.br
.ti -1c
.RI "char \fBconst\fP  * \fBinfo_arch\fP = 'INFO' ':' 'arch[' ']'"
.br
.ti -1c
.RI "\fBconst\fP char * \fBinfo_language_standard_default\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBinfo_language_extensions_default\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP __has_include(\fBx\fP)   0"

.PP
Definition at line \fB11\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP ARCHITECTURE_ID"

.PP
Definition at line \fB715\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP COMPILER_ID   ''"

.PP
Definition at line \fB426\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP CXX_STD   \fB__cplusplus\fP"

.PP
Definition at line \fB813\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP DEC(\fBn\fP)"
\fBValue:\fP.PP
.nf
  ('0' + (((n) / 10000000)%10)), \\
  ('0' + (((n) / 1000000)%10)),  \\
  ('0' + (((n) / 100000)%10)),   \\
  ('0' + (((n) / 10000)%10)),    \\
  ('0' + (((n) / 1000)%10)),     \\
  ('0' + (((n) / 100)%10)),      \\
  ('0' + (((n) / 10)%10)),       \\
  ('0' +  ((n) % 10))
.fi

.PP
Definition at line \fB719\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP HEX(\fBn\fP)"
\fBValue:\fP.PP
.nf
  ('0' + ((n)>>28 & 0xF)), \\
  ('0' + ((n)>>24 & 0xF)), \\
  ('0' + ((n)>>20 & 0xF)), \\
  ('0' + ((n)>>16 & 0xF)), \\
  ('0' + ((n)>>12 & 0xF)), \\
  ('0' + ((n)>>8  & 0xF)), \\
  ('0' + ((n)>>4  & 0xF)), \\
  ('0' + ((n)     & 0xF))
.fi

.PP
Definition at line \fB730\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP PLATFORM_ID"

.PP
Definition at line \fB557\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP STRINGIFY(\fBX\fP)   \fBSTRINGIFY_HELPER\fP(\fBX\fP)"

.PP
Definition at line \fB447\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "#\fBdefine\fP STRINGIFY_HELPER(\fBX\fP)   #\fBX\fP"

.PP
Definition at line \fB446\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, char * argv[])"

.PP
Definition at line \fB844\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char \fBconst\fP* info_arch = 'INFO' ':' 'arch[' ']'"

.PP
Definition at line \fB796\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "char \fBconst\fP* info_compiler = 'INFO' ':' 'compiler[' '' ']'"

.PP
Definition at line \fB433\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "\fBconst\fP char* info_language_extensions_default"
\fBInitial value:\fP.PP
.nf
= "INFO" ":" "extensions_default["





  "OFF"

"]"
.fi

.PP
Definition at line \fB832\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "\fBconst\fP char* info_language_standard_default"
\fBInitial value:\fP.PP
.nf
= "INFO" ":" "standard_default["











  "98"

"]"
.fi

.PP
Definition at line \fB816\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SS "char \fBconst\fP* info_platform = 'INFO' ':' 'platform[' ']'"

.PP
Definition at line \fB795\fP of file \fBCMakeCXXCompilerId\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
