.TH "ACEngine/main_ACEngine.cpp" 3 "Fri Jan 12 2024 01:10:12" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACEngine/main_ACEngine.cpp \- This file contains the testing code for the engine or\&.\&.larger project code, like a game\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'include/AEFileWriter\&.hpp'\fP
.br
\fC#include 'include/AEModuleBase\&.hpp'\fP
.br
\fC#include 'include/AETypedefs\&.hpp'\fP
.br
\fC#include 'include/AEFlags\&.hpp'\fP
.br
\fC#include 'include/AEMath\&.hpp'\fP
.br
\fC#include 'include/AEUtils\&.hpp'\fP
.br
\fC#include 'include/AETrigLookup\&.hpp'\fP
.br
\fC#include 'include/AELogger\&.hpp'\fP
.br
\fC#include 'include/AEFrame\&.hpp'\fP
.br
\fC#include 'include/AETimer\&.hpp'\fP
.br
\fC#include 'include/AEVector\&.hpp'\fP
.br
\fC#include 'include/AEFileReader\&.hpp'\fP
.br
\fC#include 'include/AELogTypes\&.hpp'\fP
.br
\fC#include 'include/AELogEntry\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the testing code for the engine or\&.\&.larger project code, like a game\&. 


.PP
\fBTodo\fP
.RS 4
Add the global variable list from my older engine 
.PP
Add \fBAELogParser\fP to parse the engine's (\fBAELogger\fP) log files 
.PP
Add engine's file format, AEFile 
.PP
Transfer and adapt code from my previous engine attempt 
.PP
Add project documentation (explanation, and examples for example) to the readme\&.md files
.RE
.PP
.PP
Should not cause everything to break :) 
.PP
Definition in file \fBmain_ACEngine\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main ()"

.PP
Definition at line \fB42\fP of file \fBmain_ACEngine\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
