.TH "AELogParser/main_AELogParser.cpp" 3 "Fri Jan 12 2024 01:05:06" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AELogParser/main_AELogParser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'AELogParser\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main ()"

.PP
Definition at line \fB8\fP of file \fBmain_AELogParser\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ArtyK's Console Engine from the source code\&.
