.TH "md__a_e_misc_2_r_e_a_d_m_e" 3 "Fri Nov 10 2023 00:47:23" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_misc_2_r_e_a_d_m_e \- AEMisc project 
.PP
This is a project that contains the miscelanneous code and stuff for the engine, that cannot be attributed to a single module\&. Stuff like global engine variables, utilities, typedefs, macros, etc\&. 
