.TH "md__a_e_log_parser_2_r_e_a_d_m_e" 3 "Sat Mar 16 2024 11:28:29" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_log_parser_2_r_e_a_d_m_e \- \fBAELogParser\fP project 
.PP
This is the project for the ACEngine that reads and parses the logs created by the engine 
