.TH "md__a_e_timer_2_r_e_a_d_m_e" 3 "Thu Mar 14 2024 20:55:55" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_timer_2_r_e_a_d_m_e \- \fBAETimer\fP project 
.PP
This is the timer module for the engine\&.\&.for counting time and timing events\&. Requires AEModuleBase, AEMisc, and \fBAEFrame\fP to work\&. 
