.TH "md__a_e_frame_2_r_e_a_d_m_e" 3 "Fri Jan 12 2024 01:05:42" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_frame_2_r_e_a_d_m_e \- \fBAEFrame\fP project 
.PP
This is the precise frame delay module for the engine\&. Requires AEModuleBase and AEMisc to work\&. 
