.TH "md__a_e_file_reader_2_r_e_a_d_m_e" 3 "Sat Jan 20 2024 16:30:37" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_file_reader_2_r_e_a_d_m_e \- \fBAEFileReader\fP project 
.PP
This is the project for engine's file reader module\&. It allows to read the data from the files fast 
