.TH "md__a_e_log_parser_2_r_e_a_d_m_e" 3 "Thu Mar 14 2024 20:55:55" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_log_parser_2_r_e_a_d_m_e \- \fBAELogParser\fP project 
.PP
This is the project for the ACEngine that reads and parses the logs created by the engine 
