.TH "md__a_e_log_entry_2_r_e_a_d_m_e" 3 "Thu Feb 15 2024 11:57:32" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_log_entry_2_r_e_a_d_m_e \- \fBAELogEntry\fP project 
.PP
This is the project for the engine's \fBAELogEntry\fP struct\&. This defines the structure for the log entry and the it's utilities (such as formatting and parsing) 
