.TH "md__a_e_module_base_2_r_e_a_d_m_e" 3 "Thu Feb 29 2024 20:45:23" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_module_base_2_r_e_a_d_m_e \- AEModuleBase project 
.PP
This module is the basis for all the engine modules\&. It allows for a basic convenience of checking the class/module name during run-time and also looking at alive instances\&. If I find anything usefull for \fIall\fP engine modules - it'll go here\&. 
