.TH "md__a_e_file_writer_2_r_e_a_d_m_e" 3 "Thu Nov 9 2023 20:42:38" "Version v0.0.8a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__a_e_file_writer_2_r_e_a_d_m_e \- \fBAEFileWriter\fP project 
.PP
This is the file-writing module for the engine\&. Requires AEModuleBase and AEMisc to work\&. 
