.TH "todo" 3 "Sat Jan 20 2024 16:30:37" "Version v0.0.8.5a" "ArtyK's Console Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fB__AEModuleBase< T >::m_sModulename\fP \fP" 1c
Find a way to make it constexpr and compile-time evaluated  
.IP "\fBMember \fBace::math::ceilToInt\fP (const Y num) noexcept\fP" 1c
Change the body of the function to use std::ceil() instead, when it gets constexpr (after c++23)  
.IP "\fBMember \fBace::math::floorToInt\fP (const Y num) noexcept\fP" 1c
Change the body of the function to use std::floor() instead, when it gets constexpr (after c++23)  
.IP "\fBMember \fBace::math::truncToInt\fP (const Y num) noexcept\fP" 1c
Change the body of the function to use std::trunc() instead, when it gets constexpr (after c++23)  
.IP "\fBClass \fBAEFileReader\fP \fP" 1c
add generic read function  
.IP "\fBMember \fBAEFileWriter::write\fP (const T &var, const size_t datasz=0, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH)\fP" 1c
Add a way to add custom types to this generic write function\&.  
.IP "\fBMember \fBAEFileWriter::writeFloat\fP (const T num, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH)\fP" 1c
Add custom way to format the float number  
.IP "\fBClass \fBAELogger\fP \fP" 1c
Implement copy constructors and copy assignment 
.PP
.PP
Add the ability to open the same log file/redirect the instance requests to the one that has it open first\&. 
.PP
.IP "\fBMember \fBAELogger::writeToLog\fP (const std::string_view logmessg, const cint logtype=AELOG_TYPE_INFO, const std::string_view logmodule=AELOG_DEFAULT_MODULE_NAME)\fP" 1c
Implement decrease in log queue size\&.\&.\&.somehow  
.IP "\fBFile \fBAETrigLookup\&.hpp\fP \fP" 1c
Add the ability to calculate the tables at compile time + control the size (36 elements or 3600, etc) Maybe it's a future (c++26) thing 
.IP "\fBFile \fBmain_ACEngine\&.cpp\fP \fP" 1c
Add the global variable list from my older engine 
.PP
.PP
Add \fBAELogParser\fP to parse the engine's (\fBAELogger\fP) log files 
.PP
.PP
Add engine's file format, AEFile 
.PP
.PP
Transfer and adapt code from my previous engine attempt 
.PP
.PP
Add project documentation (explanation, and examples for example) to the readme\&.md files
.PP

