ArtyK's Console Engine: AELogEntryInfo Struct Reference
AELogEntryInfo Struct Reference
The struct that holds the information about the log entry, used by AELogParser.
#include <AELogEntryInfo.hpp>
Public Member Functions
constexpr bool isInvalid () const noexcept
Checks if the current instance is invalid.
constexpr bool isBroken () const noexcept
Checks if the current instance is broken (partially invalid)
constexpr bool isInvalidCursor () const noexcept
Checks if the cursor index of the current instance is invalid.
constexpr bool isInvalidMName () const noexcept
Checks if the cursor index of the current instance is invalid.
constexpr bool isInvalidType () const noexcept
Checks if the cursor index of the current instance is invalid.
Static Public Member Functions
static constexpr AELogEntryInfo invalidEntry () noexcept
Returns the invalid instance of the AELogEntryInfo.
Public Attributes
llint cursorIndex = 0
The cursor number of the log entry in the opened log file.
short mnameIndex = 0
The index of the module name of the log entry The module names are enumerated when initially parsing the log file.
cint logType = 0
The type of the log entry.
Detailed Description
The struct that holds the information about the log entry, used by AELogParser.
See also
AELogEntry
Definition at line 28 of file AELogEntryInfo.hpp.
Member Function Documentation
invalidEntry()
static constexpr AELogEntryInfo AELogEntryInfo::invalidEntry () inline static constexpr noexcept
Returns the invalid instance of the AELogEntryInfo.
Returns
Invalid instance of the AELogEntryInfo
Definition at line 43 of file AELogEntryInfo.hpp.
References AELEI_INVALID_CURSOR, AELEI_INVALID_TYPE, and AELEI_INVLAID_MNAME.
isInvalid()
constexpr bool AELogEntryInfo::isInvalid () const inline constexpr noexcept
Checks if the current instance is invalid.
See also
AELogEntryInfo::isInvalidCursor()
AELogEntryInfo::isInvalidMName()
AELogEntryInfo::isInvalidType()
Returns
True if the instance is invalid, false otherwise
Definition at line 52 of file AELogEntryInfo.hpp.
References isInvalidCursor(), isInvalidMName(), and isInvalidType().
isBroken()
constexpr bool AELogEntryInfo::isBroken () const inline constexpr noexcept
Checks if the current instance is broken (partially invalid)
See also
AELogEntryInfo::isInvalidCursor()
AELogEntryInfo::isInvalidMName()
AELogEntryInfo::isInvalidType()
Returns
True if the instance is broken, false otherwise
Definition at line 63 of file AELogEntryInfo.hpp.
References isInvalidCursor(), isInvalidMName(), and isInvalidType().
isInvalidCursor()
constexpr bool AELogEntryInfo::isInvalidCursor () const inline constexpr noexcept
Checks if the cursor index of the current instance is invalid.
Returns
True if it's invalid, false otherwise
Definition at line 71 of file AELogEntryInfo.hpp.
References AELEI_INVALID_CURSOR.
isInvalidMName()
constexpr bool AELogEntryInfo::isInvalidMName () const inline constexpr noexcept
Checks if the cursor index of the current instance is invalid.
Returns
True if it's invalid, false otherwise
Definition at line 79 of file AELogEntryInfo.hpp.
References AELEI_INVLAID_MNAME.
isInvalidType()
constexpr bool AELogEntryInfo::isInvalidType () const inline constexpr noexcept
Checks if the cursor index of the current instance is invalid.
Returns
True if it's invalid, false otherwise
Definition at line 87 of file AELogEntryInfo.hpp.
References AELEI_INVALID_TYPE.
Member Data Documentation
cursorIndex
llint AELogEntryInfo::cursorIndex = 0
The cursor number of the log entry in the opened log file.
Definition at line 31 of file AELogEntryInfo.hpp.
mnameIndex
short AELogEntryInfo::mnameIndex = 0
The index of the module name of the log entry The module names are enumerated when initially parsing the log file.
See also
AELogParser::openLog()
Definition at line 35 of file AELogEntryInfo.hpp.
logType
cint AELogEntryInfo::logType = 0
The type of the log entry.
Definition at line 37 of file AELogEntryInfo.hpp.
The documentation for this struct was generated from the following file:
AECustomTypes/include/AELogEntryInfo.hpp