ArtyK's Console Engine: AEFileWriter Class Reference
AEFileWriter Class Reference
ArtyK's Engine File Writer; umm, it writes data to given file.
#include <AEFileWriter.hpp>
Public Member Functions
AEFileWriter (const std::string_view filename, const cint flags=0, const ullint af_interval=AEFW_DEFAULT_AUTOFLUSH_INTERVAL)
Class constructor – creates the AEFileWriter instance and opens the file.
AEFileWriter (void) noexcept
Class constructor – creates the instance but doesn't do anything.
AEFileWriter (AEFileWriter &&fw) noexcept
Move constructor.
AEFileWriter (const AEFileWriter &)=delete
Deleted copy constructor.
AEFileWriter & operator= (const AEFileWriter &)=delete
Deleted copy assignment operator.
~AEFileWriter (void) noexcept
Default Destructor.
cint openFile (const std::string_view str, const cint flags=0, const ullint af_interval=AEFW_DEFAULT_AUTOFLUSH_INTERVAL)
Open(and create) file with given name and flag.
cint flushFile (void) const noexcept
Flushes the opened file.
cint closeFile (void) noexcept
Closes the currently opened file.
template<typename T >
cint write (const T &var, const size_t datasz=0, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Generic function for writing data, invoking proper write functions for built-in types.
cint writeString (const std::string &str, const bool includeNull=false, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write std::string, as is, to file, and flush if necessary.
cint writeString (const std::vector< char > &str, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write std::vector<char> (string), as is, to file, and flush if necessary.
cint writeString (const char *const cdata, const bool includeNull=false, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write c-string, as is, to file, and flush if necessary.
cint writeInt (const llint num, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes the (signed) integer as text to open file.
cint writeUInt (const ullint num, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes the (unsigned) integer as text to open file.
template<typename T >
requires (std::is_floating_point<T>::value == true)
cint writeFloat (const T num, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes the float value as text to the opened file.
cint writeBool (const bool num, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes the boolean to file as text (true/false).
cint writeChar (const char c, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes the single (ascii) character to the file.
cint writeByte (const unsigned char cdata, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Writes one byte of data to the file.
cint writeBytes (const void *const cdata, const std::size_t dsize, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write a stream of bytes to file, from pointer.
cint writeBytes (const std::vector< unsigned char > &cdata, const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write a stream of bytes to file, from std::vector<unsigned char>.
cint writeData_ptr (const void *const cdata, const std::size_t dcount, const std::size_t dsize=sizeof(char), const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write binary data, as is, to file, and flush if necessary.
template<typename T >
cint writeData_ref (const T &cdata, const std::size_t tsize=sizeof(T), const bool useAutoFlush=AEFW_DEFAULT_AUTOFLUSH) noexcept
Write binary data, as is, to file, and flush if necessary.
bool isOpen (void) const noexcept
Checks if a file is open by this file-writer.
bool isClosed (void) const noexcept
Checks if a file isn't open by this file-writer.
llint getFileSize (void) const noexcept
Returns size of the file in bytes.
std::string getFullFileName (void) const noexcept
Returns the full name of currently open file, including the relative path, if such was provided.
std::string getRelativePath (void) const
Returns the relative path of the opened file.
std::string getFileName (void) const
Returns the name of the opened file, devoid of the path.
std::string getFullPath (void) const
Returns the full, absolute path of the opened file.
std::FILE * getFilePtr (void) const noexcept
Returns the file pointer of this file-writer.
llint getCursorPos (void) const noexcept
Returns current write cursor position.
int setCursorPos (const llint pos, const int origin=SEEK_CUR) const noexcept
Sets read cursor position to pos from origin.
ullint getTotalWrites (void) const noexcept
Returns total write requests made to file.
std::size_t getLastWrittenAmount (void) const noexcept
Gets the last written amount of bytes from the opened file.
Static Public Member Functions
static ullint getModuleAmount (void) noexcept
Get the amount of the currently-alive instances of module T
static constexpr const std::string_view getModuleName (void) noexcept
Get the name of the module
Public Attributes
ullint m_ullFlushInterval
Interval in write operations before automatic flush operation.
Static Protected Attributes
static std::atomic< std::size_t > m_ullModulesAlive
Amount of the currently-alive (not destroyed) instances of the module.
Private Member Functions
void autoFlush (void) noexcept
Checks for and performs the auto-flush operation if required.
REGISTER_MODULE (AEFileWriter)
Private Attributes
std::string m_sFilename
Full filename and relative path.
std::atomic< ullint > m_ullTotalWrites
Counter for total write operations for file.
std::size_t m_szLastWrittenAmount
The amount of written bytes during last operation.
std::FILE * m_fpFilestr
Object for file writing.
cint m_cFlags
Flags that were used to open the file.
Detailed Description
ArtyK's Engine File Writer; umm, it writes data to given file.
It is a wrapper around the C's FILE api, for speed and convenience. It can write strings, bools, ints, and floats, both as raw bytes and formatted to text
Just create it and dump the gigabytes of data to your files. Hungarian notation is fw. (m_fwMyFileWriter) Flags start with AEFW_
Warning
This is not thread safe!
Definition at line 108 of file AEFileWriter.hpp.
Constructor & Destructor Documentation
AEFileWriter() [1/4]
AEFileWriter::AEFileWriter (const std::string_view filename, const cint flags = 0, const ullint af_interval = AEFW_DEFAULT_AUTOFLUSH_INTERVAL) explicit
Class constructor – creates the AEFileWriter instance and opens the file.
See also
AEFileWriter::openFile()
Parameters
filename Name of the file, with extension
flags Flags for file opening; look up AEFW_FLAG_* for more info
af_interval interval in file writes between automatic file flushing
Definition at line 12 of file AEFileWriter.cpp.
References openFile().
AEFileWriter() [2/4]
AEFileWriter::AEFileWriter (void) inline noexcept
Class constructor – creates the instance but doesn't do anything.
Definition at line 125 of file AEFileWriter.hpp.
AEFileWriter() [3/4]
AEFileWriter::AEFileWriter (AEFileWriter && fw) noexcept
Move constructor.
Parameters
fw Object to be moved
Definition at line 20 of file AEFileWriter.cpp.
AEFileWriter() [4/4]
AEFileWriter::AEFileWriter (const AEFileWriter &) delete
Deleted copy constructor.
There is no need to copy AEFW, since access to file is in instance's FILE pointer. If in original instance, the file gets closed, the pointer is invalidated. Which can lead to...bad consequences using it again in the copied instance.
~AEFileWriter()
AEFileWriter::~AEFileWriter (void) inline noexcept
Default Destructor.
Just flushes and closes the file.
Definition at line 153 of file AEFileWriter.hpp.
References closeFile(), and flushFile().
Member Function Documentation
operator=()
AEFileWriter & AEFileWriter::operator= (const AEFileWriter &) delete
Deleted copy assignment operator.
There is no need to copy AEFW, since access to file is in instance's FILE pointer. If in original instance, the file gets closed, the pointer is invalidated. Which can lead to...bad consequences using it again in the copied instance.
openFile()
cint AEFileWriter::openFile (const std::string_view str, const cint flags = 0, const ullint af_interval = AEFW_DEFAULT_AUTOFLUSH_INTERVAL)
Open(and create) file with given name and flag.
On success sets AEFileWriter::m_cFlags to passed flag value.
Note
If the provided file flag is invalid, it returns AEFW_ERR_OPEN_FILE_WRONG_FLAG
If provided autoflush interval is a default value (AEFW_DEFAULT_AUTOFLUSH_INTERVAL), then the interval is not changed from the previous value
Warning
Using the AEFW_FLAG_APPEND_NO_CURSOR_MOVE disables AEFileWriter::getCursorPos(), AEFileWriter::setCursorPos(), and AEFileWriter::getFileSize(), since they manipulate the cursor.
Parameters
str Name of the file, with extension
flags Flags for file opening, AEFW_FLAG_* macros. More info in the docs
af_interval Interval in file writes between automatic file flushing.
Returns
AEFW_ERR_NOERROR if file was opened successfully; otherwise AEFW_ERR_OPEN_* flags (like AEFW_ERR_OPEN_FILE_NAME_EMPTY)
Definition at line 58 of file AEFileWriter.cpp.
References AEFW_DEFAULT_AUTOFLUSH_INTERVAL, AEFW_ERR_NOERROR, AEFW_ERR_OPEN_FILE_ALREADY_OPENED, AEFW_ERR_OPEN_FILE_ELSE, AEFW_ERR_OPEN_FILE_NAME_EMPTY, AEFW_ERR_OPEN_FILE_WRONG_FLAG, AEFW_FLAG_APPEND, AEFW_FLAG_APPEND_NO_CURSOR_MOVE, AEFW_FLAG_NOFLAGS, AEFW_FLAG_TRUNCATE, ace::utils::fopenCC(), isClosed(), isOpen(), m_cFlags, m_fpFilestr, m_sFilename, m_szLastWrittenAmount, and m_ullFlushInterval.
flushFile()
cint AEFileWriter::flushFile (void) const inline noexcept
Flushes the opened file.
That's it.
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 177 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_CLOSED_FILE, AEFW_ERR_FLUSH_ERROR, AEFW_ERR_WRITE_SUCCESS, and m_fpFilestr.
closeFile()
cint AEFileWriter::closeFile (void) inline noexcept
Closes the currently opened file.
Returns
AEFW_ERR_NOERROR if file was closed successfully; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open
Definition at line 191 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_CLOSED_FILE, AEFW_ERR_NOERROR, m_fpFilestr, m_sFilename, and m_szLastWrittenAmount.
write()
template<typename T > cint AEFileWriter::write (const T & var, const size_t datasz = 0, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Generic function for writing data, invoking proper write functions for built-in types.
Note
String types don't include null-termination characters. Use separate functions for to control that
Supported types: char, bool, integers, floats, strings; everything else is treated as binary stream.
Template Parameters
T Type of the variable to be written
Parameters
var Variable/data piece to be written
datasz Size of the data, in bytes. Only used if the T is a pointer to a binary stream, then it must be non-zero
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Todo
Add a way to add custom types to this generic write function.
Definition at line 623 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, and IS_SAME_NOCV.
writeString() [1/3]
cint AEFileWriter::writeString (const std::string & str, const bool includeNull = false, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write std::string, as is, to file, and flush if necessary.
Parameters
str String to write
includeNull Flag to include the trailing null-terminating character in the string
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 226 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, AEFW_ERR_WRITE_ZERO_SIZE, and writeData_ptr().
writeString() [2/3]
cint AEFileWriter::writeString (const std::vector< char > & str, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write std::vector<char> (string), as is, to file, and flush if necessary.
Note
It just writes the whole vector to file (since I cannot determine it without good ol' slow strlen). If you want to control the null-byte, pass the std::vector<char>.data() as the
Parameters
str String(in form of vector<char>) to write
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 244 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, AEFW_ERR_WRITE_ZERO_SIZE, and writeData_ptr().
writeString() [3/3]
cint AEFileWriter::writeString (const char *const cdata, const bool includeNull = false, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write c-string, as is, to file, and flush if necessary.
Parameters
cdata -String to write
includeNull Flag to include the null-terminating character at the end of the string
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 262 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, AEFW_ERR_WRITE_ZERO_SIZE, and writeData_ptr().
writeInt()
cint AEFileWriter::writeInt (const llint num, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes the (signed) integer as text to open file.
Parameters
num The signed integer to be written
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 286 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, and writeString().
writeUInt()
cint AEFileWriter::writeUInt (const ullint num, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes the (unsigned) integer as text to open file.
Parameters
num The unsigned integer to be written
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 300 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, and writeString().
writeFloat()
template<typename T > requires (std::is_floating_point<T>::value == true) cint AEFileWriter::writeFloat (const T num, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes the float value as text to the opened file.
Template Parameters
T The floating point type of the variable
Parameters
num The float number itself
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Todo
Add custom way to format the float number
Definition at line 598 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, and IS_SAME_NOCV.
writeBool()
cint AEFileWriter::writeBool (const bool num, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes the boolean to file as text (true/false).
Parameters
num The bool to be written
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 329 of file AEFileWriter.hpp.
References ace::utils::boolToString(), and writeString().
writeChar()
cint AEFileWriter::writeChar (const char c, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes the single (ascii) character to the file.
Note
Essentially, it's the same as AEFileWriter::writeByte()
Parameters
c The char to be written
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 340 of file AEFileWriter.hpp.
References writeByte().
writeByte()
cint AEFileWriter::writeByte (const unsigned char cdata, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Writes one byte of data to the file.
Parameters
cdata byte value
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 352 of file AEFileWriter.hpp.
References writeData_ptr().
writeBytes() [1/2]
cint AEFileWriter::writeBytes (const void *const cdata, const std::size_t dsize, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write a stream of bytes to file, from pointer.
Note
Basically just a shortcut for the AEFileWriter::writerData_ptr()
Parameters
cdata Pointer to stream of bytes
dsize Size of that stream
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 364 of file AEFileWriter.hpp.
References writeData_ptr().
writeBytes() [2/2]
cint AEFileWriter::writeBytes (const std::vector< unsigned char > & cdata, const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write a stream of bytes to file, from std::vector<unsigned char>.
Parameters
cdata A std::vector to the data bytes
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 374 of file AEFileWriter.hpp.
References writeData_ptr().
writeData_ptr()
cint AEFileWriter::writeData_ptr (const void *const cdata, const std::size_t dcount, const std::size_t dsize = sizeof(char), const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) noexcept
Write binary data, as is, to file, and flush if necessary.
Difference with writeData_ref(): uses (const) pointer to the variable/data.
Note
Doesn't work with literals
Parameters
cdata Pointer to object to write
dcount Number of elements in an object
dsize Size, in bytes, for each element
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 35 of file AEFileWriter.cpp.
References _AEFW_EXIT_ON_WRITE_CLOSED_FILE, AEFW_ERR_WRITE_ERROR, AEFW_ERR_WRITE_SUCCESS, and AEFW_ERR_WRITE_ZERO_SIZE.
writeData_ref()
template<typename T > cint AEFileWriter::writeData_ref (const T & cdata, const std::size_t tsize = sizeof(T), const bool useAutoFlush = AEFW_DEFAULT_AUTOFLUSH) inline noexcept
Write binary data, as is, to file, and flush if necessary.
Difference with writeData_ptr(): uses (const) reference to the variable.
Note
Works with literals
Template Parameters
T The type of the data to be written
Parameters
cdata The variable/data itself
tsize The size of the variable/data. Defaults to the output of sizeof(T)
useAutoFlush Flag to use automatic file flushing each n writes, specified by m_ullFlushInterval
Returns
AEFW_ERR_WRITE_SUCCESS on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_WRITE_* flags (like AEFW_ERR_WRITE_ZERO_SIZE) on write error, AEFW_ERR_FLUSH_ERROR on flush error
Definition at line 403 of file AEFileWriter.hpp.
References writeData_ptr().
isOpen()
bool AEFileWriter::isOpen (void) const inline noexcept
Checks if a file is open by this file-writer.
Returns
True if file is open, false if otherwise
Definition at line 413 of file AEFileWriter.hpp.
References m_fpFilestr.
isClosed()
bool AEFileWriter::isClosed (void) const inline noexcept
Checks if a file isn't open by this file-writer.
Returns
True if file is closed/not open, false if otherwise
Definition at line 421 of file AEFileWriter.hpp.
References isOpen().
getFileSize()
llint AEFileWriter::getFileSize (void) const inline noexcept
Returns size of the file in bytes.
Warning
Fails and returns AEFW_ERR_OPEN_FILE_WRONG_FLAG, if the flag that was used to open the current file is AEFW_FLAG_APPEND_NO_CURSOR_MOVE
Returns
File size in bytes if file is open; otherwise AEFW_ERR_FILE_NOT_OPEN
Definition at line 430 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_CLOSED_FILE, _AEFW_EXIT_ON_NO_CURSOR_MOVE, and m_fpFilestr.
getFullFileName()
std::string AEFileWriter::getFullFileName (void) const inline noexcept
Returns the full name of currently open file, including the relative path, if such was provided.
Note
If no relative path was provided when opening the file, then output of AEFileWriter::getFullFileName() is equivalent to AEFileWriter::getFileName()
Returns
std::string of the opened file (including relative path if was given); empty string otherwise
Definition at line 446 of file AEFileWriter.hpp.
References m_sFilename.
getRelativePath()
std::string AEFileWriter::getRelativePath (void) const inline
Returns the relative path of the opened file.
If the file was opened in the same directory as the executable (no relative path provided), returns "./"
Returns
std::string of the relative file path of opened file; empty string otherwise
Definition at line 455 of file AEFileWriter.hpp.
References isClosed(), and m_sFilename.
getFileName()
std::string AEFileWriter::getFileName (void) const inline
Returns the name of the opened file, devoid of the path.
Returns
std::string of the opened file name; emtpy string otherwise
Definition at line 472 of file AEFileWriter.hpp.
References m_sFilename.
getFullPath()
std::string AEFileWriter::getFullPath (void) const inline
Returns the full, absolute path of the opened file.
Returns
std::string of the absolute path of the opened file; empty string otherwise
Definition at line 486 of file AEFileWriter.hpp.
References isClosed(), and m_sFilename.
getFilePtr()
std::FILE * AEFileWriter::getFilePtr (void) const inline noexcept
Returns the file pointer of this file-writer.
Returns
Pointer to FILE used in the file writer
Definition at line 497 of file AEFileWriter.hpp.
References m_fpFilestr.
getCursorPos()
llint AEFileWriter::getCursorPos (void) const inline noexcept
Returns current write cursor position.
Warning
Fails and returns AEFW_ERR_OPEN_FILE_WRONG_FLAG, if the flag that was used to open the current file is AEFW_FLAG_APPEND_NO_CURSOR_MOVE
Returns
Current write cursor position, starting from 0, if file is open; otherwise AEFR_ERR_FILE_NOT_OPEN, AEFW_ERR_OPEN_FILE_WRONG_FLAG if wrong open flag given;
Definition at line 508 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_CLOSED_FILE, _AEFW_EXIT_ON_NO_CURSOR_MOVE, and m_fpFilestr.
setCursorPos()
int AEFileWriter::setCursorPos (const llint pos, const int origin = SEEK_CUR) const inline noexcept
Sets read cursor position to pos from origin.
Note
If cursor is beyond EOF, it fills space between EOF and cursor with null-bytes when data is written.
Warning
Fails and returns AEFW_ERR_OPEN_FILE_WRONG_FLAG, if the flag that was used to open the current file is AEFW_FLAG_APPEND_NO_CURSOR_MOVE
Note
If origin is not SEEK_SET, SEEK_CUR or SEEK_END returns AEFR_ERR_READING_EOF
Parameters
pos Position to be set to relative to origin (same as "offset" in fseek)
origin Relative origin for the operation. Google SEEK_SET, SEEK_CUR and SEEK_END for more details
Returns
0 on success; otherwise AEFW_ERR_FILE_NOT_OPEN if file isn't open, AEFW_ERR_OPEN_FILE_WRONG_FLAG if wrong open flag given, or other things that fseek can return
Definition at line 523 of file AEFileWriter.hpp.
References _AEFW_EXIT_ON_CLOSED_FILE, _AEFW_EXIT_ON_NO_CURSOR_MOVE, AEFW_ERR_WRITE_ERROR, and m_fpFilestr.
getTotalWrites()
ullint AEFileWriter::getTotalWrites (void) const inline noexcept
Returns total write requests made to file.
Returns
Amount of times the write operation has been called on this AEFileWriter instance
Definition at line 540 of file AEFileWriter.hpp.
References m_ullTotalWrites.
getLastWrittenAmount()
std::size_t AEFileWriter::getLastWrittenAmount (void) const inline noexcept
Gets the last written amount of bytes from the opened file.
Note
If last operation failed and no bytes were written (closed file, write error) – returns 0
Returns
std::size_t of the amount of bytes written in the last write operation
Definition at line 549 of file AEFileWriter.hpp.
References m_szLastWrittenAmount.
autoFlush()
void AEFileWriter::autoFlush (void) inline private noexcept
Checks for and performs the auto-flush operation if required.
Note
Does nothing if AEFW_AUTOFLUSH_ENABLE is not defined
Definition at line 566 of file AEFileWriter.hpp.
References flushFile(), and m_ullTotalWrites.
REGISTER_MODULE()
AEFileWriter::REGISTER_MODULE (AEFileWriter) private
getModuleAmount()
static ullint __AEModuleBase< AEFileWriter >::getModuleAmount (void) inline static noexcept inherited
Get the amount of the currently-alive instances of module T
See also
__AEModuleBase<T>::m_ullModulesAlive
Returns
Unsigned long long of the alive module amount
Definition at line 114 of file AEModuleBase.hpp.
getModuleName()
static constexpr const std::string_view __AEModuleBase< AEFileWriter >::getModuleName (void) static constexpr noexcept inherited
Get the name of the module
Attention
You need to add REGISTER_MODULE() to the end of the class declarations if you want to use this thing
See also
REGISTER_MODULE()
Returns
The name of the module as a const std::strinv_view type
Member Data Documentation
m_ullFlushInterval
ullint AEFileWriter::m_ullFlushInterval
Interval in write operations before automatic flush operation.
1 – flush every write operation, etc; -1 – almost never
Definition at line 557 of file AEFileWriter.hpp.
m_sFilename
std::string AEFileWriter::m_sFilename private
Full filename and relative path.
Definition at line 579 of file AEFileWriter.hpp.
m_ullTotalWrites
std::atomic<ullint> AEFileWriter::m_ullTotalWrites private
Counter for total write operations for file.
Definition at line 581 of file AEFileWriter.hpp.
m_szLastWrittenAmount
std::size_t AEFileWriter::m_szLastWrittenAmount private
The amount of written bytes during last operation.
Definition at line 583 of file AEFileWriter.hpp.
m_fpFilestr
std::FILE* AEFileWriter::m_fpFilestr private
Object for file writing.
Definition at line 585 of file AEFileWriter.hpp.
m_cFlags
cint AEFileWriter::m_cFlags private
Flags that were used to open the file.
Definition at line 587 of file AEFileWriter.hpp.
m_ullModulesAlive
std::atomic<std::size_t> __AEModuleBase< AEFileWriter >::m_ullModulesAlive inline static protected inherited
Amount of the currently-alive (not destroyed) instances of the module.
Definition at line 131 of file AEModuleBase.hpp.
The documentation for this class was generated from the following files:
AEFileWriter/include/AEFileWriter.hpp
AEFileWriter/src/AEFileWriter.cpp