ArtyK's Console Engine: AELogEntry Struct Reference
AELogEntry Struct Reference
The structure for the data of the log entry to be manipulated with the log files.
#include <AELogEntry.hpp>
Public Member Functions
AELogEntry & operator= (const AELogEntry &entry) noexcept
Copy assignment operator – copies data from the passed node.
void copyEntryFull (const AELogEntry &entry) noexcept
Makes a full copy of the log entry, including the pointer to the next node.
void copyEntry (const AELogEntry &entry) noexcept
Makes a normal copy of the log entry, copying everything but the pointer to the next node.
void copyEntryReduced (const AELogEntry &entry) noexcept
Makes a reduced copy of the log entry, including only the message, module name, and type.
std::string toString ()
Format the entry and convert it into std::string.
Static Public Member Functions
static void clearEntry (AELogEntry &entry) noexcept
Clears the current entry and sets its values to zero/invalid.
static void clearEntryFull (AELogEntry &entry) noexcept
Fully clears the entry, resetting it to the default values.
static AELogEntry * makeQueue (const std::size_t amt, const bool loopQueue=true, AELogEntry *oldqueue=nullptr)
Allocates the queue of the given size on the heap and returns the pointer to it's first node.
static int formatEntry (char *const str, const AELogEntry &entry) noexcept
Formats the passed entry to the given c-string.
static constexpr const char *const typeToString (const cint logtype) noexcept
Deduces the entry's log type and returns a c-string of it.
static constexpr cint stringToType (const std::string_view str) noexcept
Deduces the string representation of a type (as appears in the log file) to a corresponding type number.
static cint parseStringEntry (AELogEntry &entry, const std::string_view entryString, const cint flags=0b0001111)
Parses a given string as a log entry, and write it into passed entry object.
static constexpr AELogEntry emptyEntry () noexcept
Returns the empty, invalid entry, with no data.
Public Attributes
char m_sLogMessage [AELE_MESSAGE_SIZE+1] {}
The message of the log entry.
char m_sModuleName [AELE_MODULENAME_SIZE+1] {}
The name of the module that issued the log entry.
std::time_t m_tmLogTime = AENULL
The time when this log entry was created.
AELogEntry * m_pNextNode = nullptr
The pointer to the next log entry in the queue.
cint m_cLogType = -1
The type of the log entry.
std::atomic< cint > m_cStatus = 0
The status flag in the entry to show if the entry is ready, being read/set, or is invalid.
Detailed Description
The structure for the data of the log entry to be manipulated with the log files.
The flags start with AELE_
Definition at line 81 of file AELogEntry.hpp.
Member Function Documentation
operator=()
AELogEntry & AELogEntry::operator= (const AELogEntry & entry) inline noexcept
Copy assignment operator – copies data from the passed node.
Note
The pointer to the next node is omitted from the operation;
Uses the AELogEntry::copyEntry()
Parameters
entry
Returns
Definition at line 105 of file AELogEntry.hpp.
References copyEntry().
copyEntryFull()
void AELogEntry::copyEntryFull (const AELogEntry & entry) inline noexcept
Makes a full copy of the log entry, including the pointer to the next node.
Parameters
entry The entry to copy data from
Definition at line 114 of file AELogEntry.hpp.
References aeoffsetof, and m_cStatus.
copyEntry()
void AELogEntry::copyEntry (const AELogEntry & entry) inline noexcept
Makes a normal copy of the log entry, copying everything but the pointer to the next node.
Parameters
entry The entry to copy data from
Definition at line 127 of file AELogEntry.hpp.
References aeoffsetof, and m_pNextNode.
copyEntryReduced()
void AELogEntry::copyEntryReduced (const AELogEntry & entry) inline noexcept
Makes a reduced copy of the log entry, including only the message, module name, and type.
Parameters
entry The entry to copy data from
Definition at line 141 of file AELogEntry.hpp.
References aeoffsetof, and m_pNextNode.
clearEntry()
static void AELogEntry::clearEntry (AELogEntry & entry) inline static noexcept
Clears the current entry and sets its values to zero/invalid.
Parameters
entry The entry to clear
Definition at line 154 of file AELogEntry.hpp.
References AELE_STATUS_INVALID, AENULL, aeoffsetof, and m_pNextNode.
clearEntryFull()
static void AELogEntry::clearEntryFull (AELogEntry & entry) inline static noexcept
Fully clears the entry, resetting it to the default values.
Parameters
entry
Definition at line 164 of file AELogEntry.hpp.
References emptyEntry().
makeQueue()
static AELogEntry * AELogEntry::makeQueue (const std::size_t amt, const bool loopQueue = true, AELogEntry * oldqueue = nullptr) inline static
Allocates the queue of the given size on the heap and returns the pointer to it's first node.
Optionally may loop the newly-allocated queue to the old queue.
Note
You should delete[] the pointer after you're done using it (unless you like mem-leaks)
If the amt is 0, throws the std::runtime exception
Parameters
amt The amount of entries in the queue(size)
loopQueue The flag to indicate whether to loop the generated queue at all
oldqueue The pointer to the old queue to loop the new queue to.
Returns
Pointer to the first node of the allocated queue
Definition at line 178 of file AELogEntry.hpp.
References aceAssert, and m_pNextNode.
formatEntry()
static int AELogEntry::formatEntry (char *const str, const AELogEntry & entry) inline static noexcept
Formats the passed entry to the given c-string.
Note
The size of the c-string must be of AELE_FORMAT_MAX_SIZE !
Parameters
str The c-string to format the data to
entry The entry object to format its data to string
Returns
The length of the resulting string
Definition at line 212 of file AELogEntry.hpp.
References AELE_FORMAT_MAX_SIZE, AELE_FORMAT_STRING, AELE_FORMAT_STRING_DEBUG, AELOG_TYPE_DEBUG, DATETIME_STRING_SIZE, ace::utils::formatDate(), and typeToString().
typeToString()
static constexpr const char *const AELogEntry::typeToString (const cint logtype) inline static constexpr noexcept
Deduces the entry's log type and returns a c-string of it.
Parameters
logtype The value of the log type
Returns
c-string of the type
Definition at line 230 of file AELogEntry.hpp.
References AELOG_TYPE_DEBUG, AELOG_TYPE_ERROR, AELOG_TYPE_FATAL_ERROR, AELOG_TYPE_INFO, AELOG_TYPE_OK, AELOG_TYPE_SEVERE_WARN, AELOG_TYPE_SUCCESS, and AELOG_TYPE_WARN.
stringToType()
static constexpr cint AELogEntry::stringToType (const std::string_view str) inline static constexpr noexcept
Deduces the string representation of a type (as appears in the log file) to a corresponding type number.
Note
the size of the string needs to be 14 characters total, format: [TYPE IN CAPS][remaining space padding to make it 14 characters]
Parameters
str The string to check
Returns
The number corresponding to the deduced type; AELOG_TYPE_INVALID otherwise
Definition at line 246 of file AELogEntry.hpp.
References AELOG_TYPE_DEBUG, AELOG_TYPE_ERROR, AELOG_TYPE_FATAL_ERROR, AELOG_TYPE_INFO, AELOG_TYPE_INVALID, AELOG_TYPE_OK, AELOG_TYPE_SEVERE_WARN, AELOG_TYPE_SUCCESS, and AELOG_TYPE_WARN.
parseStringEntry()
static cint AELogEntry::parseStringEntry (AELogEntry & entry, const std::string_view entryString, const cint flags = 0b0001111) inline static
Parses a given string as a log entry, and write it into passed entry object.
Note
If the string is less than AELE_FORMAT_MIN_SIZE or more than AELE_FORMAT_MAX_SIZE, fails the check with AELE_ERR_INVALID_LENGTH
Parameters
entry The log entry object to write data to
entryString The string to parse
flags The flags for parsing. Refer to AELE_PARSE_STRING_* (like AELE_PARSE_STRING_JUST_VALIDATE)
Returns
AELE_ERR_NOERROR (0) on success, other AELE error flags otherwise
Definition at line 285 of file AELogEntry.hpp.
References AELE_ERR_INVALID_FORMAT, AELE_ERR_INVALID_LENGTH, AELE_ERR_INVALID_MNAME, AELE_ERR_INVALID_TIME, AELE_ERR_INVALID_TYPE, AELE_ERR_NOERROR, AELE_FORMAT_MAX_SIZE, AELE_FORMAT_MIN_SIZE, AELE_MESSAGE_DEBUG_SIZE, AELE_MESSAGE_SIZE, AELE_MODULENAME_SIZE, AELE_PARSE_STRING_FULL, AELE_PARSE_STRING_JUST_VALIDATE, AELE_PARSE_STRING_MESSG, AELE_PARSE_STRING_MNAME, AELE_PARSE_STRING_TIME, AELE_PARSE_STRING_TYPE, AELE_STATUS_READY, AELOG_TYPE_DEBUG, clearEntry(), ace::utils::isAlNumUs(), m_cLogType, m_cStatus, m_sLogMessage, m_sModuleName, m_tmLogTime, ace::utils::stringToDate(), and stringToType().
toString()
std::string AELogEntry::toString () inline
Format the entry and convert it into std::string.
Returns
std::string of the converted entry
Definition at line 396 of file AELogEntry.hpp.
References AELE_FORMAT_MAX_SIZE, and formatEntry().
emptyEntry()
static constexpr AELogEntry AELogEntry::emptyEntry () inline static constexpr noexcept
Returns the empty, invalid entry, with no data.
Returns
AELogEntry instance of an empty entry
Definition at line 407 of file AELogEntry.hpp.
Member Data Documentation
m_sLogMessage
char AELogEntry::m_sLogMessage[AELE_MESSAGE_SIZE+1] {}
The message of the log entry.
Definition at line 84 of file AELogEntry.hpp.
m_sModuleName
char AELogEntry::m_sModuleName[AELE_MODULENAME_SIZE+1] {}
The name of the module that issued the log entry.
Definition at line 86 of file AELogEntry.hpp.
m_tmLogTime
std::time_t AELogEntry::m_tmLogTime = AENULL
The time when this log entry was created.
Definition at line 88 of file AELogEntry.hpp.
m_pNextNode
AELogEntry* AELogEntry::m_pNextNode = nullptr
The pointer to the next log entry in the queue.
Definition at line 90 of file AELogEntry.hpp.
m_cLogType
cint AELogEntry::m_cLogType = -1
The type of the log entry.
See also
AELogTypes.hpp
Definition at line 93 of file AELogEntry.hpp.
m_cStatus
std::atomic<cint> AELogEntry::m_cStatus = 0
The status flag in the entry to show if the entry is ready, being read/set, or is invalid.
Definition at line 95 of file AELogEntry.hpp.
The documentation for this struct was generated from the following file:
AECustomTypes/include/AELogEntry.hpp